/**
 * subsystemWeightConstants.ts - Constants for subsystem weight modulation
 *
 * Centralizes magic numbers used when subsystem weights modulate AI decision
 * thresholds and criteria. Keeping these in one place makes it easy to tune
 * the sensitivity of each subsystem to its strategic weight.
 */

/**
 * Default subsystem weight when no weight is provided or subsystemWeights
 * is undefined. A weight of 1.0 means "no modulation" — baseline behavior.
 */
export const DEFAULT_SUBSYSTEM_WEIGHT = 1.0;

// ---------------------------------------------------------------------------
// Auction AI weight constants
// ---------------------------------------------------------------------------

/**
 * Base rating threshold below which a horse is considered an underperformer.
 * At weight = 1.0, horses with overall rating < this value may be consigned.
 */
export const CONSIGN_UNDERPERFORMER_RATING_THRESHOLD = 40;

/**
 * Base age threshold above which an underperforming horse may be consigned.
 * At weight = 1.0, horses older than this value with low rating are consigned.
 */
export const CONSIGN_UNDERPERFORMER_AGE_THRESHOLD = 5;

/**
 * How much the rating threshold relaxes per unit of weight above 1.0.
 * E.g., weight = 1.5 → rating threshold increases by 0.5 * this value.
 */
export const CONSIGN_RATING_RELAXATION_PER_WEIGHT = 20;

/**
 * How much the age threshold relaxes per unit of weight above 1.0.
 * E.g., weight = 1.5 → age threshold decreases by 0.5 * this value.
 */
export const CONSIGN_AGE_RELAXATION_PER_WEIGHT = 2;

/**
 * Base adaptive threshold for bidding decisions.
 */
export const BID_BASE_THRESHOLD = 50;

/**
 * Multiplier to convert horse overall rating into an estimated value.
 * Used for reserve price estimation and max bid calculation.
 */
export const HORSE_RATING_TO_VALUE_MULTIPLIER = 1000;

// ---------------------------------------------------------------------------
// Market AI weight constants
// ---------------------------------------------------------------------------

/**
 * Base adaptive threshold for market purchase decisions.
 */
export const PURCHASE_BASE_THRESHOLD = 50;

/**
 * Cash buffer multiplier for market purchases. Stable must have at least
 * this fraction of the purchase price remaining after buying.
 */
export const PURCHASE_CASH_BUFFER_MULTIPLIER = 1.1;

// ---------------------------------------------------------------------------
// Facility AI weight constants
// ---------------------------------------------------------------------------

/**
 * Base adaptive threshold for facility upgrade decisions.
 */
export const FACILITY_UPGRADE_BASE_THRESHOLD = 50;

// ---------------------------------------------------------------------------
// Intent priority constants
// ---------------------------------------------------------------------------

/**
 * Priority for consignment intents generated by the NPC auction intent generator.
 */
export const CONSIGNMENT_INTENT_PRIORITY = 40;
