// Canadian Grade 1 stakes races (run at Woodbine).
// Source: Wikipedia – Category:Grade 1 stakes races in Canada.
// Distances normalized to meters. dayOfYear schedules each race on the
// game's 365-day annual cycle (day 1 = Jan 1).

export type Grade = "G1" | "G2" | "G3";

export type GradedRace = {
  key: string;
  name: string;
  track: string;
  grade: Grade;
  distance: number;
  surface: "Turf" | "Dirt" | "Synthetic";
  purse: number;
  dayOfYear: number;
  restrictions?: { minAge?: number; maxAge?: number };
  note?: string; // e.g. "Fillies & Mares" — display-only
};

function doy(month: number, day: number): number {
  const cum = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
  return cum[month - 1] + day;
}

export const GRADED_RACES: GradedRace[] = [
  { key: "woodbine-mile", name: "Woodbine Mile", track: "Woodbine", grade: "G1", distance: 1600, surface: "Turf", purse: 1000000, dayOfYear: doy(9, 14), restrictions: { minAge: 3 } },
  { key: "ep-taylor", name: "E. P. Taylor Stakes", track: "Woodbine", grade: "G1", distance: 2000, surface: "Turf", purse: 600000, dayOfYear: doy(10, 12), restrictions: { minAge: 3 } },
  { key: "canadian-international", name: "Canadian International Stakes", track: "Woodbine", grade: "G1", distance: 2400, surface: "Turf", purse: 600000, dayOfYear: doy(10, 19), restrictions: { minAge: 3 } },
  { key: "northern-dancer-turf", name: "Northern Dancer Turf Stakes", track: "Woodbine", grade: "G1", distance: 2400, surface: "Turf", purse: 600000, dayOfYear: doy(9, 14), restrictions: { minAge: 3 } },
  { key: "highlander", name: "Highlander Stakes", track: "Woodbine", grade: "G1", distance: 1200, surface: "Turf", purse: 300000, dayOfYear: doy(7, 6), restrictions: { minAge: 3 } },
  { key: "summer-stakes", name: "Summer Stakes", track: "Woodbine", grade: "G1", distance: 1600, surface: "Turf", purse: 300000, dayOfYear: doy(9, 14), restrictions: { minAge: 2, maxAge: 2 } },
  { key: "natalma", name: "Natalma Stakes", track: "Woodbine", grade: "G1", distance: 1600, surface: "Turf", purse: 300000, dayOfYear: doy(9, 14), restrictions: { minAge: 2, maxAge: 2 } },

  // ============= UAE — Group 1 (Meydan, Dubai World Cup Carnival/Night) =============
  { key: "jebel-hatta", name: "Jebel Hatta", track: "Meydan", grade: "G1", distance: 1800, surface: "Turf", purse: 500000, dayOfYear: doy(1, 26), restrictions: { minAge: 4 } },
  { key: "al-maktoum-challenge", name: "Al Maktoum Challenge R3", track: "Meydan", grade: "G1", distance: 2000, surface: "Dirt", purse: 500000, dayOfYear: doy(1, 26), restrictions: { minAge: 4 } },
  { key: "al-quoz-sprint", name: "Al Quoz Sprint", track: "Meydan", grade: "G1", distance: 1200, surface: "Turf", purse: 1500000, dayOfYear: doy(3, 30), restrictions: { minAge: 3 } },
  { key: "dubai-golden-shaheen", name: "Dubai Golden Shaheen", track: "Meydan", grade: "G1", distance: 1200, surface: "Dirt", purse: 1500000, dayOfYear: doy(3, 30), restrictions: { minAge: 3 } },
  { key: "dubai-sheema-classic", name: "Dubai Sheema Classic", track: "Meydan", grade: "G1", distance: 2400, surface: "Turf", purse: 6000000, dayOfYear: doy(3, 30), restrictions: { minAge: 4 } },
  { key: "dubai-turf", name: "Dubai Turf", track: "Meydan", grade: "G1", distance: 1800, surface: "Turf", purse: 5000000, dayOfYear: doy(3, 30), restrictions: { minAge: 4 } },
  { key: "dubai-world-cup", name: "Dubai World Cup", track: "Meydan", grade: "G1", distance: 2000, surface: "Dirt", purse: 12000000, dayOfYear: doy(3, 30), restrictions: { minAge: 4 } },

  // ============= UAE — Group 2 =============
  { key: "al-fahidi-fort", name: "Al Fahidi Fort", track: "Meydan", grade: "G2", distance: 1400, surface: "Turf", purse: 250000, dayOfYear: doy(1, 12), restrictions: { minAge: 4 } },
  { key: "al-rashidiya", name: "Al Rashidiya", track: "Meydan", grade: "G2", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: doy(1, 19), restrictions: { minAge: 4 } },
  { key: "balanchine", name: "Balanchine", track: "Meydan", grade: "G2", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: doy(1, 26), restrictions: { minAge: 4 }, note: "Fillies & Mares" },
  { key: "cape-verdi", name: "Cape Verdi", track: "Meydan", grade: "G2", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: doy(1, 12), restrictions: { minAge: 4 }, note: "Fillies & Mares" },
  { key: "dubai-city-of-gold", name: "Dubai City of Gold", track: "Meydan", grade: "G2", distance: 2400, surface: "Turf", purse: 250000, dayOfYear: doy(3, 9), restrictions: { minAge: 4 } },
  { key: "dubai-gold-cup", name: "Dubai Gold Cup", track: "Meydan", grade: "G2", distance: 3200, surface: "Turf", purse: 1000000, dayOfYear: doy(3, 30), restrictions: { minAge: 4 } },
  { key: "godolphin-mile", name: "Godolphin Mile", track: "Meydan", grade: "G2", distance: 1600, surface: "Dirt", purse: 1000000, dayOfYear: doy(3, 30), restrictions: { minAge: 4 } },
  { key: "al-maktoum-mile", name: "Al Maktoum Mile", track: "Meydan", grade: "G2", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: doy(2, 9), restrictions: { minAge: 4 } },
  { key: "al-maktoum-classic", name: "Al Maktoum Classic R2", track: "Meydan", grade: "G2", distance: 1900, surface: "Dirt", purse: 350000, dayOfYear: doy(2, 9), restrictions: { minAge: 4 } },
  { key: "meydan-sprint", name: "Meydan Sprint", track: "Meydan", grade: "G2", distance: 1000, surface: "Turf", purse: 200000, dayOfYear: doy(3, 9), restrictions: { minAge: 3 } },
  { key: "singspiel-stakes", name: "Singspiel Stakes", track: "Meydan", grade: "G2", distance: 1800, surface: "Turf", purse: 200000, dayOfYear: doy(2, 16), restrictions: { minAge: 4 } },
  { key: "uae-derby", name: "UAE Derby", track: "Meydan", grade: "G2", distance: 1900, surface: "Dirt", purse: 1000000, dayOfYear: doy(3, 30), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "zabeel-mile", name: "Zabeel Mile", track: "Meydan", grade: "G2", distance: 1600, surface: "Turf", purse: 200000, dayOfYear: doy(2, 16), restrictions: { minAge: 3 } },

  // ============= UAE — Group 3 =============
  { key: "abu-dhabi-championship", name: "Abu Dhabi Championship", track: "Abu Dhabi", grade: "G3", distance: 2200, surface: "Turf", purse: 200000, dayOfYear: doy(2, 23), restrictions: { minAge: 4 } },
  { key: "al-shindagha-sprint", name: "Al Shindagha Sprint", track: "Meydan", grade: "G3", distance: 1200, surface: "Dirt", purse: 175000, dayOfYear: doy(1, 26), restrictions: { minAge: 3 } },
  { key: "burj-nahaar", name: "Burj Nahaar", track: "Meydan", grade: "G3", distance: 1600, surface: "Dirt", purse: 200000, dayOfYear: doy(3, 9), restrictions: { minAge: 4 } },
  { key: "dubai-millennium-stakes", name: "Dubai Millennium Stakes", track: "Meydan", grade: "G3", distance: 2000, surface: "Turf", purse: 175000, dayOfYear: doy(3, 9), restrictions: { minAge: 4 } },
  { key: "dubawi-stakes", name: "Dubawi Stakes", track: "Meydan", grade: "G3", distance: 1200, surface: "Dirt", purse: 175000, dayOfYear: doy(1, 12), restrictions: { minAge: 3 } },
  { key: "firebreak-stakes", name: "Firebreak Stakes", track: "Meydan", grade: "G3", distance: 1600, surface: "Dirt", purse: 175000, dayOfYear: doy(2, 9), restrictions: { minAge: 4 } },
  { key: "jebel-ali-mile", name: "Jebel Ali Mile", track: "Jebel Ali", grade: "G3", distance: 1600, surface: "Dirt", purse: 200000, dayOfYear: doy(3, 2), restrictions: { minAge: 4 } },
  { key: "mahab-al-shimaal", name: "Mahab Al Shimaal", track: "Meydan", grade: "G3", distance: 1200, surface: "Dirt", purse: 200000, dayOfYear: doy(3, 9), restrictions: { minAge: 3 } },
  { key: "nad-al-sheba-trophy", name: "Nad Al Sheba Trophy", track: "Meydan", grade: "G3", distance: 2810, surface: "Turf", purse: 200000, dayOfYear: doy(3, 9), restrictions: { minAge: 4 } },
  { key: "nad-al-sheba-turf-sprint", name: "Nad Al Sheba Turf Sprint", track: "Meydan", grade: "G3", distance: 1200, surface: "Turf", purse: 175000, dayOfYear: doy(1, 19), restrictions: { minAge: 3 } },
  { key: "uae-oaks", name: "UAE Oaks", track: "Meydan", grade: "G3", distance: 1900, surface: "Dirt", purse: 250000, dayOfYear: doy(2, 16), restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "uae-2000-guineas", name: "UAE 2000 Guineas", track: "Meydan", grade: "G3", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: doy(2, 9), restrictions: { minAge: 3, maxAge: 3 } },

  // ============= South America — Group One (Argentina, Brazil, Chile) =============
  { key: "argentina-gran-premio-miguel-alfredo-mart-nez-de-hoz", name: "Gran Premio Miguel Alfredo Martínez de Hoz", track: "Hipódromo de San Isidro", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 47, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-gilberto-lerena", name: "Gran Premio Gilberto Lerena", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2200, surface: "Turf", purse: 250000, dayOfYear: 111, restrictions: { minAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-de-honor", name: "Gran Premio de Honor", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 93, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-jorge-de-atucha", name: "Gran Premio Jorge de Atucha", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1500, surface: "Dirt", purse: 250000, dayOfYear: 126, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies" },
  { key: "argentina-gran-premio-montevideo", name: "Gran Premio Montevideo", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1500, surface: "Dirt", purse: 250000, dayOfYear: 132, restrictions: { minAge: 2, maxAge: 2 }, note: "Colts" },
  { key: "argentina-gran-premio-ciudad-de-buenos-aires", name: "Gran Premio Ciudad de Buenos Aires", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1000, surface: "Dirt", purse: 250000, dayOfYear: 134, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-de-las-am-ricas-osaf", name: "Gran Premio de Las Américas - OSAF", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 129, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-criadores", name: "Gran Premio Criadores", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 142, restrictions: { minAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-rep-blica-argentina", name: "Gran Premio República Argentina", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 133, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-25-de-mayo-copa-dr-enrique-olivera", name: "Gran Premio 25 de Mayo - Copa Dr. Enrique Olivera", track: "Hipódromo de San Isidro", grade: "G1", distance: 2400, surface: "Turf", purse: 250000, dayOfYear: 126, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-de-potrancas", name: "Gran Premio de Potrancas", track: "Hipódromo de San Isidro", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 136, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies" },
  { key: "argentina-gran-premio-gran-criterium", name: "Gran Premio Gran Criterium", track: "Hipódromo de San Isidro", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 124, restrictions: { minAge: 2, maxAge: 2 }, note: "Colts" },
  { key: "argentina-gran-premio-estrellas-juvenile-fillies", name: "Gran Premio Estrellas Juvenile Fillies", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 175, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies" },
  { key: "argentina-gran-premio-estrellas-juvenile", name: "Gran Premio Estrellas Juvenile", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 157, restrictions: { minAge: 2, maxAge: 2 }, note: "Colts" },
  { key: "argentina-gran-premio-estrellas-sprint", name: "Gran Premio Estrellas Sprint", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1000, surface: "Dirt", purse: 250000, dayOfYear: 167, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-estrellas-mile", name: "Gran Premio Estrellas Mile", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 174, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-estrellas-classic", name: "Gran Premio Estrellas Classic", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 172, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-estrellas-distaff", name: "Gran Premio Estrellas Distaff", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1800, surface: "Dirt", purse: 250000, dayOfYear: 155, restrictions: { minAge: 3 }, note: "Fillies" },
  { key: "argentina-dos-mil-guineas", name: "Dos Mil Guineas", track: "Hipódromo de San Isidro", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 189, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "argentina-gran-premio-polla-de-potrancas", name: "Gran Premio Polla de Potrancas", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 264, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-polla-de-potrillos", name: "Gran Premio Polla de Potrillos", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 251, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "argentina-gran-premio-general-san-mart-n", name: "Gran Premio General San Martín", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2400, surface: "Turf", purse: 250000, dayOfYear: 268, restrictions: { minAge: 4 } },
  { key: "argentina-gran-premio-selecci-n-de-potrancas", name: "Gran Premio Selección de Potrancas", track: "Hipódromo de La Plata", grade: "G1", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 247, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-selecci-n", name: "Gran Premio Selección", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 297, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-jockey-club", name: "Gran Premio Jockey Club", track: "Hipódromo de San Isidro", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 294, restrictions: { minAge: 3, maxAge: 3 } },
  { key: "argentina-gran-premio-san-isidro-copa-melchor-ngel-posse", name: "Gran Premio San Isidro - Copa Melchor Ángel Posse", track: "Hipódromo de San Isidro", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 282, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-suipacha", name: "Gran Premio Suipacha", track: "Hipódromo de San Isidro", grade: "G1", distance: 1000, surface: "Turf", purse: 250000, dayOfYear: 276, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-diamante", name: "Gran Premio Diamante", track: "Hipódromo de San Isidro", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 296, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-copa-de-oro-alfredo-lalor", name: "Gran Premio Copa de Oro - Alfredo Lalor", track: "Hipódromo de San Isidro", grade: "G1", distance: 2400, surface: "Turf", purse: 250000, dayOfYear: 325, restrictions: { minAge: 4 } },
  { key: "argentina-gran-premio-enrique-acebal", name: "Gran Premio Enrique Acebal", track: "Hipódromo de San Isidro", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 307, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-nacional", name: "Gran Premio Nacional", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 2500, surface: "Dirt", purse: 750000, dayOfYear: 322, restrictions: { minAge: 3, maxAge: 3 } },
  { key: "argentina-gran-premio-maip", name: "Gran Premio Maipú", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1000, surface: "Dirt", purse: 250000, dayOfYear: 327, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-palermo", name: "Gran Premio Palermo", track: "Hipódromo Argentino de Palermo", grade: "G1", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 322, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-dardo-rocha", name: "Gran Premio Dardo Rocha", track: "Hipódromo de La Plata", grade: "G1", distance: 2400, surface: "Dirt", purse: 250000, dayOfYear: 323, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-copa-de-plata-roberto-vasquez-mansilla", name: "Gran Premio Copa de Plata Roberto Vasquez Mansilla Internacional", track: "Hipódromo de San Isidro", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 353, restrictions: { minAge: 3 }, note: "Fillies" },
  { key: "argentina-gran-premio-carlos-pellegrini-internacional", name: "Gran Premio Carlos Pellegrini Internacional", track: "Hipódromo de San Isidro", grade: "G1", distance: 2400, surface: "Turf", purse: 750000, dayOfYear: 355, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-f-lix-de-lzaga-unzu-internacional", name: "Gran Premio Félix de Álzaga Unzué Internacional", track: "Hipódromo de San Isidro", grade: "G1", distance: 1000, surface: "Turf", purse: 250000, dayOfYear: 343, restrictions: { minAge: 3 } },
  { key: "argentina-gran-premio-joaqu-n-s-de-anchorena-internacional", name: "Gran Premio Joaquín S. de Anchorena Internacional", track: "Hipódromo de San Isidro", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 339, restrictions: { minAge: 3 } },
  { key: "brazil-grande-pr-mio-estado-do-rio-de-janeiro", name: "Grande Prêmio Estado do Rio de Janeiro", track: "Hipódromo da Gávea", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 45, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-henrique-possollo", name: "Grande Prêmio Henrique Possollo", track: "Hipódromo da Gávea", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 54, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-diana", name: "Grande Prêmio Diana", track: "Hipódromo da Gávea", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 64, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-francisco-eduardo-e-linneo-eduardo-de-p", name: "Grande Prêmio Francisco Eduardo e Linneo Eduardo de Paula Machado", track: "Hipódromo da Gávea", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 62, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-cruzeiro-do-sul-brazilian-derby", name: "Grande Prêmio Cruzeiro do Sul (Brazilian Derby)", track: "Hipódromo da Gávea", grade: "G1", distance: 2400, surface: "Turf", purse: 750000, dayOfYear: 109, restrictions: { minAge: 3, maxAge: 3 } },
  { key: "brazil-grande-pr-mio-z-lia-gonzaga-peixoto-de-castro", name: "Grande Prêmio Zélia Gonzaga Peixoto de Castro", track: "Hipódromo da Gávea", grade: "G1", distance: 2400, surface: "Turf", purse: 250000, dayOfYear: 116, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-juliano-martins", name: "Grande Prêmio Juliano Martins", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 1500, surface: "Turf", purse: 250000, dayOfYear: 131, restrictions: { minAge: 2, maxAge: 2 } },
  { key: "brazil-grande-pr-mio-jo-o-cec-lio-ferraz", name: "Grande Prêmio João Cecílio Ferraz", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 1500, surface: "Turf", purse: 250000, dayOfYear: 124, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-a-b-c-p-c-c", name: "Grande Prêmio A.B.C.P.C.C.", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 1000, surface: "Turf", purse: 250000, dayOfYear: 139, restrictions: { minAge: 2 } },
  { key: "brazil-grande-pr-mio-o-s-a-f-organizacion-sudamericana-de-fo", name: "Grande Prêmio O.S.A.F. - Organizacion Sudamericana de Fomento del Sangre Pura de Carrera", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 128, restrictions: { minAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-s-o-paulo", name: "Grande Prêmio São Paulo", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 2400, surface: "Turf", purse: 750000, dayOfYear: 125, restrictions: { minAge: 3 } },
  { key: "brazil-grande-pr-mio-jockey-club-brasileiro", name: "Grande Prêmio Jockey Club Brasileiro", track: "Hipódromo da Gávea", grade: "G1", distance: 1600, surface: "Turf", purse: 750000, dayOfYear: 165, restrictions: { minAge: 2, maxAge: 2 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-major-suckow", name: "Grande Prêmio Major Suckow", track: "Hipódromo da Gávea", grade: "G1", distance: 1000, surface: "Turf", purse: 250000, dayOfYear: 164, restrictions: { minAge: 3 } },
  { key: "brazil-grande-pr-mio-brasil", name: "Grande Prêmio Brasil", track: "Hipódromo da Gávea", grade: "G1", distance: 2400, surface: "Turf", purse: 750000, dayOfYear: 155, restrictions: { minAge: 4 } },
  { key: "brazil-grande-pr-mio-presidente-da-rep-blica", name: "Grande Prêmio Presidente da República", track: "Hipódromo da Gávea", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3 } },
  { key: "brazil-grande-pr-mio-roberto-e-nelson-grimaldi-seabra", name: "Grande Prêmio Roberto e Nelson Grimaldi Seabra", track: "Hipódromo da Gávea", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 173, restrictions: { minAge: 4 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-margarida-polak-lara-ta-a-de-prata", name: "Grande Prêmio Margarida Polak Lara - Taça de Prata", track: "Hipódromo da Gávea", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 237, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-jo-o-adhemar-de-almeida-prado-ta-a-de-p", name: "Grande Prêmio João Adhemar de Almeida Prado - Taça de Prata", track: "Hipódromo da Gávea", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 224, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-mathias-machline-abcpcc-cl-ssica", name: "Grande Prêmio Mathias Machline - ABCPCC Clássica", track: "Hipódromo da Gávea", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 216, restrictions: { minAge: 3 } },
  { key: "brazil-grande-pr-mio-ipiranga", name: "Grande Prêmio Ipiranga", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 253, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-bar-o-de-piracicaba", name: "Grande Prêmio Barão de Piracicaba", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 247, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-jockey-club-de-s-o-paulo", name: "Grande Prêmio Jockey Club de São Paulo", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 2000, surface: "Turf", purse: 750000, dayOfYear: 287, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-henrique-de-toledo-lara", name: "Grande Prêmio Henrique de Toledo Lara", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 297, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-derby-paulista", name: "Grande Prêmio Derby Paulista", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 2400, surface: "Turf", purse: 750000, dayOfYear: 307, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "brazil-grande-pr-mio-diana-x", name: "Grande Prêmio Diana", track: "Hipódromo Cidade Jardim", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 325, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "brazil-grande-pr-mio-linneo-de-paula-machado", name: "Grande Prêmio Linneo de Paula Machado", track: "Hipódromo da Gávea", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 345, restrictions: { minAge: 3, maxAge: 3 }, note: "Colts" },
  { key: "chile-cl-sico-el-derby", name: "Clásico El Derby", track: "Valparaiso Sporting Club", grade: "G1", distance: 2400, surface: "Turf", purse: 750000, dayOfYear: 34, restrictions: { minAge: 3, maxAge: 3 } },
  { key: "chile-gran-premio-hip-dromo-chile", name: "Gran Premio Hipódromo Chile", track: "Hipódromo Chile", grade: "G1", distance: 2200, surface: "Dirt", purse: 250000, dayOfYear: 128, restrictions: { minAge: 3 } },
  { key: "chile-cl-sico-club-h-pico-de-santiago-falabella", name: "Clásico Club Hípico de Santiago - Falabella", track: "Club Hípico de Santiago", grade: "G1", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 126, restrictions: { minAge: 3 } },
  { key: "chile-cl-sico-arturo-lyon-pe-a", name: "Clásico Arturo Lyon Peña", track: "Club Hípico de Santiago", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 168, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies" },
  { key: "chile-cl-sico-alberto-vial-infante", name: "Clásico Alberto Vial Infante", track: "Club Hípico de Santiago", grade: "G1", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 2, maxAge: 2 }, note: "Colts" },

  // ============= Canada — Triple Crown =============
  { key: "ca-kings-plate", name: "King's Plate", track: "Woodbine", grade: "G1", distance: 2000, surface: "Synthetic", purse: 1000000, dayOfYear: doy(8, 17), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "ca-prince-of-wales", name: "Prince of Wales Stakes", track: "Fort Erie", grade: "G1", distance: 1900, surface: "Dirt", purse: 400000, dayOfYear: doy(9, 9), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "ca-breeders-stakes", name: "Breeders' Stakes", track: "Woodbine", grade: "G1", distance: 2400, surface: "Turf", purse: 500000, dayOfYear: doy(10, 5), restrictions: { minAge: 3, maxAge: 3 } },

  // ============= Canada — Grade 2 (Woodbine) =============
  { key: "ca-eclipse", name: "Eclipse Stakes", track: "Woodbine", grade: "G2", distance: 1700, surface: "Synthetic", purse: 200000, dayOfYear: doy(5, 25), restrictions: { minAge: 4 } },
  { key: "ca-nassau", name: "Nassau Stakes", track: "Woodbine", grade: "G2", distance: 1600, surface: "Turf", purse: 200000, dayOfYear: doy(6, 15), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-connaught-cup", name: "Connaught Cup Stakes", track: "Woodbine", grade: "G2", distance: 1400, surface: "Turf", purse: 200000, dayOfYear: doy(6, 8), restrictions: { minAge: 4 } },
  { key: "ca-king-edward", name: "King Edward Stakes", track: "Woodbine", grade: "G2", distance: 1600, surface: "Turf", purse: 200000, dayOfYear: doy(6, 29), restrictions: { minAge: 3 } },
  { key: "ca-dance-smartly", name: "Dance Smartly Stakes", track: "Woodbine", grade: "G2", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: doy(7, 20), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-nijinsky", name: "Nijinsky Stakes", track: "Woodbine", grade: "G2", distance: 2400, surface: "Turf", purse: 200000, dayOfYear: doy(7, 27), restrictions: { minAge: 3 } },
  { key: "ca-play-the-king", name: "Play the King Stakes", track: "Woodbine", grade: "G2", distance: 1400, surface: "Turf", purse: 200000, dayOfYear: doy(8, 17), restrictions: { minAge: 3 } },
  { key: "ca-sky-classic", name: "Sky Classic Stakes", track: "Woodbine", grade: "G2", distance: 2200, surface: "Turf", purse: 200000, dayOfYear: doy(8, 24), restrictions: { minAge: 3 } },
  { key: "ca-royal-north", name: "Royal North Stakes", track: "Woodbine", grade: "G2", distance: 1200, surface: "Turf", purse: 200000, dayOfYear: doy(8, 10), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-canadian-stakes", name: "Canadian Stakes", track: "Woodbine", grade: "G2", distance: 1800, surface: "Turf", purse: 300000, dayOfYear: doy(9, 21), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-nearctic", name: "Nearctic Stakes", track: "Woodbine", grade: "G2", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: doy(10, 19), restrictions: { minAge: 3 } },
  { key: "ca-bessarabian", name: "Bessarabian Stakes", track: "Woodbine", grade: "G2", distance: 1400, surface: "Synthetic", purse: 175000, dayOfYear: doy(11, 9), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-kennedy-road", name: "Kennedy Road Stakes", track: "Woodbine", grade: "G2", distance: 1200, surface: "Synthetic", purse: 175000, dayOfYear: doy(11, 16), restrictions: { minAge: 3 } },

  // ============= Canada — Grade 3 =============
  { key: "ca-whimsical", name: "Whimsical Stakes", track: "Woodbine", grade: "G3", distance: 1200, surface: "Synthetic", purse: 125000, dayOfYear: doy(4, 27), restrictions: { minAge: 4 }, note: "Fillies & Mares" },
  { key: "ca-marine", name: "Marine Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 175000, dayOfYear: doy(5, 18), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "ca-hendrie", name: "Hendrie Stakes", track: "Woodbine", grade: "G3", distance: 1300, surface: "Synthetic", purse: 125000, dayOfYear: doy(5, 11), restrictions: { minAge: 4 }, note: "Fillies & Mares" },
  { key: "ca-selene", name: "Selene Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 175000, dayOfYear: doy(5, 25), restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "ca-jacques-cartier", name: "Jacques Cartier Stakes", track: "Woodbine", grade: "G3", distance: 1200, surface: "Synthetic", purse: 125000, dayOfYear: doy(5, 4), restrictions: { minAge: 4 } },
  { key: "ca-trillium", name: "Trillium Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 125000, dayOfYear: doy(6, 22), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-singspiel", name: "Singspiel Stakes (Canada)", track: "Woodbine", grade: "G3", distance: 2400, surface: "Turf", purse: 125000, dayOfYear: doy(6, 15), restrictions: { minAge: 3 } },
  { key: "ca-dominion-day", name: "Dominion Day Stakes", track: "Woodbine", grade: "G3", distance: 2000, surface: "Synthetic", purse: 175000, dayOfYear: doy(7, 1), restrictions: { minAge: 3 } },
  { key: "ca-vigil", name: "Vigil Stakes", track: "Woodbine", grade: "G3", distance: 1400, surface: "Synthetic", purse: 125000, dayOfYear: doy(7, 13), restrictions: { minAge: 4 } },
  { key: "ca-ontario-matron", name: "Ontario Matron Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 125000, dayOfYear: doy(7, 20), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-seagram-cup", name: "Seagram Cup Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 175000, dayOfYear: doy(8, 3), restrictions: { minAge: 3 } },
  { key: "ca-ontario-colleen", name: "Ontario Colleen Stakes", track: "Woodbine", grade: "G3", distance: 1600, surface: "Turf", purse: 125000, dayOfYear: doy(8, 10), restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies" },
  { key: "ca-canadian-derby", name: "Canadian Derby", track: "Century Mile", grade: "G3", distance: 2000, surface: "Synthetic", purse: 200000, dayOfYear: doy(8, 17), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "ca-ballerina", name: "Ballerina Stakes", track: "Hastings", grade: "G3", distance: 1800, surface: "Dirt", purse: 100000, dayOfYear: doy(8, 24), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-bold-venture", name: "Bold Venture Stakes", track: "Woodbine", grade: "G3", distance: 1300, surface: "Synthetic", purse: 125000, dayOfYear: doy(9, 7), restrictions: { minAge: 3 } },
  { key: "ca-seaway", name: "Seaway Stakes", track: "Woodbine", grade: "G3", distance: 1400, surface: "Synthetic", purse: 125000, dayOfYear: doy(9, 14), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-bc-derby", name: "British Columbia Derby", track: "Hastings", grade: "G3", distance: 1800, surface: "Dirt", purse: 200000, dayOfYear: doy(9, 21), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "ca-grey", name: "Grey Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 175000, dayOfYear: doy(10, 5), restrictions: { minAge: 2, maxAge: 2 } },
  { key: "ca-mazarine", name: "Mazarine Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Synthetic", purse: 175000, dayOfYear: doy(10, 12), restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies" },
  { key: "ca-ontario-derby", name: "Ontario Derby", track: "Woodbine", grade: "G3", distance: 1800, surface: "Synthetic", purse: 175000, dayOfYear: doy(10, 19), restrictions: { minAge: 3, maxAge: 3 } },
  { key: "ca-bc-premiers", name: "BC Premier's Handicap", track: "Hastings", grade: "G3", distance: 2200, surface: "Dirt", purse: 150000, dayOfYear: doy(10, 12), restrictions: { minAge: 3 } },
  { key: "ca-durham-cup", name: "Durham Cup Stakes", track: "Woodbine", grade: "G3", distance: 1800, surface: "Synthetic", purse: 125000, dayOfYear: doy(10, 26), restrictions: { minAge: 3 } },
  { key: "ca-autumn", name: "Autumn Stakes", track: "Woodbine", grade: "G3", distance: 1700, surface: "Turf", purse: 175000, dayOfYear: doy(11, 2), restrictions: { minAge: 3 } },
  { key: "ca-maple-leaf", name: "Maple Leaf Stakes", track: "Woodbine", grade: "G3", distance: 2000, surface: "Synthetic", purse: 175000, dayOfYear: doy(11, 9), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-ontario-fashion", name: "Ontario Fashion Stakes", track: "Woodbine", grade: "G3", distance: 1200, surface: "Synthetic", purse: 125000, dayOfYear: doy(11, 16), restrictions: { minAge: 3 }, note: "Fillies & Mares" },
  { key: "ca-valedictory", name: "Valedictory Stakes", track: "Woodbine", grade: "G3", distance: 2800, surface: "Synthetic", purse: 175000, dayOfYear: doy(12, 7), restrictions: { minAge: 3 } },

  // ============= Japan — JRA & NAR Graded =============
  { key: "jp-february-stakes", name: "February Stakes", track: "Tokyo", grade: "G1", distance: 1600, surface: "Dirt", purse: 800000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-takamatsunomiya-kinen", name: "Takamatsunomiya Kinen", track: "Chukyo", grade: "G1", distance: 1200, surface: "Turf", purse: 800000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-osaka-hai", name: "Ōsaka Hai", track: "Hanshin", grade: "G1", distance: 2000, surface: "Turf", purse: 800000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-oka-sho", name: "Oka Sho", track: "Hanshin", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-satsuki-sho", name: "Satsuki Shō", track: "Nakayama", grade: "G1", distance: 2000, surface: "Turf", purse: 800000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-tenno-sho-spring", name: "Tennō Shō (Spring)", track: "Kyoto", grade: "G1", distance: 3200, surface: "Turf", purse: 800000, dayOfYear: 105, restrictions: { minAge: 4 }, },
  { key: "jp-nhk-mile-cup", name: "NHK Mile Cup", track: "Tokyo", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 135, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-victoria-mile", name: "Victoria Mile", track: "Tokyo", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 135, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-yushun-himba", name: "Yushun Himba", track: "Tokyo", grade: "G1", distance: 2400, surface: "Turf", purse: 800000, dayOfYear: 135, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-tokyo-yushun", name: "Tōkyō Yūshun", track: "Tokyo", grade: "G1", distance: 2400, surface: "Turf", purse: 800000, dayOfYear: 135, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-yasuda-kinen", name: "Yasuda Kinen", track: "Tokyo", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-takarazuka-kinen", name: "Takarazuka Kinen", track: "Hanshin", grade: "G1", distance: 2200, surface: "Turf", purse: 800000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-sprinters-stakes", name: "Sprinters Stakes", track: "Nakayama", grade: "G1", distance: 1200, surface: "Turf", purse: 800000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-shuka-sho", name: "Shūka Sho", track: "Kyoto", grade: "G1", distance: 2000, surface: "Turf", purse: 800000, dayOfYear: 288, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-kikuka-sho", name: "Kikuka-shō", track: "Kyoto", grade: "G1", distance: 3000, surface: "Turf", purse: 800000, dayOfYear: 288, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-tenno-sho-autumn", name: "Tennō Shō (Autumn)", track: "Tokyo", grade: "G1", distance: 2000, surface: "Turf", purse: 800000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-queen-elizabeth-ii-cup", name: "Queen Elizabeth II Cup", track: "Kyoto", grade: "G1", distance: 2200, surface: "Turf", purse: 800000, dayOfYear: 319, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-mile-championship", name: "Mile Championship", track: "Kyoto", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-japan-cup", name: "Japan Cup", track: "Tokyo", grade: "G1", distance: 2400, surface: "Turf", purse: 800000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-champions-cup", name: "Champions Cup", track: "Chukyo", grade: "G1", distance: 1800, surface: "Dirt", purse: 800000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-hanshin-juvenile-fillies", name: "Hanshin Juvenile Fillies", track: "Hanshin", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 349, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies", },
  { key: "jp-asahi-hai-futurity-stakes", name: "Asahi Hai Futurity Stakes", track: "Hanshin", grade: "G1", distance: 1600, surface: "Turf", purse: 800000, dayOfYear: 349, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-arima-kinen", name: "Arima Kinen", track: "Nakayama", grade: "G1", distance: 2500, surface: "Turf", purse: 800000, dayOfYear: 349, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-hopeful-stakes", name: "Hopeful Stakes", track: "Nakayama", grade: "G1", distance: 2000, surface: "Turf", purse: 800000, dayOfYear: 349, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-nikkei-shinshun-hai", name: "Nikkei Shinshun Hai", track: "Kyoto", grade: "G2", distance: 2400, surface: "Turf", purse: 400000, dayOfYear: 15, restrictions: { minAge: 4 }, },
  { key: "jp-american-jockey-club-cup", name: "American Jockey Club Cup", track: "Nakayama", grade: "G2", distance: 2200, surface: "Turf", purse: 400000, dayOfYear: 15, restrictions: { minAge: 4 }, },
  { key: "jp-procyon-stakes", name: "Procyon Stakes", track: "Chukyo", grade: "G2", distance: 1800, surface: "Dirt", purse: 400000, dayOfYear: 15, restrictions: { minAge: 4 }, },
  { key: "jp-kyoto-kinen", name: "Kyoto Kinen", track: "Kyoto", grade: "G2", distance: 2200, surface: "Turf", purse: 400000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-nakayama-kinen", name: "Nakayama Kinen", track: "Nakayama", grade: "G2", distance: 1800, surface: "Turf", purse: 400000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-tulip-sho", name: "Tulip Sho", track: "Hanshin", grade: "G2", distance: 1600, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-yayoi-sho", name: "Yayoi Sho", track: "Nakayama", grade: "G2", distance: 2000, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-fillies-revue", name: "Fillies' Revue", track: "Hanshin", grade: "G2", distance: 1400, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-kinko-sho", name: "Kinko Sho", track: "Chukyo", grade: "G2", distance: 2000, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-spring-stakes", name: "Spring Stakes", track: "Nakayama", grade: "G2", distance: 1800, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-hanshin-daishoten", name: "Hanshin Daishoten", track: "Hanshin", grade: "G2", distance: 3000, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-nikkei-sho", name: "Nikkei Sho", track: "Nakayama", grade: "G2", distance: 2500, surface: "Turf", purse: 400000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-new-zealand-trophy", name: "New Zealand Trophy", track: "Nakayama", grade: "G2", distance: 1600, surface: "Turf", purse: 400000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-hanshin-himba-stakes", name: "Hanshin Himba Stakes", track: "Hanshin", grade: "G2", distance: 1600, surface: "Turf", purse: 400000, dayOfYear: 105, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-flora-stakes", name: "Flora Stakes", track: "Tokyo", grade: "G2", distance: 2000, surface: "Turf", purse: 400000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-yomiuri-milers-cup", name: "Yomiuri Milers Cup", track: "Kyoto", grade: "G2", distance: 1600, surface: "Turf", purse: 400000, dayOfYear: 105, restrictions: { minAge: 4 }, },
  { key: "jp-aoba-sho", name: "Aoba Sho", track: "Tokyo", grade: "G2", distance: 2400, surface: "Turf", purse: 400000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-kyoto-shimbun-hai", name: "Kyoto Shimbun Hai", track: "Kyoto", grade: "G2", distance: 2200, surface: "Turf", purse: 400000, dayOfYear: 135, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-keio-hai-spring-cup", name: "Keio Hai Spring Cup", track: "Tokyo", grade: "G2", distance: 1400, surface: "Turf", purse: 400000, dayOfYear: 135, restrictions: { minAge: 4 }, },
  { key: "jp-meguro-kinen", name: "Meguro Kinen", track: "Tokyo", grade: "G2", distance: 2500, surface: "Turf", purse: 400000, dayOfYear: 135, restrictions: { minAge: 4 }, },
  { key: "jp-sapporo-kinen", name: "Sapporo Kinen", track: "Sapporo", grade: "G2", distance: 2000, surface: "Turf", purse: 400000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-shion-stakes", name: "Shion Stakes", track: "Nakayama", grade: "G2", distance: 2000, surface: "Turf", purse: 400000, dayOfYear: 258, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-centaur-stakes", name: "Centaur Stakes", track: "Hanshin", grade: "G2", distance: 1200, surface: "Turf", purse: 400000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-rose-stakes", name: "Rose Stakes", track: "Hanshin", grade: "G2", distance: 1800, surface: "Turf", purse: 400000, dayOfYear: 258, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-st-lite-kinen", name: "St Lite Kinen", track: "Nakayama", grade: "G2", distance: 2200, surface: "Turf", purse: 400000, dayOfYear: 258, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-sankei-sho-all-comers", name: "Sankei Sho All Comers", track: "Nakayama", grade: "G2", distance: 2200, surface: "Turf", purse: 400000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-kobe-shimbun-hai", name: "Kobe Shimbun Hai", track: "Hanshin", grade: "G2", distance: 2400, surface: "Turf", purse: 400000, dayOfYear: 258, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-mainichi-okan", name: "Mainichi Okan", track: "Tokyo", grade: "G2", distance: 1800, surface: "Turf", purse: 400000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-kyoto-daishoten", name: "Kyoto Daishoten", track: "Kyoto", grade: "G2", distance: 2400, surface: "Turf", purse: 400000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-ireland-trophy", name: "Ireland Trophy", track: "Tokyo", grade: "G2", distance: 1800, surface: "Turf", purse: 400000, dayOfYear: 288, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-fuji-stakes", name: "Fuji Stakes", track: "Tokyo", grade: "G2", distance: 1600, surface: "Turf", purse: 400000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-swan-stakes", name: "Swan Stakes", track: "Kyoto", grade: "G2", distance: 1400, surface: "Turf", purse: 400000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-keio-hai-nisai-stakes", name: "Keio Hai Nisai Stakes", track: "Tokyo", grade: "G2", distance: 1400, surface: "Turf", purse: 400000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-copa-republica-argentina", name: "Copa Republica Argentina", track: "Tokyo", grade: "G2", distance: 2500, surface: "Turf", purse: 400000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-daily-hai-nisai-stakes", name: "Daily Hai Nisai Stakes", track: "Kyoto", grade: "G2", distance: 1600, surface: "Turf", purse: 400000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-tokyo-sports-hai-nisai-stakes", name: "Tokyo Sports Hai Nisai Stakes", track: "Tokyo", grade: "G2", distance: 1800, surface: "Turf", purse: 400000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-stayers-stakes", name: "Stayers Stakes", track: "Nakayama", grade: "G2", distance: 3600, surface: "Turf", purse: 400000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-hanshin-cup", name: "Hanshin Cup", track: "Hanshin", grade: "G2", distance: 1400, surface: "Turf", purse: 400000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-nakayama-kimpai", name: "Nakayama Kimpai", track: "Nakayama", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 15, restrictions: { minAge: 4 }, },
  { key: "jp-kyoto-kimpai", name: "Kyoto Kimpai", track: "Kyoto", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 15, restrictions: { minAge: 4 }, },
  { key: "jp-fairy-stakes", name: "Fairy Stakes", track: "Nakayama", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 15, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-shinzan-kinen", name: "Shinzan Kinen", track: "Kyoto", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 15, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-keisei-hai", name: "Keisei Hai", track: "Nakayama", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 15, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-kokura-himba-stakes", name: "Kokura Himba Stakes", track: "Kokura", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 15, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-negishi-stakes", name: "Negishi Stakes", track: "Tokyo", grade: "G3", distance: 1400, surface: "Dirt", purse: 250000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-silk-road-stakes", name: "Silk Road Stakes", track: "Kyoto", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-tokyo-shimbun-hai", name: "Tokyo Shimbun Hai", track: "Tokyo", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-kisaragi-sho", name: "Kisaragi Sho", track: "Kyoto", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-queen-cup", name: "Queen Cup", track: "Tokyo", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-tokinominoru-kinen", name: "Tokinominoru Kinen", track: "Tokyo", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-diamond-stakes", name: "Diamond Stakes", track: "Tokyo", grade: "G3", distance: 3400, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-kokura-daishoten", name: "Kokura Daishoten", track: "Kokura", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-hankyu-hai", name: "Hankyu Hai", track: "Hanshin", grade: "G3", distance: 1400, surface: "Turf", purse: 250000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-aichi-hai", name: "Aichi Hai", track: "Chukyo", grade: "G3", distance: 1400, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-ocean-stakes", name: "Ocean Stakes", track: "Nakayama", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-nakayama-himba-stakes", name: "Nakayama Himba Stakes", track: "Nakayama", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-flower-cup", name: "Flower Cup", track: "Nakayama", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-falcon-stakes", name: "Falcon Stakes", track: "Chukyo", grade: "G3", distance: 1400, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-mainichi-hai", name: "Mainichi Hai", track: "Hanshin", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-march-stakes", name: "March Stakes", track: "Nakayama", grade: "G3", distance: 1800, surface: "Dirt", purse: 250000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-lord-derby-challenge-trophy", name: "Lord Derby Challenge Trophy", track: "Nakayama", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-churchill-downs-cup", name: "Churchill Downs Cup", track: "Hanshin", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-antares-stakes", name: "Antares Stakes", track: "Hanshin", grade: "G3", distance: 1800, surface: "Dirt", purse: 250000, dayOfYear: 105, restrictions: { minAge: 4 }, },
  { key: "jp-fukushima-himba-stakes", name: "Fukushima Himba Stakes", track: "Fukushima", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 105, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-niigata-daishoten", name: "Niigata Daishoten", track: "Niigata", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 105, restrictions: { minAge: 4 }, },
  { key: "jp-unicorn-stakes", name: "Unicorn Stakes", track: "Kyoto", grade: "G3", distance: 1900, surface: "Dirt", purse: 250000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-heian-stakes", name: "Heian Stakes", track: "Kyoto", grade: "G3", distance: 1900, surface: "Dirt", purse: 250000, dayOfYear: 135, restrictions: { minAge: 4 }, },
  { key: "jp-aoi-stakes", name: "Aoi Stakes", track: "Kyoto", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 135, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-epsom-cup", name: "Epsom Cup", track: "Tokyo", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-fuchu-himba-stakes", name: "Fuchu Himba Stakes", track: "Tokyo", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-hakodate-sprint-stakes", name: "Hakodate Sprint Stakes", track: "Hakodate", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-radio-nikkei-sho", name: "Radio Nikkei Sho", track: "Fukushima", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-kitakyushu-kinen", name: "Kitakyushu Kinen", track: "Kokura", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-shirasagi-stakes", name: "Shirasagi Stakes", track: "Hanshin", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-tanabata-sho", name: "Tanabata Sho", track: "Fukushima", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 196, restrictions: { minAge: 3 }, },
  { key: "jp-tokai-stakes", name: "Tokai Stakes", track: "Chukyo", grade: "G3", distance: 1400, surface: "Dirt", purse: 250000, dayOfYear: 196, restrictions: { minAge: 3 }, },
  { key: "jp-hakodate-kinen", name: "Hakodate Kinen", track: "Hakodate", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 196, restrictions: { minAge: 3 }, },
  { key: "jp-chukyo-kinen", name: "Chukyo Kinen", track: "Chukyo", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 196, restrictions: { minAge: 3 }, },
  { key: "jp-hakodate-nisai-stakes", name: "Hakodate Nisai Stakes", track: "Hakodate", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 196, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-ibis-summer-dash", name: "Ibis Summer Dash", track: "Niigata", grade: "G3", distance: 1000, surface: "Turf", purse: 250000, dayOfYear: 196, restrictions: { minAge: 3 }, },
  { key: "jp-queen-stakes", name: "Queen Stakes", track: "Sapporo", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 196, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-leopard-stakes", name: "Leopard Stakes", track: "Niigata", grade: "G3", distance: 1800, surface: "Dirt", purse: 250000, dayOfYear: 227, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-kokura-kinen", name: "Kokura Kinen", track: "Kokura", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-sekiya-kinen", name: "Sekiya Kinen", track: "Niigata", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-cbc-sho", name: "CBC Sho", track: "Chukyo", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-elm-stakes", name: "Elm Stakes", track: "Sapporo", grade: "G3", distance: 1700, surface: "Dirt", purse: 250000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-niigata-nisai-stakes", name: "Niigata Nisai Stakes", track: "Niigata", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-keeneland-cup", name: "Keeneland Cup", track: "Sapporo", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-sapporo-nisai-stakes", name: "Sapporo Nisai Stakes", track: "Sapporo", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-chukyo-nisai-stakes", name: "Chukyo Nisai Stakes", track: "Chukyo", grade: "G3", distance: 1400, surface: "Turf", purse: 250000, dayOfYear: 227, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-niigata-kinen", name: "Niigata Kinen", track: "Niigata", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-keisei-hai-autumn-handicap", name: "Keisei Hai Autumn Handicap", track: "Nakayama", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-challenge-cup", name: "Challenge Cup", track: "Hanshin", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-sirius-stakes", name: "Sirius Stakes", track: "Hanshin", grade: "G3", distance: 2000, surface: "Dirt", purse: 250000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-saudi-arabia-royal-cup", name: "Saudi Arabia Royal Cup", track: "Tokyo", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 288, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-artemis-stakes", name: "Artemis Stakes", track: "Tokyo", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 288, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies", },
  { key: "jp-fantasy-stakes", name: "Fantasy Stakes", track: "Kyoto", grade: "G3", distance: 1400, surface: "Turf", purse: 250000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies", },
  { key: "jp-miyako-stakes", name: "Miyako Stakes", track: "Kyoto", grade: "G3", distance: 1800, surface: "Dirt", purse: 250000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-musashino-stakes", name: "Musashino Stakes", track: "Tokyo", grade: "G3", distance: 1600, surface: "Dirt", purse: 250000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-fukushima-kinen", name: "Fukushima Kinen", track: "Fukushima", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-kyoto-nisai-stakes", name: "Kyoto Nisai Stakes", track: "Kyoto", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-keihan-hai", name: "Keihan Hai", track: "Kyoto", grade: "G3", distance: 1200, surface: "Turf", purse: 250000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-naruo-kinen", name: "Naruo Kinen", track: "Hanshin", grade: "G3", distance: 1800, surface: "Turf", purse: 250000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-chunichi-shimbun-hai", name: "Chunichi Shimbun Hai", track: "Chukyo", grade: "G3", distance: 2000, surface: "Turf", purse: 250000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-capella-stakes", name: "Capella Stakes", track: "Nakayama", grade: "G3", distance: 1200, surface: "Dirt", purse: 250000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-turquoise-stakes", name: "Turquoise Stakes", track: "Nakayama", grade: "G3", distance: 1600, surface: "Turf", purse: 250000, dayOfYear: 349, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-tokyo-daishoten", name: "Tokyo Daishōten", track: "Ohi", grade: "G1", distance: 2000, surface: "Turf", purse: 800000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-kawasaki-kinen", name: "Kawasaki Kinen", track: "Kawasaki", grade: "G1", distance: 2100, surface: "Turf", purse: 500000, dayOfYear: 105, restrictions: { minAge: 4 }, },
  { key: "jp-haneda-hai", name: "Haneda Hai", track: "Ohi", grade: "G1", distance: 1800, surface: "Turf", purse: 500000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-kashiwa-kinen", name: "Kashiwa Kinen", track: "Funabashi", grade: "G1", distance: 1600, surface: "Turf", purse: 500000, dayOfYear: 135, restrictions: { minAge: 4 }, },
  { key: "jp-tokyo-derby", name: "Tokyo Derby", track: "Ohi", grade: "G1", distance: 2000, surface: "Turf", purse: 500000, dayOfYear: 166, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-sakitama-hai", name: "Sakitama Hai", track: "Urawa", grade: "G1", distance: 1400, surface: "Turf", purse: 500000, dayOfYear: 166, restrictions: { minAge: 3 }, },
  { key: "jp-teio-sho", name: "Teio Sho", track: "Ohi", grade: "G1", distance: 2000, surface: "Turf", purse: 500000, dayOfYear: 166, restrictions: { minAge: 4 }, },
  { key: "jp-japan-dirt-classic", name: "Japan Dirt Classic", track: "Ohi", grade: "G1", distance: 2000, surface: "Turf", purse: 500000, dayOfYear: 288, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-mile-championship-nambu-hai", name: "Mile Championship Nambu Hai", track: "Morioka", grade: "G1", distance: 1600, surface: "Turf", purse: 500000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-japan-breeding-farm-s-cup-ladies-classic", name: "Japan Breeding Farm's Cup Ladies' Classic", track: "Various", grade: "G1", distance: 1800, surface: "Turf", purse: 500000, dayOfYear: 319, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-japan-breeding-farms-cup-sprint", name: "Japan Breeding Farms' Cup Sprint", track: "Various", grade: "G1", distance: 1200, surface: "Turf", purse: 500000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-japan-breeding-farms-cup-classic", name: "Japan Breeding Farms' Cup Classic", track: "Various", grade: "G1", distance: 2000, surface: "Turf", purse: 500000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-zen-nippon-nisai-yushun", name: "Zen-Nippon Nisai Yushun", track: "Kawasaki", grade: "G1", distance: 1600, surface: "Turf", purse: 500000, dayOfYear: 349, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-diolite-kinen", name: "Diolite Kinen", track: "Funabashi", grade: "G2", distance: 2400, surface: "Turf", purse: 300000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-keihin-hai", name: "Keihin Hai", track: "Ohi", grade: "G2", distance: 1700, surface: "Turf", purse: 300000, dayOfYear: 74, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-hyogo-championship", name: "Hyogo Championship", track: "Sonoda", grade: "G2", distance: 1400, surface: "Turf", purse: 300000, dayOfYear: 105, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-nagoya-grand-prix", name: "Nagoya Grand Prix", track: "Nagoya", grade: "G2", distance: 2100, surface: "Turf", purse: 300000, dayOfYear: 135, restrictions: { minAge: 4 }, },
  { key: "jp-empress-hai", name: "Empress Hai", track: "Kawasaki", grade: "G2", distance: 2100, surface: "Turf", purse: 300000, dayOfYear: 135, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-kanto-oaks", name: "Kanto Oaks", track: "Kawasaki", grade: "G2", distance: 2100, surface: "Turf", purse: 300000, dayOfYear: 166, restrictions: { minAge: 3, maxAge: 3 }, note: "Fillies", },
  { key: "jp-furukata-award", name: "Furukata Award", track: "Morioka", grade: "G2", distance: 2000, surface: "Turf", purse: 300000, dayOfYear: 258, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-nippon-tv-hai", name: "Nippon TV Hai", track: "Funabashi", grade: "G2", distance: 1800, surface: "Turf", purse: 300000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-ladies-prelude", name: "Ladies' Prelude", track: "Ohi", grade: "G2", distance: 1800, surface: "Turf", purse: 300000, dayOfYear: 288, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-tokyo-hai", name: "Tokyo Hai", track: "Ohi", grade: "G2", distance: 1200, surface: "Turf", purse: 300000, dayOfYear: 288, restrictions: { minAge: 3 }, },
  { key: "jp-urawa-kinen", name: "Urawa Kinen", track: "Urawa Kinen", grade: "G2", distance: 2000, surface: "Turf", purse: 300000, dayOfYear: 319, restrictions: { minAge: 3 }, },
  { key: "jp-hyogo-junior-grand-prix", name: "Hyogo Junior Grand Prix", track: "Sonoda", grade: "G2", distance: 1400, surface: "Turf", purse: 300000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-bluebird-cup", name: "Bluebird Cup", track: "Funabashi", grade: "G3", distance: 1800, surface: "Turf", purse: 200000, dayOfYear: 15, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-queen-sho", name: "Queen Sho", track: "Funabashi", grade: "G3", distance: 1800, surface: "Turf", purse: 200000, dayOfYear: 46, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-saga-kinen", name: "Saga Kinen", track: "Saga", grade: "G3", distance: 2000, surface: "Turf", purse: 200000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-kumotori-sho", name: "Kumotori Sho", track: "Oi", grade: "G3", distance: 1800, surface: "Turf", purse: 200000, dayOfYear: 46, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-iris-kinen", name: "Iris Kinen", track: "Nagoya", grade: "G3", distance: 1500, surface: "Turf", purse: 200000, dayOfYear: 46, restrictions: { minAge: 4 }, },
  { key: "jp-kurofune-sho", name: "Kurofune Sho", track: "Kochi", grade: "G3", distance: 1400, surface: "Turf", purse: 200000, dayOfYear: 74, restrictions: { minAge: 4 }, },
  { key: "jp-hyogo-queen-cup", name: "Hyogo Queen Cup", track: "Sonoda", grade: "G3", distance: 1870, surface: "Turf", purse: 200000, dayOfYear: 105, restrictions: { minAge: 4 }, note: "Fillies", },
  { key: "jp-tokyo-sprint", name: "Tokyo Sprint", track: "Oi", grade: "G3", distance: 1200, surface: "Turf", purse: 200000, dayOfYear: 105, restrictions: { minAge: 4 }, },
  { key: "jp-sparking-lady-cup", name: "Sparking Lady Cup", track: "Kawasaki", grade: "G3", distance: 1600, surface: "Turf", purse: 200000, dayOfYear: 196, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-mercury-cup", name: "Mercury Cup", track: "Morioka", grade: "G3", distance: 2000, surface: "Turf", purse: 200000, dayOfYear: 196, restrictions: { minAge: 3 }, },
  { key: "jp-cluster-cup", name: "Cluster Cup", track: "Morioka", grade: "G3", distance: 1200, surface: "Turf", purse: 200000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-hokkaido-sprint-cup", name: "Hokkaido Sprint Cup", track: "Monbetsu", grade: "G3", distance: 1200, surface: "Turf", purse: 200000, dayOfYear: 227, restrictions: { minAge: 3, maxAge: 3 }, },
  { key: "jp-breeders-gold-cup", name: "Breeders' Gold Cup", track: "Monbetsu", grade: "G3", distance: 2000, surface: "Turf", purse: 200000, dayOfYear: 227, restrictions: { minAge: 3 }, note: "Fillies", },
  { key: "jp-summer-champion", name: "Summer Champion", track: "Saga", grade: "G3", distance: 1400, surface: "Turf", purse: 200000, dayOfYear: 227, restrictions: { minAge: 3 }, },
  { key: "jp-oval-sprint", name: "Oval Sprint", track: "Urawa", grade: "G3", distance: 1400, surface: "Turf", purse: 200000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-hakusan-daishoten", name: "Hakusan Daishoten", track: "Kanazawa", grade: "G3", distance: 2100, surface: "Turf", purse: 200000, dayOfYear: 258, restrictions: { minAge: 3 }, },
  { key: "jp-edelweiss-sho", name: "Edelweiss Sho", track: "Monbetsu", grade: "G3", distance: 1200, surface: "Turf", purse: 200000, dayOfYear: 288, restrictions: { minAge: 2, maxAge: 2 }, note: "Fillies", },
  { key: "jp-jbc-two-year-old-championship", name: "JBC Two-Year-Old Championship", track: "Monbetsu", grade: "G3", distance: 1800, surface: "Turf", purse: 200000, dayOfYear: 319, restrictions: { minAge: 2, maxAge: 2 }, },
  { key: "jp-nagoya-daishoten", name: "Nagoya Daishoten", track: "Nagoya", grade: "G3", distance: 2000, surface: "Turf", purse: 200000, dayOfYear: 349, restrictions: { minAge: 3 }, },
  { key: "jp-hyogo-gold-trophy", name: "Hyogo Gold Trophy", track: "Sonoda", grade: "G3", distance: 1400, surface: "Turf", purse: 200000, dayOfYear: 349, restrictions: { minAge: 3 }, },
];
