// Intent Collection Phase
// Collects player intents from the pending queue and generates NPC intents via AI systems

import type { PipelineContext, PipelinePhase } from "../pipeline";
import type { AnyIntent } from "@/core/resolver/intents";

/**
 * Intent Collection Phase (Order 5)
 * Collects all intents for the day:
 * - Player intents from pendingIntents queue
 * - NPC intents generated by AI systems
 * - System intents (upkeep, aging, etc.)
 */
export const intentCollectionPhase: PipelinePhase = {
  name: "intentCollection",
  order: 5,
  execute: (context: PipelineContext): PipelineContext => {
    const { state, newDay, dailyRng } = context;
    const intents: AnyIntent[] = [];

    // 1. Collect player intents from pending queue
    if (state.pendingIntents) {
      intents.push(...state.pendingIntents);
    }

    // 2. Generate NPC intents
    // This will be implemented in Phase 2 when we create NPC intent generators
    // For now, we'll leave this empty as a placeholder

    // 3. Generate system intents (upkeep, aging, etc.)
    // These will be generated by existing phases, so we don't need to add them here yet

    return {
      ...context,
      intents,
    };
  },
};
