export const INITIALIZATION_BUDGET_TIER_THRESHOLD = 0.6;
export const INITIALIZATION_HORSE_COUNT_THRESHOLD = 0.7;

export const AI_RISK_TOLERANCE_CONSERVATIVE = 35;
export const AI_RISK_TOLERANCE_AGGRESSIVE = 65;
export const AI_RISK_TOLERANCE_WIN_NOW = 55;

export const AI_QUALITY_ELITE_THRESHOLD = 75;
export const AI_QUALITY_MID_THRESHOLD = 65;

export const AI_STRATEGIC_HORIZON_DAYS = 90;

export const NPC_HORSE_COUNT_ELITE_MIN = 30;
export const NPC_HORSE_COUNT_ELITE_MAX = 40;
export const NPC_HORSE_COUNT_MID_MIN = 20;
export const NPC_HORSE_COUNT_MID_MAX = 30;
export const NPC_HORSE_COUNT_BUDGET_MIN = 15;
export const NPC_HORSE_COUNT_BUDGET_MAX = 25;

export const DEFAULT_SUBSYSTEM_WEIGHT = 1.0;

export const CONSIGN_UNDERPERFORMER_RATING_THRESHOLD = 40;

export const CONSIGN_UNDERPERFORMER_AGE_THRESHOLD = 5;

export const CONSIGN_RATING_RELAXATION_PER_WEIGHT = 20;

export const CONSIGN_AGE_RELAXATION_PER_WEIGHT = 2;

export const BID_BASE_THRESHOLD = 50;

export const HORSE_RATING_TO_VALUE_MULTIPLIER = 1000;

export const PURCHASE_BASE_THRESHOLD = 50;

export const PURCHASE_CASH_BUFFER_MULTIPLIER = 1.1;

export const FACILITY_UPGRADE_BASE_THRESHOLD = 50;

export const CONSIGNMENT_INTENT_PRIORITY = 40;
