export const AUCTION_AGGRESSIVE_PREMIUM = 0.3;
export const AUCTION_2YO_TRAINING_PREMIUM = 0.25;
export const AUCTION_CONSERVATIVE_DISCOUNT = 0.25;
export const AUCTION_YEARLING_PREMIUM = 0.4;
export const AUCTION_WEANLING_PREMIUM = 0.2;
export const AUCTION_RACING_AGE_DISCOUNT = 0.3;
export const AUCTION_WEANLING_DISCOUNT = 0.4;
export const AUCTION_BROODMARE_DISCOUNT = 0.6;
export const AUCTION_FILLY_PREMIUM = 0.6;
export const AUCTION_BROODMARE_PREMIUM = 0.5;
export const AUCTION_RACING_AGE_PREMIUM = 0.3;

export const AUCTION_RESERVE_SPECIALIST = 0.75;
export const AUCTION_RESERVE_AGGRESSIVE = 0.35;
export const AUCTION_RESERVE_SPECIALIST_LOW = 0.25;
export const AUCTION_RESERVE_BREEDER = 0.35;
export const AUCTION_RESERVE_CONSERVATIVE = 0.55;
export const AUCTION_RESERVE_ELITE = 0.85;

export const AUCTION_AGGRESSIVE_BID_MIN_PERCENT = 0.88;
export const AUCTION_AGGRESSIVE_BID_VARIANCE = 0.07;

export const DEFAULT_PLAYER_RESERVE_RATIO = 0.7;
