export const DASHBOARD_UPCOMING_RACES_LIMIT = 8;

export const DASHBOARD_URGENT_MESSAGES_LIMIT = 3;

export const DASHBOARD_TOP_RIVALS_LIMIT = 3;

export const DASHBOARD_RIVAL_FRICTION_THRESHOLD = 40;

export const HEAD_TO_HEAD_LOOKBACK_DAYS = 30;

export const DASHBOARD_NEWS_FEED_LIMIT = 15;

export const DASHBOARD_SEASON_STANDINGS_LIMIT = 10;

export const SHARE_ACTIVITY_FEED_LIMIT = 50;

export const NOMINATIONS_UPCOMING_LIMIT = 60;

export const WEATHER_FORECAST_STRIP_DAYS = 7;

export const BEYER_CHART_HISTORY_LIMIT = 10;

export const STANDINGS_RANGE_SHORT_DAYS = 7;
export const STANDINGS_RANGE_MEDIUM_DAYS = 30;
export const STANDINGS_RANGE_LONG_DAYS = 90;
export const STANDINGS_DEFAULT_RANGE_DAYS = 30;
export const STANDINGS_SKELETON_ROW_COUNT = 5;
export const STANDINGS_RECENT_RESULTS_LIMIT = 5;
