export const ENERGY_LOW_THRESHOLD = 40;
export const ENERGY_MODERATE_THRESHOLD = 50;
export const ENERGY_HIGH_THRESHOLD = 60;

export const RECOVERY_EXHAUSTED_THRESHOLD = 30;
export const RECOVERY_FATIGUED_THRESHOLD = 50;
export const RECOVERY_FRESH_THRESHOLD = 80;
export const RECOVERY_PEAKING_THRESHOLD = 80;

export const DEFAULT_RECOVERY_POINTS = 100;

export const MAX_RECOVERY_POINTS = 100;

export const BOUNCE_RISK_BEYER_MARGIN = 15;
export const BOUNCE_RISK_DAYS_THRESHOLD = 28;

export const ENERGY_MAX = 100;
