export {
  FACILITY_BONUSES,
  FACILITY_MAINTENANCE_COSTS,
  FACILITY_UPGRADE_COSTS,
  FACILITY_NAMES,
  FACILITY_DESCRIPTIONS,
  FACILITY_ENABLED_WORKOUTS,
  FACILITY_TIER_LABELS,
} from "@/core/facilities/facilityTypes";
