export const INJURY_RECOVERY_MIN = 60;
export const INJURY_RECOVERY_MAX = 180;

export const INJURY_SEVERITY_CAREER_ENDING_THRESHOLD = 0.98;
export const INJURY_SEVERITY_MAJOR_THRESHOLD = 0.85;
export const INJURY_SEVERITY_MODERATE_THRESHOLD = 0.6;

export const INJURY_RECOVERY_CAREER_ENDING = 999;
export const INJURY_RECOVERY_MAJOR_MIN = 60;
export const INJURY_RECOVERY_MAJOR_MAX = 180;
export const INJURY_RECOVERY_MODERATE_MIN = 14;
export const INJURY_RECOVERY_MODERATE_MAX = 42;
export const INJURY_RECOVERY_MINOR = 7;

export const EVENT_INJURY_MULTIPLIER_RACE = 2.0;
export const EVENT_INJURY_MULTIPLIER_TRAINING = 1.2;
export const FATIGUE_INJURY_THRESHOLD = 50;
export const FATIGUE_INJURY_DIVISOR = 100;
export const ENERGY_INJURY_MULTIPLIER = 1.5;

export const INJURY_SEVERITY_THRESHOLD = 0.85;

export const INJURY_PRONENESS_LOW_THRESHOLD = 0.04;
export const INJURY_PRONENESS_HIGH_THRESHOLD = 0.08;
