import {
  MILESTONE_FINAL_400M,
  MILESTONE_FINAL_200M,
  MILESTONE_FINAL_100M,
  MIN_DISTANCE_FOR_FINAL_400,
  MIN_DISTANCE_FOR_FINAL_200,
  MIN_DISTANCE_FOR_FINAL_100,
  GAP_THRESHOLD_LENGTHS,
  STRETCH_THRESHOLD_PERCENT,
  TURN_SEGMENT_LENGTH,
  METERS_PER_LENGTH,
} from "@/constants/raceSimulationConstants";

export const NARRATIVE_THRESHOLDS = {
  METERS_PER_LENGTH,
  MILESTONE_FINAL_400M,
  MILESTONE_FINAL_200M,
  MILESTONE_FINAL_100M,
  MIN_DISTANCE_FOR_FINAL_400,
  MIN_DISTANCE_FOR_FINAL_200,
  MIN_DISTANCE_FOR_FINAL_100,
  // Event detection thresholds
  ATMOSPHERE_PROBABILITY: 0.005,
  ATMOSPHERE_COOLDOWN: 45,
  GAP_THRESHOLD_LENGTHS,
  GAP_COOLDOWN: 25,
  STABLE_WATCH_START_TIME: 2,
  STABLE_WATCH_END_TIME: 15,
  STABLE_WATCH_COOLDOWN: 60,
  LEAD_CHANGE_THRESHOLD: 20,
  LEAD_CHANGE_COOLDOWN: 15,
  STRETCH_THRESHOLD: STRETCH_THRESHOLD_PERCENT,
  SURGE_RANK_DIFF: 2,
  SURGE_TOP3_RANK_DIFF: 3,
  FADE_RANK_DIFF: 3,
  SURGE_FADE_COOLDOWN: 20,
  DRAFTING_COOLDOWN: 40,
  LANE_THRESHOLD: 3.6,
  LANE_WATCH_COOLDOWN: 45,
  // Turn position thresholds
  TURN_SEGMENT_LENGTH,
  TURN_SEGMENT_START: 400,
  TURN_SEGMENT_END: 800,
  TURN_SEGMENT_FINAL_START: 1200,
  // Milestone positions
  HALFWAY_POSITION: 0.5,
  // Hot pace detection
  HOT_PACE_THRESHOLD: 1.1,
  HOT_PACE_MAX_PROGRESS: 0.6,
  HOT_PACE_COOLDOWN: 30,
  // Atmosphere minimum sim time before atmosphere events can fire
  ATMOSPHERE_MIN_TIME: 5,
  // Default cooldown
  DEFAULT_COOLDOWN: 10,
  // Commentary generator probabilities
  PREFIX_PROBABILITY: 0.2,
  BIO_TEMPLATE_PROBABILITY: 0.35,
  // Expert insight thresholds
  EXPERT_INSIGHT_POSITIVE_FORM: 5,
  EXPERT_INSIGHT_NEGATIVE_FORM: -5,
  EXPERT_INSIGHT_DISTANCE_FIT_TOLERANCE: 200,
  EXPERT_INSIGHT_NEW_DISTANCE_MIN: 1600,
  EXPERT_INSIGHT_SURFACE_APTITUDE: 85,
  // Condition commentary cooldowns (seconds)
  CONDITION_FLYING_COOLDOWN: 30,
  CONDITION_BATTLING_COOLDOWN: 25,
  CONDITION_BOXED_IN_COOLDOWN: 30,
  CONDITION_GRINDING_COOLDOWN: 35,
  CONDITION_FLAGGING_COOLDOWN: 25,
  CONDITION_IN_TROUBLE_COOLDOWN: 20,
  CONDITION_AILING_COOLDOWN: 60,
  CONDITION_SETTLED_COOLDOWN: 40,
  // Jockey commentary cooldowns (seconds)
  JOCKEY_EVENT_COOLDOWN: 35,
  JOCKEY_MASTERY_COOLDOWN: 50,
  JOCKEY_APPRENTICE_COOLDOWN: 50,
  // Ongoing insight cooldowns (seconds)
  MIDRACE_INSIGHT_COOLDOWN: 40,
  CLOSING_INSIGHT_COOLDOWN: 40,
  PACE_ANALYSIS_COOLDOWN: 40,
  // Chaining callback cooldown (seconds)
  CALLBACK_COOLDOWN: 25,
  // Dynamic generation probabilities
  COMPOSABLE_PROBABILITY: 0.30,
  PROCEDURAL_PROBABILITY: 0.15,
  HYBRID_INJECTION_PROBABILITY: 0.10,
  CALLBACK_INJECTION_PROBABILITY: 0.20,
} as const;
