import {
  MILESTONE_FINAL_400M,
  MILESTONE_FINAL_200M,
  MILESTONE_FINAL_100M,
  MIN_DISTANCE_FOR_FINAL_400,
  MIN_DISTANCE_FOR_FINAL_200,
  MIN_DISTANCE_FOR_FINAL_100,
  GAP_THRESHOLD_LENGTHS,
  STRETCH_THRESHOLD_PERCENT,
  TURN_SEGMENT_LENGTH,
  METERS_PER_LENGTH,
} from "@/constants";

export const NARRATIVE_THRESHOLDS = {
  METERS_PER_LENGTH,
  MILESTONE_FINAL_400M,
  MILESTONE_FINAL_200M,
  MILESTONE_FINAL_100M,
  MIN_DISTANCE_FOR_FINAL_400,
  MIN_DISTANCE_FOR_FINAL_200,
  MIN_DISTANCE_FOR_FINAL_100,
  // Event detection thresholds
  ATMOSPHERE_PROBABILITY: 0.005,
  ATMOSPHERE_COOLDOWN: 45,
  GAP_THRESHOLD_LENGTHS,
  GAP_COOLDOWN: 25,
  STABLE_WATCH_START_TIME: 2,
  STABLE_WATCH_END_TIME: 15,
  STABLE_WATCH_COOLDOWN: 60,
  LEAD_CHANGE_THRESHOLD: 20,
  LEAD_CHANGE_COOLDOWN: 15,
  STRETCH_THRESHOLD: STRETCH_THRESHOLD_PERCENT,
  SURGE_RANK_DIFF: 2,
  SURGE_TOP3_RANK_DIFF: 3,
  FADE_RANK_DIFF: 3,
  SURGE_FADE_COOLDOWN: 20,
  DRAFTING_COOLDOWN: 40,
  LANE_THRESHOLD: 3.6,
  LANE_WATCH_COOLDOWN: 45,
  // Turn position thresholds
  TURN_SEGMENT_LENGTH,
  TURN_SEGMENT_START: 400,
  TURN_SEGMENT_END: 800,
  TURN_SEGMENT_FINAL_START: 1200,
  // Milestone positions
  HALFWAY_POSITION: 0.5,
  // Hot pace detection
  HOT_PACE_THRESHOLD: 1.1,
  HOT_PACE_MAX_PROGRESS: 0.6,
  HOT_PACE_COOLDOWN: 30,
  // Default cooldown
  DEFAULT_COOLDOWN: 10,
} as const;
