export const NEWS_HIGH_IMPORTANCE_PRICE_THRESHOLD = 500000;

export const NEWS_LONG_DISTANCE_THRESHOLD = 2400;

export const NEWS_SPRINT_DISTANCE_THRESHOLD = 1200;

export const NEWS_DOMINANT_MARGIN_SECONDS = 1.5;

export const NEWS_FLAVOR_DAILY_PROBABILITY = 0.1;
