/**
 * expertInsightTemplates.ts - Expert insight commentary templates
 *
 * Extracted from templates.ts for modularity.
 */

export const EXPERT_INSIGHT_TEMPLATES = {
  POSITIVE_FORM: [
    "{horse} has been in sparkling form lately, looking to continue that today.",
    "Expect a big run from {horse} given their recent track record.",
    "Condition looks peak for {horse} as they load into the gates.",
    "The stable is buzzing about {horse}'s chances today.",
    "{horse} looks primed for a massive effort today based on morning work.",
    "{horse} comes into this race in absolute peak condition.",
    "You can't ignore the recent numbers {horse} has been putting up.",
    "Riding a wave of good form, {horse} is definitely a major threat.",
    "{horse} seems to be getting better with every start this campaign.",
    "It's hard to look past {horse} when they're running this well.",
    "The confidence behind {horse} is completely justified by their recent outings.",
    "{horse} is a picture of health and form heading into this contest.",
    "Everything points to a massive run from {horse} considering their current form.",
    "{horse} has hit a sweet spot in their campaign and looks very dangerous.",
    "You couldn't ask for {horse} to look any better than they do today.",
    "The momentum is entirely with {horse} right now.",
    "{horse} is flying at home and that form should translate perfectly today.",
    "If {horse} runs to their recent form, they are going to be very hard to beat.",
    "There are no concerns over {horse}'s current well-being, they look sensational.",
    "This is a horse at the absolute top of their game. Watch out for {horse}.",
  ],
  NEGATIVE_FORM: [
    "{horse} has struggled to find their best stride in recent starts.",
    "Looking for a bounce-back performance today from {horse}.",
    "Questions about the current fitness of {horse} after that last outing.",
    "This field might be a bit too deep for {horse} today.",
    "{horse} needs to show us a lot more after a string of disappointing efforts.",
    "The form line for {horse} has been a concern for the connections lately.",
    "It's been a tough campaign so far for {horse} as they try to find some rhythm.",
    "{horse} really needs to turn things around quickly with a good showing here.",
    "Confidence might be a bit low for {horse} coming into this one.",
    "We haven't seen the best of {horse} lately; they need to wake up today.",
    "{horse} looks to be struggling to recapture their earlier promise.",
    "It's hard to make a strong case for {horse} based on their recent starts.",
    "{horse} needs a sharp turnaround in form to feature today.",
    "We are hoping the real {horse} stands up today, because recent efforts have been poor.",
    "The current form of {horse} leaves a lot to be desired.",
    "{horse} is battling some form demons at the moment.",
    "It takes a leap of faith to back {horse} on current form.",
    "Connections of {horse} will be desperately hoping for a better showing this time.",
    "{horse} has been out of sorts lately and has plenty to prove.",
    "The jury is very much out on {horse} following some subpar recent runs.",
  ],
  DISTANCE_FIT: [
    "This {distance}m trip is right in the wheelhouse for {horse}.",
    "{horse} is a specialist at this distance.",
    "The distance shouldn't be an issue for {horse} today.",
    "Historically, {horse} excels at exactly this trip.",
    "{horse} will love every inch of this {distance}m journey.",
    "This {distance}m trip is where {horse} does their best work.",
    "A proven performer at {distance}m, {horse} is exactly where they want to be.",
    "{horse} has shown they can handle this {distance}m test with ease.",
    "The distance is perfect for {horse}'s natural running style.",
    "{horse} is uniquely suited to the demands of a {distance}m race.",
    "This trip is tailor-made for {horse}, giving them a distinct advantage.",
    "We know {horse} relishes a {distance}m challenge, so expect a bold showing.",
    "Over {distance}m, {horse} rarely puts a foot wrong.",
    "The {distance}m test is where {horse} finds their absolute best.",
    "{horse} is in their element over {distance}m.",
    "This field is on notice: {distance}m is {horse}'s preferred battleground.",
    "You know exactly what you'll get from {horse} at {distance}m.",
    "The statistics speak for themselves for {horse} over {distance}m.",
    "{horse} should relish every part of this {distance}m assignment.",
    "Over this specific trip of {distance}m, {horse} commands total respect.",
  ],
  SURFACE_FIT: [
    "This {surface} surface is exactly what {horse} has been looking for.",
    "{horse} is a known specialist when it comes to racing on {surface}.",
    "We know {horse} loves the {surface}, so expect a huge run today.",
    "The {surface} ground underfoot is a massive advantage for {horse}.",
    "Historically, {horse} has always produced top performances on {surface}.",
    "Given {horse}'s affinity for {surface}, they are a major threat today.",
    "{horse} will be absolutely relishing the chance to run on {surface}.",
    "You can never discount {horse} when they get their preferred {surface} conditions.",
    "This {surface} track is tailor-made for {horse}'s running style.",
    "Connections will be thrilled to have {horse} back on their favored {surface}.",
    "{horse} has proven time and again that {surface} is where they shine.",
    "Look out for {horse}, who is a completely different animal on {surface}.",
    "The return to {surface} could be the key to unlocking {horse}'s best form today.",
    "{horse} moves with so much more fluency on {surface}, they are a serious contender here.",
    "There's no questioning {horse}'s superiority when they step onto {surface}.",
    "Back on {surface}, expect {horse} to dictate terms from the start.",
    "{horse}'s record on {surface} speaks for itself; they are the one to beat.",
    "The transition back to {surface} gives {horse} a distinct edge over this field.",
    "Don't overlook {horse} today; the {surface} footing plays right into their hands.",
    "With conditions to suit, {surface} brings out the absolute best in {horse}.",
  ],
  NEW_DISTANCE: [
    "First time at {distance}m for {horse}, a real test of stamina.",
    "Testing the waters at this trip today with {horse}.",
    "Will {horse} see out the full {distance}m? We're about to find out.",
    "A major question mark over {horse} stepping up to this distance.",
    "Stepping into unknown territory today over {distance}m for {horse}.",
    "The big question is whether {horse} has the tank for this {distance}m.",
    "It's an ambitious ask to run {distance}m for the very first time, but {horse} tries today.",
    "Can {horse} handle the transition to {distance}m? The pedigree suggests maybe.",
    "We're going to learn a lot about {horse}'s versatility at this new {distance}m trip.",
    "Uncharted waters for {horse} at {distance}m, they'll need every ounce of grit.",
    "{horse} steps into the great unknown trying {distance}m for the first time.",
    "It's a gamble running {horse} at {distance}m today, let's see if it pays off.",
    "A fascinating move by connections to try {horse} over {distance}m today.",
    "We are in wait-and-see mode with {horse} at this new {distance}m trip.",
    "If {horse} can stretch out to {distance}m, they become a very interesting proposition.",
    "The big unknown today is whether {horse} stays the {distance}m.",
    "Tackling {distance}m for the first time is no easy feat, but {horse} looks ready.",
    "Can the speed of {horse} carry them over the full {distance}m?",
    "A real roll of the dice stepping {horse} out to {distance}m.",
    "The pedigree points to {horse} handling {distance}m, but today is the acid test.",
  ],
};
