export const DEFENDING_CHAMPION_TEMPLATES: string[] = [
  "{horse} won this race last year — can they repeat the dose?",
  "The defending champion {horse} is back to defend their crown in the {raceName}.",
  "{horse} took this race last year — the pressure is on to go back-to-back.",
  "Champion {horse} returns to the scene of last year's triumph.",
  "Can {horse} do it again? They won the {raceName} last year.",
  "{horse} is the defending titleholder — {year} was their year in this race.",
  "Last year's winner {horse} faces the challenge again today.",
  "The {year} champion {horse} is back — can they retain their title?",
  "{horse} knows what it takes to win this race — they proved it last year.",
  "A familiar face at the top — {horse} won this race in {year}.",
  "The defending champ {horse} looks to make it two in a row.",
  "{horse} is back to defend their title — they conquered this race last year.",
  "History beckons for {horse} — a win today makes them a back-to-back champion.",
  "The crowd remembers {horse}'s victory last year — can they deliver an encore?",
];

export const TRACK_RECORD_TEMPLATES: string[] = [
  "The track record here is {recordTime}s — {horse} is on pace to challenge it!",
  "{horse} is flying! The track record of {recordTime}s set by {recordHolder} is under threat.",
  "If {horse} keeps this pace, they could break {recordHolder}'s track record of {recordTime}s!",
  "The record of {recordTime}s by {recordHolder} is in jeopardy — {horse} is on a record pace!",
  "Watch out {recordHolder} — {horse} is threatening your track record of {recordTime}s!",
  "{horse} is on track record pace! The mark to beat is {recordTime}s.",
  "Could we see a track record today? {horse} is pacing to challenge {recordTime}s.",
  "The track record of {recordTime}s looms large — {horse} is right on schedule.",
  "{recordHolder}'s record of {recordTime}s could fall today — {horse} is on a flyer!",
  "At this rate, {horse} might just break the track record of {recordTime}s!",
  "The pace {horse} is setting has track record written all over it — {recordTime}s is the mark.",
  "{horse} is eating up the ground — the {recordTime}s track record is in sight!",
  "A record-breaking performance could be on the cards — {horse} is on pace for {recordTime}s.",
  "The {recordTime}s track record set by {recordHolder} — {horse} is giving it a real shake!",
];

export const RETURNING_RUNNER_TEMPLATES: string[] = [
  "{horse} finished {prevPosition} in this race last time — looking to go one better today.",
  "Back for another crack — {horse} was {prevPosition} in this race previously.",
  "{horse} knows this race well — they finished {prevPosition} last time they ran here.",
  "Redemption on the mind of {horse} — {prevPosition} last time in this race.",
  "{horse} returns to this race having finished {prevPosition} previously — can they improve?",
  "Last time {horse} ran in this race, they crossed the line in {prevPosition} — today they want more.",
  "{horse} has been here before — {prevPosition} last time, but today could be different.",
 "The experience of finishing {prevPosition} in this race last time drives {horse} today.",
  "{horse} is back — last time it was {prevPosition}, but today they're chasing victory.",
  "A familiar race for {horse} — they were {prevPosition} in this contest before.",
  "{horse} has unfinished business in this race after finishing {prevPosition} last time.",
  "Determined to improve on {prevPosition} — {horse} returns to this race.",
  "Last time out in this race, {horse} was {prevPosition} — can they turn the tables today?",
  "{horse} knows the feeling of finishing {prevPosition} here — today they want a different result.",
];

export const COURSE_SPECIALIST_TEMPLATES: string[] = [
  "{horse} has run at {trackName} {visits} times before — they know every blade of grass here.",
  "A course specialist — {horse} has {visits} previous visits to {trackName}.",
  "{horse} is a {trackName} regular with {visits} runs here — experience counts.",
  "No stranger to {trackName} — {horse} has raced here {visits} times.",
  "{horse} has {visits} runs at {trackName} — they could navigate this track blindfolded.",
  "Experience at {trackName} — {horse} has been here {visits} times before.",
  "{horse} knows {trackName} like the back of their hand — {visits} previous visits.",
  "A true course specialist — {horse} has {visits} starts at {trackName}.",
  "{trackName} is a second home for {horse} with {visits} previous runs here.",
  "{horse} has seen {trackName} {visits} times before — that local knowledge is priceless.",
  "With {visits} visits to {trackName}, {horse} is one of the most experienced runners here.",
  "You can't buy {visits} runs of experience at {trackName} — {horse} has it in spades.",
  "{horse} is a {trackName} veteran — {visits} previous starts at this track.",
  "The {visits} times {horse} has run at {trackName} makes them a course specialist.",
];
