import type { NarrativeEvent } from "@/services/narrative/commentaryGenerator";

/**
 * Narrative commentary templates
 * Extracted from narrativeService.ts for better organization
 */

export const BIOGRAPHICAL_TEMPLATES = [
  "The {coat} {gender} {horse}, by {sire} out of {dam},",
  "{horse}, the {coat} {gender} representing {stable},",
  "Watch {horse}, a progeny of {sire},",
  "The {stable} runner, {horse},",
  "From the famous {family} family, {horse}",
];

export const FRAGMENTS = {
  PREFIXES: [
    "Unbelievable!",
    "Look at this!",
    "Incredible action,",
    "Right now,",
    "Unfolding before our eyes,",
    "As expected,",
    "Surprisingly,",
    "A dramatic turn,",
    "Stay focused on the pack,",
  ],
};

export const EXPERT_INSIGHT_TEMPLATES = {
  POSITIVE_FORM: [
    "{horse} has been in sparkling form lately, looking to continue that today.",
    "Expect a big run from {horse} given their recent track record.",
    "Condition looks peak for {horse} as they load into the gates.",
    "The stable is buzzing about {horse}'s chances today.",
    "{horse} looks primed for a massive effort today based on morning work.",
    "{horse} comes into this race in absolute peak condition.",
    "You can't ignore the recent numbers {horse} has been putting up.",
    "Riding a wave of good form, {horse} is definitely a major threat.",
    "{horse} seems to be getting better with every start this campaign.",
    "It's hard to look past {horse} when they're running this well.",
    "The confidence behind {horse} is completely justified by their recent outings.",
    "{horse} is a picture of health and form heading into this contest.",
  ],
  NEGATIVE_FORM: [
    "{horse} has struggled to find their best stride in recent starts.",
    "Looking for a bounce-back performance today from {horse}.",
    "Questions about the current fitness of {horse} after that last outing.",
    "This field might be a bit too deep for {horse} today.",
    "{horse} needs to show us a lot more after a string of disappointing efforts.",
    "The form line for {horse} has been a concern for the connections lately.",
    "It's been a tough campaign so far for {horse} as they try to find some rhythm.",
    "{horse} really needs to turn things around quickly with a good showing here.",
    "Confidence might be a bit low for {horse} coming into this one.",
    "We haven't seen the best of {horse} lately; they need to wake up today.",
    "{horse} looks to be struggling to recapture their earlier promise.",
    "It's hard to make a strong case for {horse} based on their recent starts.",
  ],
  DISTANCE_FIT: [
    "This {distance}m trip is right in the wheelhouse for {horse}.",
    "{horse} is a specialist at this distance.",
    "The distance shouldn't be an issue for {horse} today.",
    "Historically, {horse} excels at exactly this trip.",
    "{horse} will love every inch of this {distance}m journey.",
    "This {distance}m trip is where {horse} does their best work.",
    "A proven performer at {distance}m, {horse} is exactly where they want to be.",
    "{horse} has shown they can handle this {distance}m test with ease.",
    "The distance is perfect for {horse}'s natural running style.",
    "{horse} is uniquely suited to the demands of a {distance}m race.",
    "This trip is tailor-made for {horse}, giving them a distinct advantage.",
    "We know {horse} relishes a {distance}m challenge, so expect a bold showing.",
  ],
  NEW_DISTANCE: [
    "First time at {distance}m for {horse}, a real test of stamina.",
    "Testing the waters at this trip today with {horse}.",
    "Will {horse} see out the full {distance}m? We're about to find out.",
    "A major question mark over {horse} stepping up to this distance.",
    "Stepping into unknown territory today over {distance}m for {horse}.",
    "The big question is whether {horse} has the tank for this {distance}m.",
    "It's an ambitious ask to run {distance}m for the very first time, but {horse} tries today.",
    "Can {horse} handle the transition to {distance}m? The pedigree suggests maybe.",
    "We're going to learn a lot about {horse}'s versatility at this new {distance}m trip.",
    "Uncharted waters for {horse} at {distance}m, they'll need every ounce of grit.",
    "{horse} steps into the great unknown trying {distance}m for the first time.",
    "It's a gamble running {horse} at {distance}m today, let's see if it pays off.",
  ],
};

export const TEMPLATES: Record<NarrativeEvent, string[]> = {
  START: [
    "And they're off in the {raceName}!",
    "The gates are open and they're away!",
    "A clean start for the field in this {raceClass}!",
    "They break cleanly from the gates at {trackName}!",
    "A perfect dispatch for the {raceClass}!",
    "They're racing in the {raceName}!",
    "A smooth break for the runners in this {raceClass}.",
    "The flag drops and they're off at {trackName}!",
    "They burst out of the stalls for the {raceName}!",
    "It's a level start for this {raceClass} field!",
    "Underway in the {raceName}!",
    "The flag is down and we are racing!",
    "They've left the stalls in the {raceName}!",
    "A level break for all runners today!",
    "We're underway in this highly anticipated {raceClass}!",
    "The starter lets them go at {trackName}!",
  ],
  LEAD_CHANGE: [
    "{horse} takes the lead!",
    "{horse} moves to the front!",
    "{horse} has surged into the lead!",
    "New leader! It's {horse} taking control.",
    "{horse} stick's their nose in front!",
    "A bold move by {horse} to grab the initiative!",
    "{horse} is bossing the field now from the front!",
    "The {stable} runner {horse} has found the lead!",
  ],
  SURGE: [
    "{horse} is making a move!",
    "{horse} is finding another gear!",
    "Watch {horse} go! They're gaining ground fast.",
    "{horse} is picking up the pace!",
    "{horse} is accelerating through the field!",
    "The {coat} {gender} {horse} is really starting to motor!",
    "{horse} is weaving through traffic like they're standing still!",
    "{horse} finds a gap on the rail and explodes through!",
    "Going around the outside, it's {horse} flying!",
  ],
  FADE: [
    "{horse} is starting to tire.",
    "{horse} is losing ground.",
    "{horse} is dropping back now.",
    "{horse} can't keep up with this pace.",
    "The early effort is telling on {horse}.",
    "{horse} looks to be hitting a wall here.",
    "{horse} is being left behind as the pace quickens.",
    "Losing touch with the pack, {horse} is in trouble.",
  ],
  STRETCH: [
    "They're turning for home in the {raceName}!",
    "Into the final stretch!",
    "The wire is in sight!",
    "Final furlong! Who's got the legs?",
    "Down the stretch they come!",
    "It's a battle to the wire!",
    "The crowd is on its feet as they hit the straight!",
    "Ears pinned back, they're sprinting for home!",
    "They make the final turn in the {raceName}!",
    "The long drive for home begins now!",
    "It's a sprint to the finish in the {raceName}!",
    "They've hit the top of the straight!",
    "Every jockey asking for maximum effort now!",
    "The whips are out as they drive for the finish!",
    "The field straightens for the final drive!",
    "It's a desperate drive to the line now!",
    "Who wants this {raceName} the most?",
    "A true test of stamina awaits them in the stretch!",
  ],
  FINISH: [
    "{horse} wins it!",
    "It's {horse} at the wire!",
    "{horse} takes the victory!",
    "A brilliant finish for {horse}!",
    "What a performance by {horse} to take the {raceName}!",
    "He's done it! {horse} is the winner!",
    "A photo finish! But {horse} looks to have it!",
    "{horse} crosses the wire in first!",
    "A spectacular win for {horse}!",
    "{horse} takes the honors in the {raceName}!",
    "Nobody can catch {horse} today!",
    "It's all {horse} at the finish line!",
    "A masterclass performance from {horse} to win it!",
    "{horse} strikes gold in the {raceName}!",
    "A memorable victory for {horse}!",
    "An absolute masterclass from {horse} today!",
    "{horse} claims the prize with authority!",
    "Nobody was catching {horse} in this form!",
    "A gutsy, hard-fought triumph for {horse}!",
    "{horse} secures the glory in the shadow of the post!",
  ],
  POSITION_CHECK: [
    "{horse} is running well in {rank}.",
    "In {rank} place, it's {horse}.",
    "{horse} holds steady in {rank}.",
    "{horse} is currently in {rank}.",
    "Tracking the leaders in {rank} is {horse}.",
    "{horse} is biding their time in {rank}.",
    "Settling nicely into {rank} position is {horse}.",
    "{horse} has found a rhythm in {rank}.",
    "Running comfortably in {rank}, we find {horse}.",
    "Keeping a close watch from {rank} is {horse}.",
    "Occupying {rank} spot for now is {horse}.",
    "{horse} travels smoothly in {rank}.",
  ],
  DRAFTING: [
    "{horse} is tucked in behind {other}, saving ground.",
    "{horse} finds a nice slipstream behind {other}.",
    "Smart riding by {horse}, drafting behind {other}.",
    "{horse} is biding their time in the pocket.",
    "Conserving energy, {horse} is glued to the back of {other}.",
    "{horse} gets a beautiful tow into the race behind {other}.",
    "Following every move of {other}, {horse} sits patiently.",
    "Enjoying a perfect trail right behind {other} is {horse}.",
    "{horse} is anchored firmly in the slipstream of {other}.",
    "Letting {other} do the heavy lifting, {horse} waits for the gap.",
    "A textbook ride so far, {horse} parked right on {other}'s heels.",
    "{horse} uses {other} as a perfect windbreak here.",
  ],
  HOT_PACE: [
    "The pace is scorching early on!",
    "They're really flying out there!",
    "A very hot pace being set by the front-runners.",
    "Front-runners are battling hard for the lead.",
    "They're going at a suicidal clip in front!",
    "They are absolutely smoking through these early fractions!",
    "A frantic gallop being established right from the off!",
    "No quarters asked or given with this blistering pace!",
    "They are not hanging around in the early stages here!",
    "A genuine speed duel developing up front!",
    "This breakneck pace will surely test their stamina later!",
    "They've set a cracking tempo right from the jump!",
  ],
  WEATHER_COMMENT: [
    "The {weather} conditions might favor the stayers today.",
    "It's a {weather} day at the track, surface is {trackCondition}.",
    "The track is {trackCondition}, which will test their mettle.",
    "Conditions are perfect for a fast time today.",
    "The {trackCondition} going will play a major role as they tire.",
    "With {weather} weather overhead, the track is playing {trackCondition}.",
    "The {trackCondition} surface is definitely a factor under these {weather} skies.",
    "Runners are kicking up the {trackCondition} dirt in this {weather} weather.",
    "Interesting to see who handles this {trackCondition} ground best.",
    "A beautiful {weather} day for racing on this {trackCondition} surface.",
    "These {weather} conditions make the {trackCondition} track a real equalizer.",
  ],
  STABLE_WATCH: [
    "Keep an eye on the {stable} runner, {horse}.",
    "{stable} will be hoping for a big run from {horse} here.",
    "{horse} carrying the famous {stable} colors.",
    "The {stable} team looks confident with {horse} today.",
    "Much expected from the {stable} representative, {horse}.",
    "The {stable} connections must be pleased with {horse}'s position.",
    "A pivotal moment for {horse} and the {stable} operation.",
    "Can {horse} deliver the goods for the {stable} yard?",
    "{horse} represents the powerful {stable} stable here.",
    "The {stable} camp sends out a very ready {horse}.",
    "We've heard good reports from {stable} about {horse}.",
  ],
  MILESTONE: [
    "Passing the halfway point now.",
    "Only {remaining}m to go in the {raceName}.",
    "They've got {remaining}m left to find a winner.",
    "Entering the final 400 meters!",
    "They're inside the final 100! Who wants it more?",
    "Approaching the crucial {remaining}m mark of the {raceName}.",
    "Just {remaining}m left to decide the {raceName}!",
    "They cross the halfway point of this testing journey.",
    "The long run continues with {remaining}m remaining.",
    "They are eating up the ground, {remaining}m to the wire.",
    "Heading into the business end with {remaining}m to travel.",
    "The pressure mounts as they hit the final {remaining}m!",
  ],
  EXPERT_INSIGHT: [],
  GAP_ANNOUNCEMENT: [
    "{horse} is leading by {lengths} lengths!",
    "{horse} has a {lengths} length advantage at the front.",
    "{horse} is pulling away! The gap is now {lengths} lengths.",
    "A dominant display from {horse}, clear by {lengths}!",
    "{horse} is absolutely bounding away, a {lengths} length margin!",
    "The rest of the field is struggling to close a {lengths} length gap!",
    "{horse} has opened up a commanding {lengths} length lead!",
    "Look at the separation! {horse} is out by {lengths} lengths!",
  ],
  ATMOSPHERE: [
    "The roar of the crowd is deafening!",
    "A tense atmosphere here at {trackName}.",
    "The anticipation is palpable as they round the turn.",
    "Every jockey is looking for that winning opening.",
    "You can feel the electricity in the grandstands at {trackName}!",
    "The noise level is rising as the drama unfolds here.",
    "A crackling atmosphere builds around {trackName}!",
    "The fans are on their feet, roaring them on!",
    "Tension mounts across {trackName} as the race develops.",
    "It's a cauldron of noise at {trackName} today!",
    "The crowd senses something special is about to happen.",
    "An incredible buzz around the track as they enter the crucial stage.",
  ],
  LANE_WATCH: [
    "{horse} is caught wide on the turn, covering a lot of extra ground!",
    "Looking for the rail, but {horse} is trapped out three-wide.",
    "A tough trip for {horse}, parked out wide without cover.",
    "The jockey on {horse} is trying to tuck in, but the rail is packed.",
    "{horse} is charting a very wide course around the bend.",
    "Forced out four-wide, {horse} has a mountain to climb now.",
    "No daylight on the rail, so {horse} takes the overland route.",
    "Caught deep on the track, {horse} is doing this the hard way.",
    "A ground-saving trip is out the window for {horse} who travels wide.",
    "{horse} is caught out on a limb, miles from the inside rail.",
    "Desperately seeking cover, {horse} remains exposed out wide.",
    "{horse} will need to be special to win after covering this much ground.",
  ],
};
