import type { NarrativeEvent } from "@/services/narrative/commentaryGenerator";
import {
  JOCKEY_MOVE_TEMPLATES,
  JOCKEY_TACTIC_TEMPLATES,
  JOCKEY_MASTERY_TEMPLATES,
  JOCKEY_APPRENTICE_TEMPLATES,
} from "./jockeyTemplates";
import {
  ATMOSPHERE_LONG_STRAIGHT_TEMPLATES,
  ATMOSPHERE_TIGHT_TURN_TEMPLATES,
  ATMOSPHERE_GRADED_TEMPLATES,
  ATMOSPHERE_TRIPLE_CROWN_TEMPLATES,
  ATMOSPHERE_ELEVATION_TEMPLATES,
} from "./atmosphereTemplates";
import {
  DEFENDING_CHAMPION_TEMPLATES,
  TRACK_RECORD_TEMPLATES,
  RETURNING_RUNNER_TEMPLATES,
  COURSE_SPECIALIST_TEMPLATES,
} from "./raceContextTemplates";
import {
  MIDRACE_INSIGHT_TEMPLATES,
  MIDRACE_INSIGHT_CLOSER_TEMPLATES,
  CLOSING_INSIGHT_TEMPLATES,
  PACE_ANALYSIS_TEMPLATES,
} from "./ongoingInsightTemplates";
import {
  COMEBACK_NOTE_TEMPLATES,
  REDEMPTION_NOTE_TEMPLATES,
  CONFIRMATION_NOTE_TEMPLATES,
} from "./chainingTemplates";

/**
 * Narrative commentary templates
 * Extracted from narrativeService.ts for better organization
 */

// Re-export biographical and expert insight templates for backward compatibility
export { BIOGRAPHICAL_TEMPLATES, FRAGMENTS } from "./biographicalTemplates";
export { EXPERT_INSIGHT_TEMPLATES } from "./expertInsightTemplates";
export {
  JOCKEY_MOVE_TEMPLATES,
  JOCKEY_TACTIC_TEMPLATES,
  JOCKEY_MASTERY_TEMPLATES,
  JOCKEY_APPRENTICE_TEMPLATES,
  JOCKEY_TRAIT_TEMPLATES,
} from "./jockeyTemplates";
export {
  ATMOSPHERE_LONG_STRAIGHT_TEMPLATES,
  ATMOSPHERE_TIGHT_TURN_TEMPLATES,
  ATMOSPHERE_GRADED_TEMPLATES,
  ATMOSPHERE_TRIPLE_CROWN_TEMPLATES,
  ATMOSPHERE_ELEVATION_TEMPLATES,
} from "./atmosphereTemplates";
export {
  DEFENDING_CHAMPION_TEMPLATES,
  TRACK_RECORD_TEMPLATES,
  RETURNING_RUNNER_TEMPLATES,
  COURSE_SPECIALIST_TEMPLATES,
} from "./raceContextTemplates";
export {
  MIDRACE_INSIGHT_TEMPLATES,
  MIDRACE_INSIGHT_CLOSER_TEMPLATES,
  CLOSING_INSIGHT_TEMPLATES,
  PACE_ANALYSIS_TEMPLATES,
} from "./ongoingInsightTemplates";
export {
  COMEBACK_NOTE_TEMPLATES,
  REDEMPTION_NOTE_TEMPLATES,
  CONFIRMATION_NOTE_TEMPLATES,
} from "./chainingTemplates";
export { DYNAMIC_OPENERS, DYNAMIC_TRAILERS } from "./dynamicClauses";

export const TEMPLATES: Record<NarrativeEvent, string[]> = {
  START: [
    "And they're off in the {raceName}!",
    "The gates are open and they're away!",
    "A clean start for the field in this {raceClass}!",
    "They break cleanly from the gates at {trackName}!",
    "A perfect dispatch for the {raceClass}!",
    "They're racing in the {raceName}!",
    "A smooth break for the runners in this {raceClass}.",
    "The flag drops and they're off at {trackName}!",
    "They burst out of the stalls for the {raceName}!",
    "It's a level start for this {raceClass} field!",
    "Underway in the {raceName}!",
    "The flag is down and we are racing!",
    "They've left the stalls in the {raceName}!",
    "A level break for all runners today!",
    "We're underway in this highly anticipated {raceClass}!",
    "The starter lets them go at {trackName}!",
  ],
  LEAD_CHANGE: [
    "{horse} takes the lead!",
    "{horse} moves to the front!",
    "{horse} has surged into the lead!",
    "New leader! It's {horse} taking control.",
    "{horse} stick's their nose in front!",
    "A bold move by {horse} to grab the initiative!",
    "{horse} is bossing the field now from the front!",
    "The {stable} runner {horse} has found the lead!",
    "It's {horse} who strikes the front now!",
    "{horse} wrests the lead away!",
    "A new pacemaker emerges as {horse} goes to the front.",
    "{horse} pushes past them to take the advantage!",
    "They're chasing {horse} now!",
    "{horse} strikes the front with a burst of speed!",
    "The lead changes hands, {horse} is the new leader!",
    "Taking command of the race, it's {horse}!",
  ],
  SURGE: [
    "{horse} is making a move!",
    "{horse} is finding another gear!",
    "Watch {horse} go! They're gaining ground fast.",
    "{horse} is picking up the pace!",
    "{horse} is accelerating through the field!",
    "The {coat} {gender} {horse} is really starting to motor!",
    "{horse} is weaving through traffic like they're standing still!",
    "{horse} finds a gap on the rail and explodes through!",
    "Going around the outside, it's {horse} flying!",
    "{horse} is putting in a massive run right now!",
    "Here comes {horse} with a sustained burst of speed!",
    "{horse} slices through the pack with ease!",
    "A scintillating move from {horse}!",
    "{horse} is gobbling up the ground!",
    "Look at the acceleration from {horse}!",
    "{horse} starts to roll on the outside!",
  ],
  FADE: [
    "{horse} is starting to tire.",
    "{horse} is losing ground.",
    "{horse} is dropping back now.",
    "{horse} can't keep up with this pace.",
    "The early effort is telling on {horse}.",
    "{horse} looks to be hitting a wall here.",
    "{horse} is being left behind as the pace quickens.",
    "Losing touch with the pack, {horse} is in trouble.",
    "{horse} is retreating through the field.",
    "The tank looks empty for {horse}.",
    "{horse} is struggling to maintain their position.",
    "They are swamping {horse} right now.",
    "{horse} has run their race and is backing up.",
    "It's a rapid retreat from {horse}.",
    "{horse} is dropping out of contention.",
  ],
  STRETCH: [
    "They're turning for home in the {raceName}!",
    "Into the final stretch!",
    "The wire is in sight!",
    "Final furlong! Who's got the legs?",
    "Down the stretch they come!",
    "It's a battle to the wire!",
    "The crowd is on its feet as they hit the straight!",
    "Ears pinned back, they're sprinting for home!",
    "They make the final turn in the {raceName}!",
    "The long drive for home begins now!",
    "It's a sprint to the finish in the {raceName}!",
    "They've hit the top of the straight!",
    "Every jockey asking for maximum effort now!",
    "The whips are out as they drive for the finish!",
    "The field straightens for the final drive!",
    "It's a desperate drive to the line now!",
    "Who wants this {raceName} the most?",
    "A true test of stamina awaits them in the stretch!",
  ],
  FINISH: [
    "{horse} wins it!",
    "It's {horse} at the wire!",
    "{horse} takes the victory!",
    "A brilliant finish for {horse}!",
    "What a performance by {horse} to take the {raceName}!",
    "He's done it! {horse} is the winner!",
    "A photo finish! But {horse} looks to have it!",
    "{horse} crosses the wire in first!",
    "A spectacular win for {horse}!",
    "{horse} takes the honors in the {raceName}!",
    "Nobody can catch {horse} today!",
    "It's all {horse} at the finish line!",
    "A masterclass performance from {horse} to win it!",
    "{horse} strikes gold in the {raceName}!",
    "A memorable victory for {horse}!",
    "An absolute masterclass from {horse} today!",
    "{horse} claims the prize with authority!",
    "Nobody was catching {horse} in this form!",
    "A gutsy, hard-fought triumph for {horse}!",
    "{horse} secures the glory in the shadow of the post!",
  ],
  POSITION_CHECK: [
    "{horse} is running well in {rank}.",
    "In {rank} place, it's {horse}.",
    "{horse} holds steady in {rank}.",
    "{horse} is currently in {rank}.",
    "Tracking the leaders in {rank} is {horse}.",
    "{horse} is biding their time in {rank}.",
    "A comfortable {rank} for {horse} at this stage.",
    "{horse} is travelling nicely in {rank} position.",
    "No panic from {horse}, settled in {rank}.",
    "The {coat} {gender} is cruising along in {rank}.",
    "{horse} finds a rhythm in {rank} spot.",
    "Steady as she goes for {horse} in {rank}.",
    "{horse} is holding their ground nicely in {rank}.",
    "Settled into a good rhythm in {rank} is {horse}.",
    "{horse} looks completely relaxed in {rank}.",
    "Nothing changing for {horse}, maintaining {rank} place.",
  ],
  DRAFTING: [
    "{horse} is tucked in behind {other}, saving ground.",
    "{horse} finds a nice slipstream behind {other}.",
    "Smart riding by {horse}, drafting behind {other}.",
    "{horse} is biding their time in the pocket.",
    "Conserving energy, {horse} is glued to the back of {other}.",
    "{horse} is getting a lovely tow behind {other}.",
    "Box-seat position for {horse} just off the heels of {other}.",
    "{horse} is enjoying the cover provided by {other}.",
    "Racing with economy, {horse} drafts behind {other}.",
    "{horse} is perfectly placed in the wake of {other}.",
    "A textbook trip for {horse}, sheltered behind {other}.",
    "{horse} is saving every inch behind {other}.",
    "{horse} is getting a free ride behind {other}.",
    "Sitting patiently in the slipstream of {other} is {horse}.",
    "{horse} lets {other} do all the hard work up front.",
    "A smart tactical ride sees {horse} covered up behind {other}.",
  ],
  HOT_PACE: [
    "The pace is scorching early on!",
    "They're really flying out there!",
    "A very hot pace being set by the front-runners.",
    "Front-runners are battling hard for the lead.",
    "They're going at a suicidal clip in front!",
    "The early fractions are blazing fast!",
    "This is a genuine burn-up in the early stages!",
    "The tempo is red-hot as they blaze along!",
    "Those early sectionals are eye-watering!",
    "The front-runners are setting a punishing pace!",
    "They're going faster than a runaway train up front!",
    "The pace is furious — someone will pay for this later!",
    "They are absolutely flying early doors!",
    "No prisoners being taken with this blistering pace!",
    "The speed they are showing is quite something!",
    "It's a genuine test of stamina with this early tempo!",
  ],
  WEATHER_COMMENT: [
    "The {weather} conditions might favor the stayers today.",
    "It's a {weather} day at the track, surface is {trackCondition}.",
    "The track is {trackCondition}, which will test their mettle.",
    "Conditions are perfect for a fast time today.",
    "The {weather} is playing havoc with the going.",
    "A {trackCondition} surface adds an extra layer of complexity today.",
    "The {weather} won't bother the mudlarks in this field.",
    "Under {weather} skies, the track is riding {trackCondition}.",
    "The ground is {trackCondition} — expect a tactical race.",
    "With the weather being {weather}, stamina will be at a premium.",
    "The {weather} could shake things up on this {trackCondition} surface.",
    "It's a testing {trackCondition} track under {weather} conditions.",
    "The {weather} skies loom over this {trackCondition} surface.",
    "It's a beautiful {weather} day for racing on a {trackCondition} track.",
    "The {trackCondition} ground under these {weather} conditions is a true test.",
    "We have {weather} weather today, setting the stage on this {trackCondition} surface.",
  ],
  STABLE_WATCH: [
    "Keep an eye on the {stable} runner, {horse}.",
    "{stable} will be hoping for a big run from {horse} here.",
    "{horse} carrying the famous {stable} colors.",
    "The {stable} team looks confident with {horse} today.",
    "{stable} has {horse} primed for a big performance.",
    "The {stable} silks are flying on {horse} today.",
    "{horse} is the pride of the {stable} string.",
    "Big expectations from the {stable} camp for {horse}.",
    "{stable} sends {horse} into battle with high hopes.",
    "The {stable} operation has {horse} peaking at the right time.",
    "All eyes on {horse} from the powerful {stable} stable.",
    "{horse} is flying the flag for {stable} in this one.",
    "{stable} is well-represented here by {horse}.",
    "The familiar silks of {stable} are carried by {horse}.",
    "{horse} looks a picture of health for the {stable} yard.",
    "A major player for the {stable} operation today is {horse}.",
  ],
  MILESTONE: [
    "Passing the halfway point now.",
    "Only {remaining}m to go in the {raceName}.",
    "They've got {remaining}m left to find a winner.",
    "Entering the final 400 meters!",
    "They're inside the final 100! Who wants it more?",
    "We're at the halfway marker — time to make a move.",
    "The halfway point is behind them, {remaining}m remains.",
    "Into the final 400m — the pressure is building!",
    "Just {remaining}m standing between them and glory.",
    "The business end of the race is here with {remaining}m left.",
    "They're running out of real estate — only {remaining}m to go!",
    "The crowd rises as they pass the halfway point in the {raceName}.",
    "They've reached the midpoint of the journey.",
    "The halfway stage is upon us in the {raceName}.",
    "It's time to get serious as they pass the halfway mark.",
    "With {remaining}m remaining, the tactics begin to unfold.",
  ],
  MILESTONE_HALFWAY: [
    "They've reached the halfway marker — the pace is genuine!",
    "Passing the halfway point in the {raceName} now.",
    "We're at the halfway stage — time for the tactical decisions to unfold.",
    "The midpoint of the {raceName} is behind them, {remaining}m remains.",
    "Halfway there! Only {remaining}m left to find a winner.",
    "They've reached the midpoint of the journey in the {raceName}.",
    "The crowd rises as they pass the halfway point in the {raceName}.",
    "We're at the halfway marker — who's going to make the first move?",
    "It's time to get serious as they pass the halfway mark.",
    "The halfway point is behind them — {remaining}m to go.",
    "They're at the halfway stage of the {raceName} — the real racing starts now.",
    "Halfway through the {raceName} and the pace is honest.",
    "They've hit the halfway marker — the tactics begin to unfold.",
    "The midpoint of the race is upon us in the {raceName}.",
    "Halfway done — {remaining}m stands between them and the finish.",
    "They pass the halfway point with {remaining}m remaining in the {raceName}.",
  ],
  MILESTONE_FINAL_400: [
    "Into the final 400m — the pressure is building!",
    "Entering the final 400 meters of the {raceName}!",
    "They're inside the final 400m — it's crunch time now.",
    "The last 400m of the {raceName} — who wants it most?",
    "Final quarter mile! The jockeys are getting serious.",
    "They've hit the 400m marker — the race is about to get real.",
    "Inside the final 400m of the {raceName} — positions are crucial now.",
    "The business end is here — 400m to go and everything to play for.",
    "They're approaching the final 400m — the pace is about to lift.",
    "400 meters remain — it's time to put the cards on the table.",
    "Into the final 400m of the {raceName} — the tension is palpable.",
    "The 400m marker passes — the sprint for home begins here.",
    "They're inside the last 400m — who's got the legs?",
    "Final 400m of the {raceName} — the jockeys are reaching for the whip.",
    "The pressure cooker of the final 400m is upon them.",
    "400 meters from glory — the race is heating up in the {raceName}.",
  ],
  MILESTONE_FINAL_200: [
    "Inside the final 200m — it's now or never!",
    "200 meters to go in the {raceName} — who's finding the most?",
    "They're inside the final 200m — every stride counts now.",
    "The last 200m of the {raceName} — hearts are pounding!",
    "Final 200m! It's a test of courage and stamina.",
    "They've hit the 200m marker — the finish is in sight.",
    "Inside the final 200 meters — the drama is building.",
    "200m from the wire — who's got the finishing kick?",
    "The final 200m of the {raceName} — this is where legends are made.",
    "They're in the last 200m — the crowd is on its feet!",
    "200 meters remain — it's a battle to the line.",
    "Inside the final 200m of the {raceName} — positions are everything.",
    "The 200m marker passes — it's a sprint to the finish now!",
    "Final 200m — the jockeys are giving it everything.",
    "They're inside the last 200 meters — the tension is unbearable.",
    "200m from home in the {raceName} — who will prevail?",
  ],
  MILESTONE_FINAL_100: [
    "They're inside the final 100! Who wants it more?",
    "100 meters to go in the {raceName} — it's a nail-biter!",
    "Inside the final 100m — every muscle is burning now.",
    "The last 100m of the {raceName} — this is the moment of truth!",
    "Final 100 meters! It's all on the line.",
    "They've hit the 100m marker — the wire is within reach.",
    "Inside the final 100m — the crowd is roaring!",
    "100m to go — who's got the final burst of speed?",
    "The last 100m of the {raceName} — it's a desperate drive to the line.",
    "They're in the final 100 meters — this is what it all comes down to.",
    "100m from the finish — the race is on a knife's edge.",
    "Inside the final 100m of the {raceName} — hearts are in mouths!",
    "The 100m marker passes — it's a photo finish in the making.",
    "Final 100m — the jockeys are riding for their lives.",
    "They're inside the last 100 meters — the finish line beckons.",
    "100m from glory in the {raceName} — who will etch their name in history?",
  ],
  EXPERT_INSIGHT: [],
  JOCKEY_MOVE: JOCKEY_MOVE_TEMPLATES,
  JOCKEY_TACTIC: JOCKEY_TACTIC_TEMPLATES,
  JOCKEY_MASTERY: JOCKEY_MASTERY_TEMPLATES,
  JOCKEY_APPRENTICE: JOCKEY_APPRENTICE_TEMPLATES,
  JOCKEY_TRAIT: [], // Populated dynamically via JOCKEY_TRAIT_TEMPLATES
  ATMOSPHERE_LONG_STRAIGHT: ATMOSPHERE_LONG_STRAIGHT_TEMPLATES,
  ATMOSPHERE_TIGHT_TURN: ATMOSPHERE_TIGHT_TURN_TEMPLATES,
  ATMOSPHERE_GRADED: ATMOSPHERE_GRADED_TEMPLATES,
  ATMOSPHERE_TRIPLE_CROWN: ATMOSPHERE_TRIPLE_CROWN_TEMPLATES,
  ATMOSPHERE_ELEVATION: ATMOSPHERE_ELEVATION_TEMPLATES,
  DEFENDING_CHAMPION: DEFENDING_CHAMPION_TEMPLATES,
  TRACK_RECORD: TRACK_RECORD_TEMPLATES,
  RETURNING_RUNNER: RETURNING_RUNNER_TEMPLATES,
  COURSE_SPECIALIST: COURSE_SPECIALIST_TEMPLATES,
  MIDRACE_INSIGHT: MIDRACE_INSIGHT_TEMPLATES,
  CLOSING_INSIGHT: CLOSING_INSIGHT_TEMPLATES,
  PACE_ANALYSIS: PACE_ANALYSIS_TEMPLATES,
  COMEBACK_NOTE: COMEBACK_NOTE_TEMPLATES,
  REDEMPTION_NOTE: REDEMPTION_NOTE_TEMPLATES,
  CONFIRMATION_NOTE: CONFIRMATION_NOTE_TEMPLATES,
  GAP_ANNOUNCEMENT: [
    "{horse} is leading by {lengths} lengths!",
    "{horse} has a {lengths} length advantage at the front.",
    "{horse} is pulling away! The gap is now {lengths} lengths.",
    "A dominant display from {horse}, clear by {lengths}!",
    "{horse} is absolutely bounding away, a {lengths} length margin!",
    "The rest of the field is struggling to close a {lengths} length gap!",
    "{horse} has opened up a commanding {lengths} length lead!",
    "Look at the separation! {horse} is out by {lengths} lengths!",
    "A chasm has opened up! {horse} leads by {lengths} lengths.",
    "{horse} is putting on a clinic, clear by {lengths} lengths!",
    "It's a one-horse race right now, {horse} leads by {lengths}!",
    "They can't get near {horse}, the margin is {lengths} lengths.",
    "{horse} extends the advantage to {lengths} lengths!",
    "Nobody is going with {horse}, now {lengths} lengths in front.",
    "A sprawling {lengths} length lead for {horse}!",
    "{horse} says 'catch me if you can' with a {lengths} length gap!",
  ],
  ATMOSPHERE: [
    "The roar of the crowd is deafening!",
    "A tense atmosphere here at {trackName}.",
    "The anticipation is palpable as they round the turn.",
    "Every jockey is looking for that winning opening.",
    "The grandstand is buzzing with excitement!",
    "You could cut the tension with a knife at {trackName}.",
    "The crowd is on the edge of their seats!",
    "A thrilling atmosphere envelops the course.",
    "The noise is incredible as they sweep around the bend.",
    "Fans are on their feet as the drama unfolds!",
    "The electric atmosphere at {trackName} is something special.",
    "A deafening roar goes up from the packed stands!",
    "The energy in the grandstand is absolutely electric!",
    "Cheers echo across {trackName} as the field battles on.",
    "A collective gasp goes up from the spectators!",
    "The spectators are bringing the noise today!",
    "It's a wall of sound from the rail to the rafters!",
    "The stakes are high and the crowd knows it!",
    "Every eye at the track is glued to the action.",
    "The roar from the grandstand is shaking the ground!",
    "You can feel the electricity in the air today.",
    "The passionate crowd at {trackName} is loving this!",
    "What a spectacle we have unfolding before us!",
    "The atmosphere is at fever pitch!",
  ],
  LANE_WATCH: [
    "{horse} is caught wide on the turn, covering a lot of extra ground!",
    "Looking for the rail, but {horse} is trapped out three-wide.",
    "A tough trip for {horse}, parked out wide without cover.",
    "The jockey on {horse} is trying to tuck in, but the rail is packed.",
    "{horse} is burning fuel out there, racing wide on the bend.",
    "No cover for {horse} — they're doing it the hard way.",
    "{horse} is three-deep without a friend in sight.",
    "The wide trip is costing {horse} valuable ground.",
    "{horse} is out in the car park, covering extra distance.",
    "Stuck on the fence with nowhere to go, {horse} is boxed in.",
    "{horse} is navigating a tricky path on the outside.",
    "The jockey is working overtime to get {horse} out of trouble.",
    "{horse} is caught out on a limb here.",
    "A difficult passage for {horse}, racing without cover.",
    "{horse} is forced to take the overland route today.",
    "The jockey on {horse} is struggling to find a position near the rail.",
  ],
  FLYING: [
    "{horse} is absolutely flying out there!",
    "What a performance from {horse} — travelling like a dream!",
    "{horse} is on the bridle and cruising!",
    "Effortless from {horse}, gliding over the ground!",
    "{horse} is travelling beautifully, full of running!",
    "Look at {horse} go — that is textbook stuff!",
    "{horse} is cantering all over them!",
    "A magnificent display from {horse}, on the bridle and dominant!",
    "{horse} is going like a machine!",
    "The {coat} {gender} {horse} is travelling within itself!",
    "{horse} makes it look easy — still on the bridle!",
    "That is gorgeous action from {horse}!",
    "{horse} is bowling along in front, completely relaxed!",
    "The jockey hasn't moved on {horse} — that is a seriously good sign!",
    "{horse} is travelling like a Group 1 winner!",
    "A dream run for {horse} — every post a winning post!",
  ],
  BATTLING: [
    "{horse} is locked in a fierce battle!",
    "A real dogfight developing involving {horse}!",
    "{horse} is giving it everything in this duel!",
    "Neither giving an inch — {horse} is fighting tooth and nail!",
    "{horse} is in the thick of the fight!",
    "A tremendous tussle — {horse} is not backing down!",
    "{horse} is battling like a warrior!",
    "This is a proper scrap — {horse} is digging deep!",
    "{horse} is giving no quarter in this battle!",
    "A real slugfest — {horse} is standing tall!",
    "{horse} is in the wars but fighting on bravely!",
    "A tremendous contest — {horse} is giving as good as they get!",
    "{horse} is grappling for supremacy!",
    "The {coat} {gender} {horse} is in the heat of battle!",
    "{horse} is putting their heart into this duel!",
    "A real arm-wrestle — {horse} is not for turning!",
  ],
  BOXED_IN: [
    "{horse} is boxed in with nowhere to go!",
    "No room for {horse} — needs a gap to appear!",
    "{horse} is trapped on the rail, desperate for a run!",
    "Traffic trouble for {horse} — the jockey is searching for a way out!",
    "{horse} is short of running room!",
    "A traffic jam for {horse} — boxed in on all sides!",
    "{horse} is locked away on the inside!",
    "Nowhere to go for {horse} — the field is closing in!",
    "{horse} is caught behind a wall of horses!",
    "The jockey on {horse} is screaming for a gap!",
    "{horse} is stuck in traffic — needs luck!",
    "A nightmare trip for {horse} — boxed in and waiting!",
    "{horse} is pinned on the fence with no escape!",
    "The run has completely closed for {horse}!",
    "{horse} is shuffled back and boxed in!",
    "A wall of horses in front of {horse} — where is the gap?",
  ],
  GRINDING: [
    "{horse} is grinding away relentlessly!",
    "{horse} is staying on at the one tempo!",
    "Not quickening, but {horse} is not stopping either!",
    "{horse} is plugging away gamely!",
    "A relentless effort from {horse} — grinding forward!",
    "{horse} is plugging on at the same pace!",
    "{horse} is staying on dourly!",
    "A game effort from {horse} — just grinding away!",
    "{horse} is not flashy but is getting the job done!",
    "Steady as she goes — {horse} is grinding it out!",
    "{horse} is plugging on with real determination!",
    "A stout staying effort from {horse}!",
    "{horse} is grinding forward, one stride at a time!",
    "The {coat} {gender} {horse} is staying on gamely!",
    "{horse} is not stopping — just grinding away!",
    "A relentless, grinding effort from {horse}!",
  ],
  FLAGGING: [
    "{horse} is starting to flag!",
    "The effort is telling on {horse}!",
    "{horse} is losing ground now!",
    "{horse} is starting to feel the pinch!",
    "The tank is emptying for {horse}!",
    "{horse} is beginning to labour!",
    "The early pace is catching up with {horse}!",
    "{horse} is starting to drop away!",
    "The {coat} {gender} {horse} is feeling the effort!",
    "{horse} is not finding anything extra!",
    "The well is running dry for {horse}!",
    "{horse} is starting to go backwards!",
    "A tough stage for {horse} — the effort is telling!",
    "{horse} is losing touch with the leaders!",
    "The petrol is running out for {horse}!",
    "{horse} is starting to feel the burn!",
  ],
  IN_TROUBLE: [
    "{horse} is in real trouble here!",
    "A dramatic collapse from {horse}!",
    "{horse} is dropping away sharply!",
    "The wheels have come off for {horse}!",
    "{horse} is being left behind!",
    "A worrying performance from {horse}!",
    "{horse} is in severe difficulties!",
    "The {coat} {gender} {horse} is going backwards fast!",
    "{horse} is completely out of petrol!",
    "A sorry sight — {horse} is in trouble!",
    "{horse} is being nursed home!",
    "The jockey on {horse} is just saving ground now!",
    "{horse} is struggling badly!",
    "A dramatic reversal for {horse}!",
    "{horse} is going backwards through the field!",
    "The race is over for {horse} — just trying to get home!",
  ],
  AILING: [
    "{horse} appears to be carrying a complaint!",
    "Something is not right with {horse} — a tender action!",
    "{horse} doesn't look sound out there!",
    "A worrying display from {horse} — not moving freely!",
    "{horse} is racing gingerly — that is a concern!",
    "The action of {horse} is giving cause for concern!",
    "{horse} is not travelling comfortably at all!",
    "There is something amiss with {horse}!",
    "The {coat} {gender} {horse} is showing signs of distress!",
    "{horse} is carrying an issue into this race!",
    "A laboured effort from {horse} — connections will be worried!",
    "{horse} is not moving with any fluency!",
    "The stride of {horse} looks short and uncomfortable!",
    "{horse} is feeling the effects of a complaint!",
    "A concerning display — {horse} is not at their best!",
    "The jockey on {horse} is mindful of a problem!",
  ],
  SETTLED: [
    "{horse} is settled beautifully in the run!",
    "{horse} is travelling comfortably within itself!",
    "A relaxed {horse} is going through the motions!",
    "{horse} is on the bridle and happy!",
    "Everything is going to plan for {horse}!",
    "{horse} is cantering along nicely!",
    "A smooth trip for {horse} — no issues at all!",
    "{horse} is going the pace happily!",
    "The {coat} {gender} {horse} is travelling like a dream!",
    "{horse} is settled and waiting for the moment!",
    "A trouble-free run for {horse} so far!",
    "{horse} is biding their time comfortably!",
    "The jockey on {horse} is sitting motionless!",
    "{horse} is going along on the bridle!",
    "A relaxed and comfortable {horse}!",
    "{horse} is travelling nicely within itself!",
  ],
};
