import type { NarrativeEvent } from "@/services/narrative/commentaryGenerator";

/**
 * Narrative commentary templates
 * Extracted from narrativeService.ts for better organization
 */

export const BIOGRAPHICAL_TEMPLATES = [
  "The {coat} {gender} {horse}, by {sire} out of {dam},",
  "{horse}, the {coat} {gender} representing {stable},",
  "Watch {horse}, a progeny of {sire},",
  "The {stable} runner, {horse},",
  "From the famous {family} family, {horse}",
  "A magnificent {coat} {gender}, {horse} steps up,",
  "{horse} carries the hopes of {stable} today,",
  "Sired by the great {sire}, here is {horse},",
  "Tracing back to the {family} line, {horse} is one to watch,",
  "The {coat} {gender} {horse} looks to make a statement,",
  "Representing the {stable} operation, {horse},",
  "Bred in the purple, {horse}, a son of {sire},",
  "{horse}, a beautifully bred {coat} {gender} out of {dam},",
  "The pride of the {family} lineage, {horse},",
  "Carrying the colors of {stable}, it's {horse},",
  "{horse}, a striking {coat} {gender} by {sire},",
  "Another talented progeny of {sire}, {horse} is here,",
  "A well-regarded {coat} {gender}, {horse},",
  "The {stable} team sends out their {coat} {gender}, {horse},",
];

export const FRAGMENTS = {
  PREFIXES: [
    "Unbelievable!",
    "Look at this!",
    "Incredible action,",
    "Right now,",
    "Unfolding before our eyes,",
    "As expected,",
    "Surprisingly,",
    "A dramatic turn,",
    "Stay focused on the pack,",
  ],
};

export const EXPERT_INSIGHT_TEMPLATES = {
  POSITIVE_FORM: [
    "{horse} has been in sparkling form lately, looking to continue that today.",
    "Expect a big run from {horse} given their recent track record.",
    "Condition looks peak for {horse} as they load into the gates.",
    "The stable is buzzing about {horse}'s chances today.",
    "{horse} looks primed for a massive effort today based on morning work.",
    "{horse} comes into this race in absolute peak condition.",
    "You can't ignore the recent numbers {horse} has been putting up.",
    "Riding a wave of good form, {horse} is definitely a major threat.",
    "{horse} seems to be getting better with every start this campaign.",
    "It's hard to look past {horse} when they're running this well.",
    "The confidence behind {horse} is completely justified by their recent outings.",
    "{horse} is a picture of health and form heading into this contest.",
    "Everything points to a massive run from {horse} considering their current form.",
    "{horse} has hit a sweet spot in their campaign and looks very dangerous.",
    "You couldn't ask for {horse} to look any better than they do today.",
    "The momentum is entirely with {horse} right now.",
    "{horse} is flying at home and that form should translate perfectly today.",
    "If {horse} runs to their recent form, they are going to be very hard to beat.",
    "There are no concerns over {horse}'s current well-being, they look sensational.",
    "This is a horse at the absolute top of their game. Watch out for {horse}.",
  ],
  NEGATIVE_FORM: [
    "{horse} has struggled to find their best stride in recent starts.",
    "Looking for a bounce-back performance today from {horse}.",
    "Questions about the current fitness of {horse} after that last outing.",
    "This field might be a bit too deep for {horse} today.",
    "{horse} needs to show us a lot more after a string of disappointing efforts.",
    "The form line for {horse} has been a concern for the connections lately.",
    "It's been a tough campaign so far for {horse} as they try to find some rhythm.",
    "{horse} really needs to turn things around quickly with a good showing here.",
    "Confidence might be a bit low for {horse} coming into this one.",
    "We haven't seen the best of {horse} lately; they need to wake up today.",
    "{horse} looks to be struggling to recapture their earlier promise.",
    "It's hard to make a strong case for {horse} based on their recent starts.",
    "{horse} needs a sharp turnaround in form to feature today.",
    "We are hoping the real {horse} stands up today, because recent efforts have been poor.",
    "The current form of {horse} leaves a lot to be desired.",
    "{horse} is battling some form demons at the moment.",
    "It takes a leap of faith to back {horse} on current form.",
    "Connections of {horse} will be desperately hoping for a better showing this time.",
    "{horse} has been out of sorts lately and has plenty to prove.",
    "The jury is very much out on {horse} following some subpar recent runs.",
  ],
  DISTANCE_FIT: [
    "This {distance}m trip is right in the wheelhouse for {horse}.",
    "{horse} is a specialist at this distance.",
    "The distance shouldn't be an issue for {horse} today.",
    "Historically, {horse} excels at exactly this trip.",
    "{horse} will love every inch of this {distance}m journey.",
    "This {distance}m trip is where {horse} does their best work.",
    "A proven performer at {distance}m, {horse} is exactly where they want to be.",
    "{horse} has shown they can handle this {distance}m test with ease.",
    "The distance is perfect for {horse}'s natural running style.",
    "{horse} is uniquely suited to the demands of a {distance}m race.",
    "This trip is tailor-made for {horse}, giving them a distinct advantage.",
    "We know {horse} relishes a {distance}m challenge, so expect a bold showing.",
    "Over {distance}m, {horse} rarely puts a foot wrong.",
    "The {distance}m test is where {horse} finds their absolute best.",
    "{horse} is in their element over {distance}m.",
    "This field is on notice: {distance}m is {horse}'s preferred battleground.",
    "You know exactly what you'll get from {horse} at {distance}m.",
    "The statistics speak for themselves for {horse} over {distance}m.",
    "{horse} should relish every part of this {distance}m assignment.",
    "Over this specific trip of {distance}m, {horse} commands total respect.",
  ],
  NEW_DISTANCE: [
    "First time at {distance}m for {horse}, a real test of stamina.",
    "Testing the waters at this trip today with {horse}.",
    "Will {horse} see out the full {distance}m? We're about to find out.",
    "A major question mark over {horse} stepping up to this distance.",
    "Stepping into unknown territory today over {distance}m for {horse}.",
    "The big question is whether {horse} has the tank for this {distance}m.",
    "It's an ambitious ask to run {distance}m for the very first time, but {horse} tries today.",
    "Can {horse} handle the transition to {distance}m? The pedigree suggests maybe.",
    "We're going to learn a lot about {horse}'s versatility at this new {distance}m trip.",
    "Uncharted waters for {horse} at {distance}m, they'll need every ounce of grit.",
    "{horse} steps into the great unknown trying {distance}m for the first time.",
    "It's a gamble running {horse} at {distance}m today, let's see if it pays off.",
    "A fascinating move by connections to try {horse} over {distance}m today.",
    "We are in wait-and-see mode with {horse} at this new {distance}m trip.",
    "If {horse} can stretch out to {distance}m, they become a very interesting proposition.",
    "The big unknown today is whether {horse} stays the {distance}m.",
    "Tackling {distance}m for the first time is no easy feat, but {horse} looks ready.",
    "Can the speed of {horse} carry them over the full {distance}m?",
    "A real roll of the dice stepping {horse} out to {distance}m.",
    "The pedigree points to {horse} handling {distance}m, but today is the acid test.",
  ],
};

export const TEMPLATES: Record<NarrativeEvent, string[]> = {
  START: [
    "And they're off in the {raceName}!",
    "The gates are open and they're away!",
    "A clean start for the field in this {raceClass}!",
    "They break cleanly from the gates at {trackName}!",
    "A perfect dispatch for the {raceClass}!",
    "They're racing in the {raceName}!",
    "A smooth break for the runners in this {raceClass}.",
    "The flag drops and they're off at {trackName}!",
    "They burst out of the stalls for the {raceName}!",
    "It's a level start for this {raceClass} field!",
    "Underway in the {raceName}!",
    "The flag is down and we are racing!",
    "They've left the stalls in the {raceName}!",
    "A level break for all runners today!",
    "We're underway in this highly anticipated {raceClass}!",
    "The starter lets them go at {trackName}!",
  ],
  LEAD_CHANGE: [
    "{horse} takes the lead!",
    "{horse} moves to the front!",
    "{horse} has surged into the lead!",
    "New leader! It's {horse} taking control.",
    "{horse} stick's their nose in front!",
    "A bold move by {horse} to grab the initiative!",
    "{horse} is bossing the field now from the front!",
    "The {stable} runner {horse} has found the lead!",
    "It's {horse} who strikes the front now!",
    "{horse} wrests the lead away!",
    "A new pacemaker emerges as {horse} goes to the front.",
    "{horse} pushes past them to take the advantage!",
    "They're chasing {horse} now!",
    "{horse} strikes the front with a burst of speed!",
    "The lead changes hands, {horse} is the new leader!",
    "Taking command of the race, it's {horse}!",
  ],
  SURGE: [
    "{horse} is making a move!",
    "{horse} is finding another gear!",
    "Watch {horse} go! They're gaining ground fast.",
    "{horse} is picking up the pace!",
    "{horse} is accelerating through the field!",
    "The {coat} {gender} {horse} is really starting to motor!",
    "{horse} is weaving through traffic like they're standing still!",
    "{horse} finds a gap on the rail and explodes through!",
    "Going around the outside, it's {horse} flying!",
    "{horse} is putting in a massive run right now!",
    "Here comes {horse} with a sustained burst of speed!",
    "{horse} slices through the pack with ease!",
    "A scintillating move from {horse}!",
    "{horse} is gobbling up the ground!",
    "Look at the acceleration from {horse}!",
    "{horse} starts to roll on the outside!",
  ],
  FADE: [
    "{horse} is starting to tire.",
    "{horse} is losing ground.",
    "{horse} is dropping back now.",
    "{horse} can't keep up with this pace.",
    "The early effort is telling on {horse}.",
    "{horse} looks to be hitting a wall here.",
    "{horse} is being left behind as the pace quickens.",
    "Losing touch with the pack, {horse} is in trouble.",
    "{horse} is retreating through the field.",
    "The tank looks empty for {horse}.",
    "{horse} is struggling to maintain their position.",
    "They are swamping {horse} right now.",
    "{horse} has run their race and is backing up.",
    "It's a rapid retreat from {horse}.",
    "{horse} is dropping out of contention.",
  ],
  STRETCH: [
    "They're turning for home in the {raceName}!",
    "Into the final stretch!",
    "The wire is in sight!",
    "Final furlong! Who's got the legs?",
    "Down the stretch they come!",
    "It's a battle to the wire!",
    "The crowd is on its feet as they hit the straight!",
    "Ears pinned back, they're sprinting for home!",
    "They make the final turn in the {raceName}!",
    "The long drive for home begins now!",
    "It's a sprint to the finish in the {raceName}!",
    "They've hit the top of the straight!",
    "Every jockey asking for maximum effort now!",
    "The whips are out as they drive for the finish!",
    "The field straightens for the final drive!",
    "It's a desperate drive to the line now!",
    "Who wants this {raceName} the most?",
    "A true test of stamina awaits them in the stretch!",
  ],
  FINISH: [
    "{horse} wins it!",
    "It's {horse} at the wire!",
    "{horse} takes the victory!",
    "A brilliant finish for {horse}!",
    "What a performance by {horse} to take the {raceName}!",
    "He's done it! {horse} is the winner!",
    "A photo finish! But {horse} looks to have it!",
    "{horse} crosses the wire in first!",
    "A spectacular win for {horse}!",
    "{horse} takes the honors in the {raceName}!",
    "Nobody can catch {horse} today!",
    "It's all {horse} at the finish line!",
    "A masterclass performance from {horse} to win it!",
    "{horse} strikes gold in the {raceName}!",
    "A memorable victory for {horse}!",
    "An absolute masterclass from {horse} today!",
    "{horse} claims the prize with authority!",
    "Nobody was catching {horse} in this form!",
    "A gutsy, hard-fought triumph for {horse}!",
    "{horse} secures the glory in the shadow of the post!",
  ],
  POSITION_CHECK: [
    "{horse} is running well in {rank}.",
    "In {rank} place, it's {horse}.",
    "{horse} holds steady in {rank}.",
    "{horse} is currently in {rank}.",
    "Tracking the leaders in {rank} is {horse}.",
    "{horse} is biding their time in {rank}.",
    "A comfortable {rank} for {horse} at this stage.",
    "{horse} is travelling nicely in {rank} position.",
    "No panic from {horse}, settled in {rank}.",
    "The {coat} {gender} is cruising along in {rank}.",
    "{horse} finds a rhythm in {rank} spot.",
    "Steady as she goes for {horse} in {rank}.",
    "{horse} is holding their ground nicely in {rank}.",
    "Settled into a good rhythm in {rank} is {horse}.",
    "{horse} looks completely relaxed in {rank}.",
    "Nothing changing for {horse}, maintaining {rank} place.",
  ],
  DRAFTING: [
    "{horse} is tucked in behind {other}, saving ground.",
    "{horse} finds a nice slipstream behind {other}.",
    "Smart riding by {horse}, drafting behind {other}.",
    "{horse} is biding their time in the pocket.",
    "Conserving energy, {horse} is glued to the back of {other}.",
    "{horse} is getting a lovely tow behind {other}.",
    "Box-seat position for {horse} just off the heels of {other}.",
    "{horse} is enjoying the cover provided by {other}.",
    "Racing with economy, {horse} drafts behind {other}.",
    "{horse} is perfectly placed in the wake of {other}.",
    "A textbook trip for {horse}, sheltered behind {other}.",
    "{horse} is saving every inch behind {other}.",
    "{horse} is getting a free ride behind {other}.",
    "Sitting patiently in the slipstream of {other} is {horse}.",
    "{horse} lets {other} do all the hard work up front.",
    "A smart tactical ride sees {horse} covered up behind {other}.",
  ],
  HOT_PACE: [
    "The pace is scorching early on!",
    "They're really flying out there!",
    "A very hot pace being set by the front-runners.",
    "Front-runners are battling hard for the lead.",
    "They're going at a suicidal clip in front!",
    "The early fractions are blazing fast!",
    "This is a genuine burn-up in the early stages!",
    "The tempo is red-hot as they blaze along!",
    "Those early sectionals are eye-watering!",
    "The front-runners are setting a punishing pace!",
    "They're going faster than a runaway train up front!",
    "The pace is furious — someone will pay for this later!",
    "They are absolutely flying early doors!",
    "No prisoners being taken with this blistering pace!",
    "The speed they are showing is quite something!",
    "It's a genuine test of stamina with this early tempo!",
  ],
  WEATHER_COMMENT: [
    "The {weather} conditions might favor the stayers today.",
    "It's a {weather} day at the track, surface is {trackCondition}.",
    "The track is {trackCondition}, which will test their mettle.",
    "Conditions are perfect for a fast time today.",
    "The {weather} is playing havoc with the going.",
    "A {trackCondition} surface adds an extra layer of complexity today.",
    "The {weather} won't bother the mudlarks in this field.",
    "Under {weather} skies, the track is riding {trackCondition}.",
    "The ground is {trackCondition} — expect a tactical race.",
    "With the weather being {weather}, stamina will be at a premium.",
    "The {weather} could shake things up on this {trackCondition} surface.",
    "It's a testing {trackCondition} track under {weather} conditions.",
    "The {weather} skies loom over this {trackCondition} surface.",
    "It's a beautiful {weather} day for racing on a {trackCondition} track.",
    "The {trackCondition} ground under these {weather} conditions is a true test.",
    "We have {weather} weather today, setting the stage on this {trackCondition} surface.",
  ],
  STABLE_WATCH: [
    "Keep an eye on the {stable} runner, {horse}.",
    "{stable} will be hoping for a big run from {horse} here.",
    "{horse} carrying the famous {stable} colors.",
    "The {stable} team looks confident with {horse} today.",
    "{stable} has {horse} primed for a big performance.",
    "The {stable} silks are flying on {horse} today.",
    "{horse} is the pride of the {stable} string.",
    "Big expectations from the {stable} camp for {horse}.",
    "{stable} sends {horse} into battle with high hopes.",
    "The {stable} operation has {horse} peaking at the right time.",
    "All eyes on {horse} from the powerful {stable} stable.",
    "{horse} is flying the flag for {stable} in this one.",
    "{stable} is well-represented here by {horse}.",
    "The familiar silks of {stable} are carried by {horse}.",
    "{horse} looks a picture of health for the {stable} yard.",
    "A major player for the {stable} operation today is {horse}.",
  ],
  MILESTONE: [
    "Passing the halfway point now.",
    "Only {remaining}m to go in the {raceName}.",
    "They've got {remaining}m left to find a winner.",
    "Entering the final 400 meters!",
    "They're inside the final 100! Who wants it more?",
    "We're at the halfway marker — time to make a move.",
    "The halfway point is behind them, {remaining}m remains.",
    "Into the final 400m — the pressure is building!",
    "Just {remaining}m standing between them and glory.",
    "The business end of the race is here with {remaining}m left.",
    "They're running out of real estate — only {remaining}m to go!",
    "The crowd rises as they pass the halfway point in the {raceName}.",
    "They've reached the midpoint of the journey.",
    "The halfway stage is upon us in the {raceName}.",
    "It's time to get serious as they pass the halfway mark.",
    "With {remaining}m remaining, the tactics begin to unfold.",
  ],
  EXPERT_INSIGHT: [],
  GAP_ANNOUNCEMENT: [
    "{horse} is leading by {lengths} lengths!",
    "{horse} has a {lengths} length advantage at the front.",
    "{horse} is pulling away! The gap is now {lengths} lengths.",
    "A dominant display from {horse}, clear by {lengths}!",
    "{horse} is absolutely bounding away, a {lengths} length margin!",
    "The rest of the field is struggling to close a {lengths} length gap!",
    "{horse} has opened up a commanding {lengths} length lead!",
    "Look at the separation! {horse} is out by {lengths} lengths!",
    "A chasm has opened up! {horse} leads by {lengths} lengths.",
    "{horse} is putting on a clinic, clear by {lengths} lengths!",
    "It's a one-horse race right now, {horse} leads by {lengths}!",
    "They can't get near {horse}, the margin is {lengths} lengths.",
    "{horse} extends the advantage to {lengths} lengths!",
    "Nobody is going with {horse}, now {lengths} lengths in front.",
    "A sprawling {lengths} length lead for {horse}!",
    "{horse} says 'catch me if you can' with a {lengths} length gap!",
  ],
  ATMOSPHERE: [
    "The roar of the crowd is deafening!",
    "A tense atmosphere here at {trackName}.",
    "The anticipation is palpable as they round the turn.",
    "Every jockey is looking for that winning opening.",
    "The grandstand is buzzing with excitement!",
    "You could cut the tension with a knife at {trackName}.",
    "The crowd is on the edge of their seats!",
    "A thrilling atmosphere envelops the course.",
    "The noise is incredible as they sweep around the bend.",
    "Fans are on their feet as the drama unfolds!",
    "The electric atmosphere at {trackName} is something special.",
    "A deafening roar goes up from the packed stands!",
    "The energy in the grandstand is absolutely electric!",
    "Cheers echo across {trackName} as the field battles on.",
    "A collective gasp goes up from the spectators!",
    "The spectators are bringing the noise today!",
    "It's a wall of sound from the rail to the rafters!",
    "The stakes are high and the crowd knows it!",
    "Every eye at the track is glued to the action.",
    "The roar from the grandstand is shaking the ground!",
    "You can feel the electricity in the air today.",
    "The passionate crowd at {trackName} is loving this!",
    "What a spectacle we have unfolding before us!",
    "The atmosphere is at fever pitch!",
  ],
  LANE_WATCH: [
    "{horse} is caught wide on the turn, covering a lot of extra ground!",
    "Looking for the rail, but {horse} is trapped out three-wide.",
    "A tough trip for {horse}, parked out wide without cover.",
    "The jockey on {horse} is trying to tuck in, but the rail is packed.",
    "{horse} is burning fuel out there, racing wide on the bend.",
    "No cover for {horse} — they're doing it the hard way.",
    "{horse} is three-deep without a friend in sight.",
    "The wide trip is costing {horse} valuable ground.",
    "{horse} is out in the car park, covering extra distance.",
    "Stuck on the fence with nowhere to go, {horse} is boxed in.",
    "{horse} is navigating a tricky path on the outside.",
    "The jockey is working overtime to get {horse} out of trouble.",
    "{horse} is caught out on a limb here.",
    "A difficult passage for {horse}, racing without cover.",
    "{horse} is forced to take the overland route today.",
    "The jockey on {horse} is struggling to find a position near the rail.",
  ],
};
