/**
 * archetypeOriginal.ts - Original 8 breeding archetypes
 *
 * Extracted from archetypes.ts for modularity.
 */

import type { Archetype } from "./archetypeTypes";

export const ORIGINAL_ARCHETYPES: Archetype[] = [
  {
    id: "elite-turf-stayer",
    name: "Elite Turf Stayer",
    description:
      "High stamina for long turf races, balanced speed/stamina, surface Turf, style S/P",
    targetPhenotype: {
      speed: 0.7,
      stamina: 0.9,
      acceleration: 0.6,
      consistency: 0.8,
      distance: 2400,
      surface: "Turf",
      trainability: 0.7,
      durability: 0.8,
      peakAge: 4,
    },
    weights: { speed: 0.2, stamina: 0.4, acceleration: 0.1, consistency: 0.3 },
  },
  {
    id: "dirt-sprinter",
    name: "Dirt Sprinter",
    description: "High speed, fiber sprinter, distance ≤1200m, surface Dirt",
    targetPhenotype: {
      speed: 0.9,
      stamina: 0.5,
      acceleration: 0.85,
      consistency: 0.7,
      distance: 1000,
      surface: "Dirt",
      trainability: 0.6,
      durability: 0.6,
      peakAge: 3,
    },
    weights: { speed: 0.5, stamina: 0.1, acceleration: 0.3, consistency: 0.1 },
  },
  {
    id: "classic-miler",
    name: "Classic Miler",
    description: "Balanced speed/stamina, distance 1600m, versatile surface",
    targetPhenotype: {
      speed: 0.8,
      stamina: 0.75,
      acceleration: 0.75,
      consistency: 0.75,
      distance: 1600,
      surface: "Versatile",
      trainability: 0.7,
      durability: 0.7,
      peakAge: 3,
    },
    weights: { speed: 0.3, stamina: 0.3, acceleration: 0.2, consistency: 0.2 },
  },
  {
    id: "turf-specialist",
    name: "Turf Specialist",
    description: "High acceleration, cornering, climbing, surface Turf",
    targetPhenotype: {
      speed: 0.7,
      stamina: 0.7,
      acceleration: 0.85,
      consistency: 0.8,
      distance: 1800,
      surface: "Turf",
      trainability: 0.75,
      durability: 0.7,
      peakAge: 4,
    },
    weights: { speed: 0.25, stamina: 0.25, acceleration: 0.35, consistency: 0.15 },
  },
  {
    id: "iron-horse",
    name: "Iron Horse",
    description: "High durability, recovery, consistency, low health risk",
    targetPhenotype: {
      speed: 0.6,
      stamina: 0.7,
      acceleration: 0.6,
      consistency: 0.9,
      distance: 2000,
      surface: "Versatile",
      trainability: 0.7,
      durability: 0.95,
      peakAge: 5,
    },
    weights: { speed: 0.15, stamina: 0.25, acceleration: 0.1, consistency: 0.5 },
  },
  {
    id: "early-developer",
    name: "Early Developer",
    description: "Low peakAge, high acceleration, sprinter/miler",
    targetPhenotype: {
      speed: 0.8,
      stamina: 0.6,
      acceleration: 0.85,
      consistency: 0.7,
      distance: 1200,
      surface: "Versatile",
      trainability: 0.8,
      durability: 0.6,
      peakAge: 2,
    },
    weights: { speed: 0.35, stamina: 0.15, acceleration: 0.35, consistency: 0.15 },
  },
  {
    id: "late-bloomer",
    name: "Late Bloomer",
    description: "High peakAge, stamina dominant, trainability",
    targetPhenotype: {
      speed: 0.6,
      stamina: 0.9,
      acceleration: 0.6,
      consistency: 0.75,
      distance: 2400,
      surface: "Versatile",
      trainability: 0.8,
      durability: 0.75,
      peakAge: 6,
    },
    weights: { speed: 0.15, stamina: 0.5, acceleration: 0.1, consistency: 0.25 },
  },
  {
    id: "all-weather",
    name: "All-Weather",
    description: "Versatile surface, balanced stats, high mental",
    targetPhenotype: {
      speed: 0.75,
      stamina: 0.75,
      acceleration: 0.75,
      consistency: 0.8,
      distance: 1600,
      surface: "Synthetic",
      trainability: 0.7,
      durability: 0.7,
      peakAge: 4,
    },
    weights: { speed: 0.25, stamina: 0.25, acceleration: 0.25, consistency: 0.25 },
  },
];
