/**
 * eliteStablePool.ts - Elite stable pool data
 *
 * Extracted from stablePoolData.ts for modularity.
 */

import type { StablePoolEntry } from "./stablePoolData";

export const ELITE_POOL: StablePoolEntry[] = [
  {
    name: "Coolmore Stud",
    owner: "Magnier Family",
    isMajor: true,
    colors: { primary: "#1a472a", secondary: "#ffffff" },
    description:
      "Irish breeding powerhouse dominating European racing for decades. Home of Galileo and descendants.",
    country: "Ireland",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Godolphin",
    owner: "Sheikh Mohammed",
    isMajor: true,
    colors: { primary: "#0066cc", secondary: "#ffffff" },
    description:
      "Dubai-based global racing operation with strings across five continents. The world's largest racing stable.",
    country: "UAE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Juddmonte Farms",
    owner: "Prince Khalid Abdullah",
    isMajor: true,
    colors: { primary: "#4a0080", secondary: "#ffd700" },
    description: "Saudi-owned American and European operation famous for Frankel and Enable.",
    country: "USA/UK",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "WinStar Farm",
    owner: "Kenny Troutt",
    isMajor: true,
    colors: { primary: "#006400", secondary: "#daa520" },
    description: "Kentucky mega-stable producing Kentucky Derby winners and champion stallions.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Klaravich Stables",
    owner: "Seth Klarman",
    isMajor: true,
    colors: { primary: "#8b0000", secondary: "#ffffff" },
    description: "New York-based operation with graded stakes success across the Americas.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Gainsborough Farm",
    owner: "Maktoum Family",
    isMajor: true,
    colors: { primary: "#228b22", secondary: "#ffd700" },
    description:
      "Historic Kentucky nursery with classic winners and influence on American bloodlines.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Sackatoga Stable",
    owner: "Jack Knowlton",
    isMajor: true,
    colors: { primary: "#ff8c00", secondary: "#000000" },
    description: "New York partnership famous for Tiz the Law and Saratoga success stories.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Skull Stable",
    owner: "Hugo Merry",
    isMajor: true,
    colors: { primary: "#000000", secondary: "#ffffff" },
    description: "Australian operation making waves in Asian and Australian racing circuits.",
    country: "Australia",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "AMO Racing",
    owner: "Amit Singh",
    isMajor: true,
    colors: { primary: "#dc143c", secondary: "#ffd700" },
    description: "British-based syndicate targeting European pattern races and Royal Ascot.",
    country: "UK",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "China Horse Club",
    owner: "Teo Ah Khing",
    isMajor: true,
    colors: { primary: "#ff0000", secondary: "#ffd700" },
    description: "Asian powerhouse with global reach, breeding and racing worldwide.",
    country: "China/International",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Shadai Stallion Station",
    owner: "Yoshida Family",
    isMajor: true,
    colors: { primary: "#000080", secondary: "#ffffff" },
    description:
      "Japanese breeding powerhouse home of Deep Impact, Sunday Silence, and Japanese Triple Crown winners.",
    country: "Japan",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Spendthrift Farm",
    owner: "B. Wayne Hughes",
    isMajor: true,
    colors: { primary: "#000000", secondary: "#ffd700" },
    description:
      "Kentucky stud farm home of Into Mischief, Omaha Beach, and other champion stallions.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Ashford Stud",
    owner: "Coolmore",
    isMajor: true,
    colors: { primary: "#1a472a", secondary: "#ffffff" },
    description:
      "Coolmore's Kentucky operation standing Justify, Uncle Mo, and other elite stallions.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Gainesway Farm",
    owner: "Gainesway Farm LLC",
    isMajor: true,
    colors: { primary: "#191970", secondary: "#c0c0c0" },
    description: "Kentucky farm home of Tapit, Quality Road, and leading sires.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Three Chimneys Farm",
    owner: "Three Chimneys Farm",
    isMajor: true,
    colors: { primary: "#4b0082", secondary: "#ffd700" },
    description: "Kentucky farm standing Gun Runner, Candy Ride, and champion stallions.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Hill 'n' Dale Farms",
    owner: "Hill 'n' Dale Farms",
    isMajor: true,
    colors: { primary: "#800000", secondary: "#ffffff" },
    description: "Kentucky farm home of Curlin and other champion racehorses.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Lane's End",
    owner: "Farish Family",
    isMajor: true,
    colors: { primary: "#006400", secondary: "#ffffff" },
    description: "Kentucky farm standing Liam's Map, Twirling Candy, and quality stallions.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Claiborne Farm",
    owner: "Hancock Family",
    isMajor: true,
    colors: { primary: "#8b0000", secondary: "#ffd700" },
    description: "Historic Kentucky nursery with over 100 years of breeding excellence.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
];
