/**
 * midStablePool.ts - Mid-tier stable pool data
 *
 * Extracted from stablePoolData.ts for modularity.
 */

import type { StablePoolEntry } from "./stablePoolData";

export const MID_POOL: StablePoolEntry[] = [
  {
    name: "Team Valor",
    owner: "Barry Irwin",
    isMajor: true,
    colors: { primary: "#4169e1", secondary: "#ff0000" },
    description:
      "International partnership stable famous for Animal Kingdom and Kentucky Derby victories.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Reddam Racing",
    owner: "Paul Reddam",
    isMajor: true,
    colors: { primary: "#dc143c", secondary: "#ffffff" },
    description: "California-based operation with multiple Breeders' Cup and Kentucky Derby wins.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Churchill Downs Stables",
    owner: "Bradley Racing",
    isMajor: true,
    colors: { primary: "#8b4513", secondary: "#ffd700" },
    description: "Kentucky operation with deep ties to the track and consistent stakes performers.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Phoenix Thoroughbreds",
    owner: "Amer Abdulaziz",
    isMajor: true,
    colors: { primary: "#ff4500", secondary: "#000000" },
    description: "International investment fund with horses across Europe, America, and Australia.",
    country: "International",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Al Shaqab Racing",
    owner: "Qatar Royal Family",
    isMajor: true,
    colors: { primary: "#800080", secondary: "#ffd700" },
    description: "Qatari operation with strong presence in European turf racing and breeding.",
    country: "Qatar",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Shadwell Estate",
    owner: "Hamdan Al Maktoum",
    isMajor: true,
    colors: { primary: "#0000cd", secondary: "#ffffff" },
    description: "British breeding and racing operation with global influence and classic winners.",
    country: "UK",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Sunday Silence Ltd",
    owner: "Masayoshi Son",
    isMajor: true,
    colors: { primary: "#ff8c00", secondary: "#000000" },
    description: "Japanese breeding empire built on the legendary stallion Sunday Silence.",
    country: "Japan",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Moyglare Stud",
    owner: "Evlanoff Family",
    isMajor: true,
    colors: { primary: "#228b22", secondary: "#ffffff" },
    description: "Historic Irish breeding operation producing classic winners for over 50 years.",
    country: "Ireland",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Rathbarry Stud",
    owner: "Noreen O'Callaghan",
    isMajor: true,
    colors: { primary: "#8b0000", secondary: "#ffd700" },
    description: "Irish farm known for nurturing champions and successful broodmare band.",
    country: "Ireland",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Gestut Fahrhof",
    owner: "von Schroeder Family",
    isMajor: true,
    colors: { primary: "#191970", secondary: "#c0c0c0" },
    description: "German breeding nursery with influence across European racing.",
    country: "Germany",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Ecurie Pierre-Etienne",
    owner: "Pierre-Etienne Dubois",
    isMajor: true,
    colors: { primary: "#000080", secondary: "#ffffff" },
    description: "French operation with consistent success in Parisian tracks and Arc trials.",
    country: "France",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Arrowfield Stud",
    owner: "Ingham Family",
    isMajor: true,
    colors: { primary: "#006400", secondary: "#ffd700" },
    description: "Australian powerhouse with Champion Sires and Golden Slipper winners.",
    country: "Australia",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Newgate Farm",
    owner: "Henry Field",
    isMajor: true,
    colors: { primary: "#4b0082", secondary: "#ffffff" },
    description: "Australian farm producing champion stallions and racehorses.",
    country: "Australia",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Yulong Investments",
    owner: "Zhang Yuesheng",
    isMajor: true,
    colors: { primary: "#ff6347", secondary: "#ffd700" },
    description: "Chinese-Australian operation acquiring top bloodstock worldwide.",
    country: "China/Australia",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Silk Racing",
    owner: "Australian Syndicate",
    isMajor: true,
    colors: { primary: "#800000", secondary: "#ffffff" },
    description: "Micro-share racing syndicate making ownership accessible to thousands.",
    country: "Australia",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Airdrie Stud",
    owner: "B. Wayne Hughes",
    isMajor: true,
    colors: { primary: "#000080", secondary: "#ffd700" },
    description: "Kentucky farm known for quality stallions and broodmares.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Stone Farm",
    owner: "Stone Farm",
    isMajor: true,
    colors: { primary: "#556b2f", secondary: "#ffffff" },
    description: "Kentucky farm with history of producing graded stakes winners.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Vinery",
    owner: "Vinery",
    isMajor: true,
    colors: { primary: "#8b4513", secondary: "#ffd700" },
    description: "Kentucky breeding operation with international influence.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Yarraman Park",
    owner: "Arthur Mitchell",
    isMajor: true,
    colors: { primary: "#ff6347", secondary: "#000000" },
    description: "Australian home of I Am Invincible, champion sire.",
    country: "Australia",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Haras La Quebrada",
    owner: "Haras La Quebrada",
    isMajor: true,
    colors: { primary: "#006633", secondary: "#ffd700" },
    description: "Brazilian breeding operation producing South American champions.",
    country: "Brazil",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Haras Vacacion",
    owner: "Haras Vacacion",
    isMajor: true,
    colors: { primary: "#dc143c", secondary: "#ffffff" },
    description: "Chilean breeding farm known for quality stallions.",
    country: "Chile",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Northern Farm",
    owner: "Northern Farm",
    isMajor: true,
    colors: { primary: "#000080", secondary: "#ffffff" },
    description: "Japanese breeding operation home of Contrail and other champions.",
    country: "Japan",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Bizenn Ranch",
    owner: "Bizenn Ranch",
    isMajor: true,
    colors: { primary: "#4b0082", secondary: "#ffd700" },
    description: "Japanese breeding farm with quality bloodlines.",
    country: "Japan",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Newsells Park Stud",
    owner: "Newsells Park Stud",
    isMajor: true,
    colors: { primary: "#1a472a", secondary: "#ffd700" },
    description: "British stud farm standing champion stallions.",
    country: "UK",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Banstead Manor Stud",
    owner: "Banstead Manor Stud",
    isMajor: true,
    colors: { primary: "#800000", secondary: "#ffffff" },
    description: "British stud farm home of Frankel's son Cracksman.",
    country: "UK",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Cheveley Park Stud",
    owner: "Cheveley Park Stud",
    isMajor: true,
    colors: { primary: "#191970", secondary: "#c0c0c0" },
    description: "British breeding operation with quality mares and stallions.",
    country: "UK",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Haras du Logis",
    owner: "Haras du Logis",
    isMajor: true,
    colors: { primary: "#006633", secondary: "#ffffff" },
    description: "French breeding operation home of champion sires and classic winners.",
    country: "France",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Taylor Made Farm",
    owner: "Taylor Made Farm",
    isMajor: true,
    colors: { primary: "#000080", secondary: "#ffd700" },
    description: "Kentucky farm known for quality stallions and innovative breeding programs.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Calumet Farm",
    owner: "Calumet Farm",
    isMajor: true,
    colors: { primary: "#8b0000", secondary: "#ffd700" },
    description: "Historic Kentucky nursery with multiple Triple Crown winners.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Ramsey Farm",
    owner: "Ramsey Farm",
    isMajor: true,
    colors: { primary: "#556b2f", secondary: "#ffffff" },
    description: "Kentucky farm specializing in turf horses and international runners.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Summerhill Stud",
    owner: "Summerhill Stud",
    isMajor: true,
    colors: { primary: "#ff6347", secondary: "#000000" },
    description: "South African breeding powerhouse producing champions across the continent.",
    country: "South Africa",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Hong Kong Jockey Club",
    owner: "Hong Kong Jockey Club",
    isMajor: true,
    colors: { primary: "#ff0000", secondary: "#ffffff" },
    description: "Hong Kong's premier racing and breeding operation.",
    country: "Hong Kong",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Allevamento di Besnate",
    owner: "Allevamento di Besnate",
    isMajor: true,
    colors: { primary: "#0066cc", secondary: "#ffd700" },
    description: "Italian breeding operation producing classic winners.",
    country: "Italy",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Gestut Isarland",
    owner: "Gestut Isarland",
    isMajor: true,
    colors: { primary: "#191970", secondary: "#c0c0c0" },
    description: "German breeding operation with international influence.",
    country: "Germany",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
];
