/**
 * secondaryStablePool.ts - Secondary (regional) named stable pool
 *
 * Real-feeling named yards used to fill out the world beyond the headline
 * elite/mid/budget pools, so the Exchange and Auction Houses are populated by
 * many distinct stables rather than a handful of big operations.
 *
 * Dependencies: ./stablePoolData (StablePoolEntry)
 * Related files: stables.ts (generation), stableConfig.ts (counts)
 */

import type { StablePoolEntry } from "./stablePoolData";

export const SECONDARY_POOL: StablePoolEntry[] = [
  {
    name: "Ashbourne Park",
    owner: "Miriam Ashbourne",
    isMajor: false,
    colors: { primary: "#1f4e79", secondary: "#f2c14e" },
    description: "Limestone-country yard with a knack for tough middle-distance sorts.",
    country: "IRE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Kellermann Gestüt",
    owner: "Anton Kellermann",
    isMajor: false,
    colors: { primary: "#2e2e38", secondary: "#c0392b" },
    description: "Disciplined German operation breeding for stamina and soundness.",
    country: "GER",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Brackenhill Stud",
    owner: "Rowan Brackley",
    isMajor: false,
    colors: { primary: "#37613c", secondary: "#e8e2d0" },
    description: "Yorkshire hill yard famed for hardy staying types.",
    country: "GBR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Marisol Racing",
    owner: "Elena Marisol",
    isMajor: false,
    colors: { primary: "#7b2d43", secondary: "#f7e7ce" },
    description: "Chantilly-based string with a fondness for soft-ground milers.",
    country: "FRA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Coolagh Bloodstock",
    owner: "Declan Coolagh",
    isMajor: false,
    colors: { primary: "#0b6e4f", secondary: "#ffd166" },
    description: "Trading yard that pinhooks yearlings across two hemispheres.",
    country: "IRE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Ridgeway Farms",
    owner: "Walter Ridge",
    isMajor: false,
    colors: { primary: "#14213d", secondary: "#fca311" },
    description: "Kentucky family farm built on patient two-year-old education.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Sable Creek Racing",
    owner: "Jolene Hart",
    isMajor: false,
    colors: { primary: "#3d348b", secondary: "#f7b801" },
    description: "Dirt-oriented barn chasing allowance-to-stakes progressions.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Nakagawa Racing",
    owner: "Sho Nakagawa",
    isMajor: false,
    colors: { primary: "#8d0801", secondary: "#ffffff" },
    description: "Ritto operation with precise, data-led training regimes.",
    country: "JPN",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Higashiyama Farm",
    owner: "Rika Higashiyama",
    isMajor: false,
    colors: { primary: "#1b3a4b", secondary: "#f2e9e4" },
    description: "Hokkaido nursery producing tough turf performers.",
    country: "JPN",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Barrowfield Lodge",
    owner: "Cormac Neale",
    isMajor: false,
    colors: { primary: "#4a5859", secondary: "#f4d35e" },
    description: "Traditional lodge that never sells a horse cheaply.",
    country: "IRE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Whitmore & Sons",
    owner: "Gerald Whitmore",
    isMajor: false,
    colors: { primary: "#5c374c", secondary: "#dcd6f7" },
    description: "Old-school Newmarket family firm with deep owner ties.",
    country: "GBR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Silvergate Stables",
    owner: "Priya Anand",
    isMajor: false,
    colors: { primary: "#2a4494", secondary: "#c7d3ff" },
    description: "Ambitious newcomer buying aggressively at the breeze-ups.",
    country: "GBR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Alto Pampas",
    owner: "Mateo Ferreyra",
    isMajor: false,
    colors: { primary: "#0f5257", secondary: "#f6ae2d" },
    description: "Argentine yard exporting hardy dirt milers.",
    country: "ARG",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Estancia del Sol",
    owner: "Camila Reyes",
    isMajor: false,
    colors: { primary: "#b23a48", secondary: "#fcb9b2" },
    description: "Sun-baked estancia with a strong broodmare band.",
    country: "ARG",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Karoo Thoroughbreds",
    owner: "Pieter van Zyl",
    isMajor: false,
    colors: { primary: "#6a4c93", secondary: "#ffca3a" },
    description: "Cape operation known for sprinting speed.",
    country: "RSA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Yarra Bend Racing",
    owner: "Neil Cartwright",
    isMajor: false,
    colors: { primary: "#1982c4", secondary: "#8ac926" },
    description: "Victorian yard aimed squarely at spring carnivals.",
    country: "AUS",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Wattle Ridge Farm",
    owner: "Bree Donnelly",
    isMajor: false,
    colors: { primary: "#43aa8b", secondary: "#f9c74f" },
    description: "Country property developing staying types on the cheap.",
    country: "AUS",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Southern Star Lodge",
    owner: "Hemi Walker",
    isMajor: false,
    colors: { primary: "#264653", secondary: "#e9c46a" },
    description: "New Zealand lodge selling tried horses across the Tasman.",
    country: "NZL",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Falconridge Stable",
    owner: "Isabelle Faucher",
    isMajor: false,
    colors: { primary: "#3a015c", secondary: "#ffd6ff" },
    description: "Provincial French yard punching above its prize-money weight.",
    country: "FRA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Montclair Racing",
    owner: "Henri Montclair",
    isMajor: false,
    colors: { primary: "#22223b", secondary: "#c9ada7" },
    description: "Deauville-based string with a taste for black type.",
    country: "FRA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Dunmore Bay Stud",
    owner: "Aoife Dunmore",
    isMajor: false,
    colors: { primary: "#006d77", secondary: "#ffddd2" },
    description: "Coastal stud combining nursery and racing arms.",
    country: "IRE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Cedarcroft Farm",
    owner: "Marcus Bell",
    isMajor: false,
    colors: { primary: "#432818", secondary: "#ffe6a7" },
    description: "Maryland farm running a steady claiming operation.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Blue Ash Racing",
    owner: "Dana Whitfield",
    isMajor: false,
    colors: { primary: "#264a99", secondary: "#a2d2ff" },
    description: "Midwestern barn that flips horses quickly for profit.",
    country: "USA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Northgate Equine",
    owner: "Ivan Sorokin",
    isMajor: false,
    colors: { primary: "#1d3557", secondary: "#a8dadc" },
    description: "Northern yard specialising in all-weather handicappers.",
    country: "GBR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Verdant Hill Stables",
    owner: "Grace Okonkwo",
    isMajor: false,
    colors: { primary: "#386641", secondary: "#a7c957" },
    description: "Patient outfit that rarely runs a horse before it is ready.",
    country: "GBR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Rivermeade Racing",
    owner: "Sean Traynor",
    isMajor: false,
    colors: { primary: "#3c096c", secondary: "#e0aaff" },
    description: "Buys stores and sells on once they show ability.",
    country: "IRE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Steinbach Rennstall",
    owner: "Lena Steinbach",
    isMajor: false,
    colors: { primary: "#354f52", secondary: "#cad2c5" },
    description: "Cologne stable with a strong classic-trial record.",
    country: "GER",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Villa Ferrante",
    owner: "Giulio Ferrante",
    isMajor: false,
    colors: { primary: "#780000", secondary: "#fdf0d5" },
    description: "Italian yard with a long Group-race tradition.",
    country: "ITA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Costa Bianca",
    owner: "Paola Rinaldi",
    isMajor: false,
    colors: { primary: "#457b9d", secondary: "#f1faee" },
    description: "Coastal Italian operation focused on sprint handicaps.",
    country: "ITA",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Kalmar Stuteri",
    owner: "Erik Lindqvist",
    isMajor: false,
    colors: { primary: "#0353a4", secondary: "#ffd60a" },
    description: "Scandinavian stud thriving on winter dirt racing.",
    country: "SWE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Fjordlys Racing",
    owner: "Ingrid Halvorsen",
    isMajor: false,
    colors: { primary: "#1b4965", secondary: "#bee9e8" },
    description: "Small Nordic string with excellent horse welfare standards.",
    country: "NOR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Al Rukban Stables",
    owner: "Faisal Al Rukban",
    isMajor: false,
    colors: { primary: "#5f0f40", secondary: "#fb8b24" },
    description: "Gulf operation with deep pockets and quick trigger fingers.",
    country: "UAE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Desert Wind Racing",
    owner: "Nadia Haddad",
    isMajor: false,
    colors: { primary: "#0f4c5c", secondary: "#e36414" },
    description: "Dubai carnival specialists who buy proven form.",
    country: "UAE",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Maple Ridge Farm",
    owner: "Owen Leclair",
    isMajor: false,
    colors: { primary: "#9a031e", secondary: "#fff1e6" },
    description: "Ontario farm producing durable synthetic-track types.",
    country: "CAN",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Prairie Gold Racing",
    owner: "Kate Sandison",
    isMajor: false,
    colors: { primary: "#5f7470", secondary: "#f5cb5c" },
    description: "Modest western barn with a strong claiming eye.",
    country: "CAN",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
  {
    name: "Hollowfield Yard",
    owner: "Tomas Berger",
    isMajor: false,
    colors: { primary: "#6b705c", secondary: "#ffe8d6" },
    description: "Rural yard that quietly turns out consistent winners.",
    country: "GBR",
    staff: {
      veterinarian: null,
      farrier: null,
      nutritionist: null,
      groom: null,
      trainer: null,
    },
    outposts: [],
  },
];
