/**
 * resolver/impacts/inboxImpacts.ts - Inbox impact definitions
 *
 * This file provides impacts for pushing messages to the player's inbox
 * via the impact resolver.
 *
 * Dependencies: ./index (Impact), @/core/inbox/inboxTypes (InboxMessage)
 */

import type { Impact } from "./index";
import type { InboxMessage } from "@/core/inbox/inboxTypes";

/**
 * Impact to push a new message to the player's inbox.
 */
export interface InboxImpact extends Impact {
  type: "inbox_message";
  /** The message payload (ID and readAt are generated by the handler) */
  message: Omit<InboxMessage, "id" | "readAt">;
}
