/**
 * useRacePageData.fillerHorses.test.ts
 *
 * Integration test verifying that filler horses generated by buildRaceField
 * are spread into the NarrativeGenerator constructor so commentary about
 * filler runners has full horse context (pedigree, coat, stable, etc.).
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { renderHook } from "@testing-library/react";
import type { Horse, Race, Stable, Jockey } from "@/game/types";
import type { Runner } from "@/core/race/engine/runnerBuilder";

// ─── Mocks ───────────────────────────────────────────────────────────────────

const mockNarrativeGenerator = vi.fn();
vi.mock("@/services/narrative/narrativeService", () => ({
  NarrativeGenerator: vi.fn((...args: unknown[]) => {
    mockNarrativeGenerator(...args);
    return { update: () => [], getHistory: () => [] };
  }),
}));

vi.mock("@/services/race/raceSimulationService", () => ({
  buildRaceField: vi.fn(),
  rngForRace: vi.fn(() => ({ next: () => 0 })),
}));

vi.mock("@/core/odds", () => ({
  calculateWinProbability: vi.fn(() => 0.5),
  probabilityToMorningLine: vi.fn(() => 2),
  formatOdds: vi.fn((n: number) => `${n}-1`),
}));

vi.mock("@/core/common/classBonus", () => ({
  calculateClassBonus: vi.fn(() => 0),
}));

vi.mock("@/core/common/rng", () => ({
  createRng: vi.fn(() => ({ next: () => 0 })),
  hashStr: vi.fn(() => 0),
}));

vi.mock("@/constants/raceBroadcastConstants", () => ({
  NARRATIVE_RNG_XOR_MASK: 0x6e61,
}));

// Store mock — we control the return value per-test.
vi.mock("@/game/store", () => ({
  useGame: vi.fn((selector: (s: unknown) => unknown) => selector(mockState)),
  useGameWithShallow: vi.fn((selector: (s: unknown) => unknown) => selector(mockState)),
}));

// ─── Test Data ───────────────────────────────────────────────────────────────

let mockState: Record<string, unknown>;

const STORE_HORSE_A: Horse = {
  id: "store-a",
  name: "Alpha",
  coatColor: "bay",
  gender: "colt",
  sireName: "Sire A",
  damName: "Dam A",
  stableId: "stable-1",
  stats: { speed: 80, stamina: 75, acceleration: 70 } as never,
  form: 50,
  raceHistory: [],
} as unknown as Horse;

const FILLER_HORSE_B: Horse = {
  id: "filler-b",
  name: "Bravo",
  coatColor: "chestnut",
  gender: "filly",
  sireName: "Unknown Sire",
  damName: "Unknown Dam",
  stats: { speed: 70, stamina: 65, acceleration: 60 } as never,
  form: 40,
  raceHistory: [],
} as unknown as Horse;

const FILLER_HORSE_C: Horse = {
  id: "filler-c",
  name: "Charlie",
  coatColor: "grey",
  gender: "horse",
  sireName: "Another Sire",
  damName: "Another Dam",
  stats: { speed: 65, stamina: 70, acceleration: 55 } as never,
  form: 35,
  raceHistory: [],
} as unknown as Horse;

const RACE: Race = {
  id: "race-1",
  name: "Test Stakes",
  day: 1,
  distance: 1600,
  raceClass: "Allowance",
  fieldSize: 3,
  entries: [{ horseId: "store-a" } as never],
  resolved: false,
} as unknown as Race;

const STABLES: Stable[] = [{ id: "stable-1", name: "Test Stable" } as unknown as Stable];

const RUNNERS: Runner[] = [
  { horseId: "store-a", name: "Alpha", position: 0, velocity: 0, finishTime: null } as Runner,
  { horseId: "filler-b", name: "Bravo", position: 0, velocity: 0, finishTime: null } as Runner,
  { horseId: "filler-c", name: "Charlie", position: 0, velocity: 0, finishTime: null } as Runner,
];

// ─── Imports (after mocks) ───────────────────────────────────────────────────

import { useRacePageData } from "@/hooks/race/useRacePageData";
import { buildRaceField } from "@/services/race/raceSimulationService";
import { NarrativeGenerator } from "@/services/narrative/narrativeService";

// ─── Tests ───────────────────────────────────────────────────────────────────

describe("useRacePageData filler horse integration", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockState = {
      races: { "race-1": RACE },
      horses: { "store-a": STORE_HORSE_A },
      jockeys: [],
      npcStables: STABLES,
      hiredStaff: [],
      npcAIManager: null,
      day: 1,
      weather: { byTrack: {} },
      calibratedPars: {},
      resolveRaceWithImpacts: vi.fn(),
    };
  });

  it("passes filler horses to NarrativeGenerator constructor alongside store horses", () => {
    vi.mocked(buildRaceField).mockReturnValue({
      runners: RUNNERS,
      fillerHorses: [FILLER_HORSE_B, FILLER_HORSE_C],
    } as never);

    renderHook(() => useRacePageData("race-1"));

    expect(NarrativeGenerator).toHaveBeenCalledTimes(1);
    const constructorArgs = vi.mocked(NarrativeGenerator).mock.calls[0];
    // args: (race, horses, stables, rng)
    const horsesArg = constructorArgs[1] as Horse[];
    const horseIds = horsesArg.map((h) => h.id);

    // Store horse + both filler horses should be present
    expect(horseIds).toContain("store-a");
    expect(horseIds).toContain("filler-b");
    expect(horseIds).toContain("filler-c");
    expect(horseIds).toHaveLength(3);
  });

  it("does not duplicate horses already in the store when fillers overlap", () => {
    // Simulate a filler that happens to share an ID with a store horse
    const overlappingFiller = { ...STORE_HORSE_A } as Horse;
    vi.mocked(buildRaceField).mockReturnValue({
      runners: RUNNERS,
      fillerHorses: [overlappingFiller, FILLER_HORSE_B],
    } as never);

    renderHook(() => useRacePageData("race-1"));

    const constructorArgs = vi.mocked(NarrativeGenerator).mock.calls[0];
    const horsesArg = constructorArgs[1] as Horse[];
    const horseIds = horsesArg.map((h) => h.id);

    // store-a appears once from the store, once from fillers → 2 occurrences.
    // The NarrativeGenerator constructor builds a Map (horsesMap), so the last
    // one wins. This test documents the current behavior: the array may contain
    // duplicates, but the Map inside NarrativeGenerator deduplicates by ID.
    expect(horseIds.filter((id) => id === "store-a")).toHaveLength(2);
    expect(horseIds).toContain("filler-b");
  });
});
