/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StallionsRouteImport } from './routes/stallions'
import { Route as StableRouteImport } from './routes/stable'
import { Route as SireWatchRouteImport } from './routes/sire-watch'
import { Route as SireLeaderboardsRouteImport } from './routes/sire-leaderboards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as RacesRouteImport } from './routes/races'
import { Route as RaceBrowserRouteImport } from './routes/race-browser'
import { Route as NpcStablesRouteImport } from './routes/npc-stables'
import { Route as MarketRouteImport } from './routes/market'
import { Route as JockeysRouteImport } from './routes/jockeys'
import { Route as HorseGalleryRouteImport } from './routes/horse-gallery'
import { Route as FinancialReportRouteImport } from './routes/financial-report'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as BroodmaresRouteImport } from './routes/broodmares'
import { Route as BreedingRouteImport } from './routes/breeding'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as StableHorseIdRouteImport } from './routes/stable.$horseId'
import { Route as SireWatchStallionIdRouteImport } from './routes/sire-watch.$stallionId'
import { Route as RaceRaceIdRouteImport } from './routes/race.$raceId'
import { Route as NpcStablesStableIdRouteImport } from './routes/npc-stables.$stableId'
import { Route as CalendarRegionIdRouteImport } from './routes/calendar.$regionId'
import { Route as AuctionSalesRouteImport } from './routes/auction.sales'
import { Route as AuctionSaleIdRouteImport } from './routes/auction.$saleId'

const StallionsRoute = StallionsRouteImport.update({
  id: '/stallions',
  path: '/stallions',
  getParentRoute: () => rootRouteImport,
} as any)
const StableRoute = StableRouteImport.update({
  id: '/stable',
  path: '/stable',
  getParentRoute: () => rootRouteImport,
} as any)
const SireWatchRoute = SireWatchRouteImport.update({
  id: '/sire-watch',
  path: '/sire-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SireLeaderboardsRoute = SireLeaderboardsRouteImport.update({
  id: '/sire-leaderboards',
  path: '/sire-leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRoute = RacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceBrowserRoute = RaceBrowserRouteImport.update({
  id: '/race-browser',
  path: '/race-browser',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcStablesRoute = NpcStablesRouteImport.update({
  id: '/npc-stables',
  path: '/npc-stables',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const JockeysRoute = JockeysRouteImport.update({
  id: '/jockeys',
  path: '/jockeys',
  getParentRoute: () => rootRouteImport,
} as any)
const HorseGalleryRoute = HorseGalleryRouteImport.update({
  id: '/horse-gallery',
  path: '/horse-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialReportRoute = FinancialReportRouteImport.update({
  id: '/financial-report',
  path: '/financial-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BroodmaresRoute = BroodmaresRouteImport.update({
  id: '/broodmares',
  path: '/broodmares',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedingRoute = BreedingRouteImport.update({
  id: '/breeding',
  path: '/breeding',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const StableHorseIdRoute = StableHorseIdRouteImport.update({
  id: '/$horseId',
  path: '/$horseId',
  getParentRoute: () => StableRoute,
} as any)
const SireWatchStallionIdRoute = SireWatchStallionIdRouteImport.update({
  id: '/$stallionId',
  path: '/$stallionId',
  getParentRoute: () => SireWatchRoute,
} as any)
const RaceRaceIdRoute = RaceRaceIdRouteImport.update({
  id: '/race/$raceId',
  path: '/race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcStablesStableIdRoute = NpcStablesStableIdRouteImport.update({
  id: '/$stableId',
  path: '/$stableId',
  getParentRoute: () => NpcStablesRoute,
} as any)
const CalendarRegionIdRoute = CalendarRegionIdRouteImport.update({
  id: '/calendar/$regionId',
  path: '/calendar/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionSalesRoute = AuctionSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuctionRoute,
} as any)
const AuctionSaleIdRoute = AuctionSaleIdRouteImport.update({
  id: '/$saleId',
  path: '/$saleId',
  getParentRoute: () => AuctionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRouteWithChildren
  '/awards': typeof AwardsRoute
  '/breeding': typeof BreedingRoute
  '/broodmares': typeof BroodmaresRoute
  '/facilities': typeof FacilitiesRoute
  '/financial-report': typeof FinancialReportRoute
  '/horse-gallery': typeof HorseGalleryRoute
  '/jockeys': typeof JockeysRoute
  '/market': typeof MarketRoute
  '/npc-stables': typeof NpcStablesRouteWithChildren
  '/race-browser': typeof RaceBrowserRoute
  '/races': typeof RacesRoute
  '/recap': typeof RecapRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/sire-leaderboards': typeof SireLeaderboardsRoute
  '/sire-watch': typeof SireWatchRouteWithChildren
  '/stable': typeof StableRouteWithChildren
  '/stallions': typeof StallionsRoute
  '/auction/$saleId': typeof AuctionSaleIdRoute
  '/auction/sales': typeof AuctionSalesRoute
  '/calendar/$regionId': typeof CalendarRegionIdRoute
  '/npc-stables/$stableId': typeof NpcStablesStableIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/sire-watch/$stallionId': typeof SireWatchStallionIdRoute
  '/stable/$horseId': typeof StableHorseIdRoute
  '/calendar/': typeof CalendarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auction': typeof AuctionRouteWithChildren
  '/awards': typeof AwardsRoute
  '/breeding': typeof BreedingRoute
  '/broodmares': typeof BroodmaresRoute
  '/facilities': typeof FacilitiesRoute
  '/financial-report': typeof FinancialReportRoute
  '/horse-gallery': typeof HorseGalleryRoute
  '/jockeys': typeof JockeysRoute
  '/market': typeof MarketRoute
  '/npc-stables': typeof NpcStablesRouteWithChildren
  '/race-browser': typeof RaceBrowserRoute
  '/races': typeof RacesRoute
  '/recap': typeof RecapRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/sire-leaderboards': typeof SireLeaderboardsRoute
  '/sire-watch': typeof SireWatchRouteWithChildren
  '/stable': typeof StableRouteWithChildren
  '/stallions': typeof StallionsRoute
  '/auction/$saleId': typeof AuctionSaleIdRoute
  '/auction/sales': typeof AuctionSalesRoute
  '/calendar/$regionId': typeof CalendarRegionIdRoute
  '/npc-stables/$stableId': typeof NpcStablesStableIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/sire-watch/$stallionId': typeof SireWatchStallionIdRoute
  '/stable/$horseId': typeof StableHorseIdRoute
  '/calendar': typeof CalendarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auction': typeof AuctionRouteWithChildren
  '/awards': typeof AwardsRoute
  '/breeding': typeof BreedingRoute
  '/broodmares': typeof BroodmaresRoute
  '/facilities': typeof FacilitiesRoute
  '/financial-report': typeof FinancialReportRoute
  '/horse-gallery': typeof HorseGalleryRoute
  '/jockeys': typeof JockeysRoute
  '/market': typeof MarketRoute
  '/npc-stables': typeof NpcStablesRouteWithChildren
  '/race-browser': typeof RaceBrowserRoute
  '/races': typeof RacesRoute
  '/recap': typeof RecapRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/sire-leaderboards': typeof SireLeaderboardsRoute
  '/sire-watch': typeof SireWatchRouteWithChildren
  '/stable': typeof StableRouteWithChildren
  '/stallions': typeof StallionsRoute
  '/auction/$saleId': typeof AuctionSaleIdRoute
  '/auction/sales': typeof AuctionSalesRoute
  '/calendar/$regionId': typeof CalendarRegionIdRoute
  '/npc-stables/$stableId': typeof NpcStablesStableIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/sire-watch/$stallionId': typeof SireWatchStallionIdRoute
  '/stable/$horseId': typeof StableHorseIdRoute
  '/calendar/': typeof CalendarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auction'
    | '/awards'
    | '/breeding'
    | '/broodmares'
    | '/facilities'
    | '/financial-report'
    | '/horse-gallery'
    | '/jockeys'
    | '/market'
    | '/npc-stables'
    | '/race-browser'
    | '/races'
    | '/recap'
    | '/scheduler'
    | '/settings'
    | '/sire-leaderboards'
    | '/sire-watch'
    | '/stable'
    | '/stallions'
    | '/auction/$saleId'
    | '/auction/sales'
    | '/calendar/$regionId'
    | '/npc-stables/$stableId'
    | '/race/$raceId'
    | '/sire-watch/$stallionId'
    | '/stable/$horseId'
    | '/calendar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auction'
    | '/awards'
    | '/breeding'
    | '/broodmares'
    | '/facilities'
    | '/financial-report'
    | '/horse-gallery'
    | '/jockeys'
    | '/market'
    | '/npc-stables'
    | '/race-browser'
    | '/races'
    | '/recap'
    | '/scheduler'
    | '/settings'
    | '/sire-leaderboards'
    | '/sire-watch'
    | '/stable'
    | '/stallions'
    | '/auction/$saleId'
    | '/auction/sales'
    | '/calendar/$regionId'
    | '/npc-stables/$stableId'
    | '/race/$raceId'
    | '/sire-watch/$stallionId'
    | '/stable/$horseId'
    | '/calendar'
  id:
    | '__root__'
    | '/'
    | '/auction'
    | '/awards'
    | '/breeding'
    | '/broodmares'
    | '/facilities'
    | '/financial-report'
    | '/horse-gallery'
    | '/jockeys'
    | '/market'
    | '/npc-stables'
    | '/race-browser'
    | '/races'
    | '/recap'
    | '/scheduler'
    | '/settings'
    | '/sire-leaderboards'
    | '/sire-watch'
    | '/stable'
    | '/stallions'
    | '/auction/$saleId'
    | '/auction/sales'
    | '/calendar/$regionId'
    | '/npc-stables/$stableId'
    | '/race/$raceId'
    | '/sire-watch/$stallionId'
    | '/stable/$horseId'
    | '/calendar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionRoute: typeof AuctionRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  BreedingRoute: typeof BreedingRoute
  BroodmaresRoute: typeof BroodmaresRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FinancialReportRoute: typeof FinancialReportRoute
  HorseGalleryRoute: typeof HorseGalleryRoute
  JockeysRoute: typeof JockeysRoute
  MarketRoute: typeof MarketRoute
  NpcStablesRoute: typeof NpcStablesRouteWithChildren
  RaceBrowserRoute: typeof RaceBrowserRoute
  RacesRoute: typeof RacesRoute
  RecapRoute: typeof RecapRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
  SireLeaderboardsRoute: typeof SireLeaderboardsRoute
  SireWatchRoute: typeof SireWatchRouteWithChildren
  StableRoute: typeof StableRouteWithChildren
  StallionsRoute: typeof StallionsRoute
  CalendarRegionIdRoute: typeof CalendarRegionIdRoute
  RaceRaceIdRoute: typeof RaceRaceIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stallions': {
      id: '/stallions'
      path: '/stallions'
      fullPath: '/stallions'
      preLoaderRoute: typeof StallionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable': {
      id: '/stable'
      path: '/stable'
      fullPath: '/stable'
      preLoaderRoute: typeof StableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sire-watch': {
      id: '/sire-watch'
      path: '/sire-watch'
      fullPath: '/sire-watch'
      preLoaderRoute: typeof SireWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sire-leaderboards': {
      id: '/sire-leaderboards'
      path: '/sire-leaderboards'
      fullPath: '/sire-leaderboards'
      preLoaderRoute: typeof SireLeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races': {
      id: '/races'
      path: '/races'
      fullPath: '/races'
      preLoaderRoute: typeof RacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race-browser': {
      id: '/race-browser'
      path: '/race-browser'
      fullPath: '/race-browser'
      preLoaderRoute: typeof RaceBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npc-stables': {
      id: '/npc-stables'
      path: '/npc-stables'
      fullPath: '/npc-stables'
      preLoaderRoute: typeof NpcStablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jockeys': {
      id: '/jockeys'
      path: '/jockeys'
      fullPath: '/jockeys'
      preLoaderRoute: typeof JockeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horse-gallery': {
      id: '/horse-gallery'
      path: '/horse-gallery'
      fullPath: '/horse-gallery'
      preLoaderRoute: typeof HorseGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-report': {
      id: '/financial-report'
      path: '/financial-report'
      fullPath: '/financial-report'
      preLoaderRoute: typeof FinancialReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broodmares': {
      id: '/broodmares'
      path: '/broodmares'
      fullPath: '/broodmares'
      preLoaderRoute: typeof BroodmaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeding': {
      id: '/breeding'
      path: '/breeding'
      fullPath: '/breeding'
      preLoaderRoute: typeof BreedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/$horseId': {
      id: '/stable/$horseId'
      path: '/$horseId'
      fullPath: '/stable/$horseId'
      preLoaderRoute: typeof StableHorseIdRouteImport
      parentRoute: typeof StableRoute
    }
    '/sire-watch/$stallionId': {
      id: '/sire-watch/$stallionId'
      path: '/$stallionId'
      fullPath: '/sire-watch/$stallionId'
      preLoaderRoute: typeof SireWatchStallionIdRouteImport
      parentRoute: typeof SireWatchRoute
    }
    '/race/$raceId': {
      id: '/race/$raceId'
      path: '/race/$raceId'
      fullPath: '/race/$raceId'
      preLoaderRoute: typeof RaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npc-stables/$stableId': {
      id: '/npc-stables/$stableId'
      path: '/$stableId'
      fullPath: '/npc-stables/$stableId'
      preLoaderRoute: typeof NpcStablesStableIdRouteImport
      parentRoute: typeof NpcStablesRoute
    }
    '/calendar/$regionId': {
      id: '/calendar/$regionId'
      path: '/calendar/$regionId'
      fullPath: '/calendar/$regionId'
      preLoaderRoute: typeof CalendarRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/sales': {
      id: '/auction/sales'
      path: '/sales'
      fullPath: '/auction/sales'
      preLoaderRoute: typeof AuctionSalesRouteImport
      parentRoute: typeof AuctionRoute
    }
    '/auction/$saleId': {
      id: '/auction/$saleId'
      path: '/$saleId'
      fullPath: '/auction/$saleId'
      preLoaderRoute: typeof AuctionSaleIdRouteImport
      parentRoute: typeof AuctionRoute
    }
  }
}

interface AuctionRouteChildren {
  AuctionSaleIdRoute: typeof AuctionSaleIdRoute
  AuctionSalesRoute: typeof AuctionSalesRoute
}

const AuctionRouteChildren: AuctionRouteChildren = {
  AuctionSaleIdRoute: AuctionSaleIdRoute,
  AuctionSalesRoute: AuctionSalesRoute,
}

const AuctionRouteWithChildren =
  AuctionRoute._addFileChildren(AuctionRouteChildren)

interface NpcStablesRouteChildren {
  NpcStablesStableIdRoute: typeof NpcStablesStableIdRoute
}

const NpcStablesRouteChildren: NpcStablesRouteChildren = {
  NpcStablesStableIdRoute: NpcStablesStableIdRoute,
}

const NpcStablesRouteWithChildren = NpcStablesRoute._addFileChildren(
  NpcStablesRouteChildren,
)

interface SireWatchRouteChildren {
  SireWatchStallionIdRoute: typeof SireWatchStallionIdRoute
}

const SireWatchRouteChildren: SireWatchRouteChildren = {
  SireWatchStallionIdRoute: SireWatchStallionIdRoute,
}

const SireWatchRouteWithChildren = SireWatchRoute._addFileChildren(
  SireWatchRouteChildren,
)

interface StableRouteChildren {
  StableHorseIdRoute: typeof StableHorseIdRoute
}

const StableRouteChildren: StableRouteChildren = {
  StableHorseIdRoute: StableHorseIdRoute,
}

const StableRouteWithChildren =
  StableRoute._addFileChildren(StableRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionRoute: AuctionRouteWithChildren,
  AwardsRoute: AwardsRoute,
  BreedingRoute: BreedingRoute,
  BroodmaresRoute: BroodmaresRoute,
  FacilitiesRoute: FacilitiesRoute,
  FinancialReportRoute: FinancialReportRoute,
  HorseGalleryRoute: HorseGalleryRoute,
  JockeysRoute: JockeysRoute,
  MarketRoute: MarketRoute,
  NpcStablesRoute: NpcStablesRouteWithChildren,
  RaceBrowserRoute: RaceBrowserRoute,
  RacesRoute: RacesRoute,
  RecapRoute: RecapRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
  SireLeaderboardsRoute: SireLeaderboardsRoute,
  SireWatchRoute: SireWatchRouteWithChildren,
  StableRoute: StableRouteWithChildren,
  StallionsRoute: StallionsRoute,
  CalendarRegionIdRoute: CalendarRegionIdRoute,
  RaceRaceIdRoute: RaceRaceIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
