/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as StallionsRouteImport } from './routes/stallions'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StableRouteImport } from './routes/stable'
import { Route as SireWatchRouteImport } from './routes/sire-watch'
import { Route as SireLeaderboardsRouteImport } from './routes/sire-leaderboards'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as RacingRouteImport } from './routes/racing'
import { Route as RacesRouteImport } from './routes/races'
import { Route as RaceBrowserRouteImport } from './routes/race-browser'
import { Route as NpcStablesRouteImport } from './routes/npc-stables'
import { Route as NewGameRouteImport } from './routes/new-game'
import { Route as MarketRouteImport } from './routes/market'
import { Route as JockeysRouteImport } from './routes/jockeys'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HorseGalleryRouteImport } from './routes/horse-gallery'
import { Route as HonorsRouteImport } from './routes/honors'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as GazetteRouteImport } from './routes/gazette'
import { Route as FinancialReportRouteImport } from './routes/financial-report'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BroodmaresRouteImport } from './routes/broodmares'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as BreedingRouteImport } from './routes/breeding'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AuctionRouteImport } from './routes/auction'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StableIndexRouteImport } from './routes/stable.index'
import { Route as SireWatchIndexRouteImport } from './routes/sire-watch.index'
import { Route as NpcStablesIndexRouteImport } from './routes/npc-stables.index'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as AuctionIndexRouteImport } from './routes/auction.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as SyndicateSyndicateIdRouteImport } from './routes/syndicate.$syndicateId'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'
import { Route as StableHorseIdRouteImport } from './routes/stable.$horseId'
import { Route as SireWatchStallionIdRouteImport } from './routes/sire-watch.$stallionId'
import { Route as RaceRaceIdRouteImport } from './routes/race.$raceId'
import { Route as NpcStablesStableIdRouteImport } from './routes/npc-stables.$stableId'
import { Route as JockeyJockeyIdRouteImport } from './routes/jockey.$jockeyId'
import { Route as FoalDevelopmentHorseIdRouteImport } from './routes/foal-development.$horseId'
import { Route as CalendarRegionIdRouteImport } from './routes/calendar.$regionId'
import { Route as AuctionSaleIdRouteImport } from './routes/auction.$saleId'
import { Route as AnalyticsStableRouteImport } from './routes/analytics.stable'
import { Route as AnalyticsRacingRouteImport } from './routes/analytics.racing'
import { Route as AnalyticsFinanceRouteImport } from './routes/analytics.finance'
import { Route as AnalyticsBreedingRouteImport } from './routes/analytics.breeding'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StallionsRoute = StallionsRouteImport.update({
  id: '/stallions',
  path: '/stallions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StableRoute = StableRouteImport.update({
  id: '/stable',
  path: '/stable',
  getParentRoute: () => rootRouteImport,
} as any)
const SireWatchRoute = SireWatchRouteImport.update({
  id: '/sire-watch',
  path: '/sire-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SireLeaderboardsRoute = SireLeaderboardsRouteImport.update({
  id: '/sire-leaderboards',
  path: '/sire-leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const RacingRoute = RacingRouteImport.update({
  id: '/racing',
  path: '/racing',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRoute = RacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceBrowserRoute = RaceBrowserRouteImport.update({
  id: '/race-browser',
  path: '/race-browser',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcStablesRoute = NpcStablesRouteImport.update({
  id: '/npc-stables',
  path: '/npc-stables',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGameRoute = NewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const JockeysRoute = JockeysRouteImport.update({
  id: '/jockeys',
  path: '/jockeys',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HorseGalleryRoute = HorseGalleryRouteImport.update({
  id: '/horse-gallery',
  path: '/horse-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorsRoute = HonorsRouteImport.update({
  id: '/honors',
  path: '/honors',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteRoute = GazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialReportRoute = FinancialReportRouteImport.update({
  id: '/financial-report',
  path: '/financial-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BroodmaresRoute = BroodmaresRouteImport.update({
  id: '/broodmares',
  path: '/broodmares',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const BreedingRoute = BreedingRouteImport.update({
  id: '/breeding',
  path: '/breeding',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionRoute = AuctionRouteImport.update({
  id: '/auction',
  path: '/auction',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StableIndexRoute = StableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StableRoute,
} as any)
const SireWatchIndexRoute = SireWatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SireWatchRoute,
} as any)
const NpcStablesIndexRoute = NpcStablesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NpcStablesRoute,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CalendarRoute,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuctionRoute,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const SyndicateSyndicateIdRoute = SyndicateSyndicateIdRouteImport.update({
  id: '/syndicate/$syndicateId',
  path: '/syndicate/$syndicateId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRoute,
} as any)
const StableHorseIdRoute = StableHorseIdRouteImport.update({
  id: '/$horseId',
  path: '/$horseId',
  getParentRoute: () => StableRoute,
} as any)
const SireWatchStallionIdRoute = SireWatchStallionIdRouteImport.update({
  id: '/$stallionId',
  path: '/$stallionId',
  getParentRoute: () => SireWatchRoute,
} as any)
const RaceRaceIdRoute = RaceRaceIdRouteImport.update({
  id: '/race/$raceId',
  path: '/race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcStablesStableIdRoute = NpcStablesStableIdRouteImport.update({
  id: '/$stableId',
  path: '/$stableId',
  getParentRoute: () => NpcStablesRoute,
} as any)
const JockeyJockeyIdRoute = JockeyJockeyIdRouteImport.update({
  id: '/jockey/$jockeyId',
  path: '/jockey/$jockeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoalDevelopmentHorseIdRoute = FoalDevelopmentHorseIdRouteImport.update({
  id: '/foal-development/$horseId',
  path: '/foal-development/$horseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRegionIdRoute = CalendarRegionIdRouteImport.update({
  id: '/$regionId',
  path: '/$regionId',
  getParentRoute: () => CalendarRoute,
} as any)
const AuctionSaleIdRoute = AuctionSaleIdRouteImport.update({
  id: '/$saleId',
  path: '/$saleId',
  getParentRoute: () => AuctionRoute,
} as any)
const AnalyticsStableRoute = AnalyticsStableRouteImport.update({
  id: '/stable',
  path: '/stable',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsRacingRoute = AnalyticsRacingRouteImport.update({
  id: '/racing',
  path: '/racing',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsFinanceRoute = AnalyticsFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsBreedingRoute = AnalyticsBreedingRouteImport.update({
  id: '/breeding',
  path: '/breeding',
  getParentRoute: () => AnalyticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auction': typeof AuctionRouteWithChildren
  '/awards': typeof AwardsRoute
  '/bookmarks': typeof BookmarksRoute
  '/breeding': typeof BreedingRoute
  '/briefing': typeof BriefingRoute
  '/broodmares': typeof BroodmaresRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/facilities': typeof FacilitiesRoute
  '/financial-report': typeof FinancialReportRoute
  '/gazette': typeof GazetteRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/honors': typeof HonorsRoute
  '/horse-gallery': typeof HorseGalleryRoute
  '/inbox': typeof InboxRoute
  '/jockeys': typeof JockeysRoute
  '/market': typeof MarketRoute
  '/new-game': typeof NewGameRoute
  '/npc-stables': typeof NpcStablesRouteWithChildren
  '/race-browser': typeof RaceBrowserRoute
  '/races': typeof RacesRoute
  '/racing': typeof RacingRoute
  '/recap': typeof RecapRoute
  '/records': typeof RecordsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/sire-leaderboards': typeof SireLeaderboardsRoute
  '/sire-watch': typeof SireWatchRouteWithChildren
  '/stable': typeof StableRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/stallions': typeof StallionsRoute
  '/start': typeof StartRoute
  '/analytics/breeding': typeof AnalyticsBreedingRoute
  '/analytics/finance': typeof AnalyticsFinanceRoute
  '/analytics/racing': typeof AnalyticsRacingRoute
  '/analytics/stable': typeof AnalyticsStableRoute
  '/auction/$saleId': typeof AuctionSaleIdRoute
  '/calendar/$regionId': typeof CalendarRegionIdRoute
  '/foal-development/$horseId': typeof FoalDevelopmentHorseIdRoute
  '/jockey/$jockeyId': typeof JockeyJockeyIdRoute
  '/npc-stables/$stableId': typeof NpcStablesStableIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/sire-watch/$stallionId': typeof SireWatchStallionIdRoute
  '/stable/$horseId': typeof StableHorseIdRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/syndicate/$syndicateId': typeof SyndicateSyndicateIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/auction/': typeof AuctionIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/npc-stables/': typeof NpcStablesIndexRoute
  '/sire-watch/': typeof SireWatchIndexRoute
  '/stable/': typeof StableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awards': typeof AwardsRoute
  '/bookmarks': typeof BookmarksRoute
  '/breeding': typeof BreedingRoute
  '/briefing': typeof BriefingRoute
  '/broodmares': typeof BroodmaresRoute
  '/facilities': typeof FacilitiesRoute
  '/financial-report': typeof FinancialReportRoute
  '/gazette': typeof GazetteRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/honors': typeof HonorsRoute
  '/horse-gallery': typeof HorseGalleryRoute
  '/inbox': typeof InboxRoute
  '/jockeys': typeof JockeysRoute
  '/market': typeof MarketRoute
  '/new-game': typeof NewGameRoute
  '/race-browser': typeof RaceBrowserRoute
  '/races': typeof RacesRoute
  '/racing': typeof RacingRoute
  '/recap': typeof RecapRoute
  '/records': typeof RecordsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/sire-leaderboards': typeof SireLeaderboardsRoute
  '/staff': typeof StaffRouteWithChildren
  '/stallions': typeof StallionsRoute
  '/start': typeof StartRoute
  '/analytics/breeding': typeof AnalyticsBreedingRoute
  '/analytics/finance': typeof AnalyticsFinanceRoute
  '/analytics/racing': typeof AnalyticsRacingRoute
  '/analytics/stable': typeof AnalyticsStableRoute
  '/auction/$saleId': typeof AuctionSaleIdRoute
  '/calendar/$regionId': typeof CalendarRegionIdRoute
  '/foal-development/$horseId': typeof FoalDevelopmentHorseIdRoute
  '/jockey/$jockeyId': typeof JockeyJockeyIdRoute
  '/npc-stables/$stableId': typeof NpcStablesStableIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/sire-watch/$stallionId': typeof SireWatchStallionIdRoute
  '/stable/$horseId': typeof StableHorseIdRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/syndicate/$syndicateId': typeof SyndicateSyndicateIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/auction': typeof AuctionIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/npc-stables': typeof NpcStablesIndexRoute
  '/sire-watch': typeof SireWatchIndexRoute
  '/stable': typeof StableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auction': typeof AuctionRouteWithChildren
  '/awards': typeof AwardsRoute
  '/bookmarks': typeof BookmarksRoute
  '/breeding': typeof BreedingRoute
  '/briefing': typeof BriefingRoute
  '/broodmares': typeof BroodmaresRoute
  '/calendar': typeof CalendarRouteWithChildren
  '/facilities': typeof FacilitiesRoute
  '/financial-report': typeof FinancialReportRoute
  '/gazette': typeof GazetteRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/honors': typeof HonorsRoute
  '/horse-gallery': typeof HorseGalleryRoute
  '/inbox': typeof InboxRoute
  '/jockeys': typeof JockeysRoute
  '/market': typeof MarketRoute
  '/new-game': typeof NewGameRoute
  '/npc-stables': typeof NpcStablesRouteWithChildren
  '/race-browser': typeof RaceBrowserRoute
  '/races': typeof RacesRoute
  '/racing': typeof RacingRoute
  '/recap': typeof RecapRoute
  '/records': typeof RecordsRoute
  '/scheduler': typeof SchedulerRoute
  '/settings': typeof SettingsRoute
  '/sire-leaderboards': typeof SireLeaderboardsRoute
  '/sire-watch': typeof SireWatchRouteWithChildren
  '/stable': typeof StableRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/stallions': typeof StallionsRoute
  '/start': typeof StartRoute
  '/analytics/breeding': typeof AnalyticsBreedingRoute
  '/analytics/finance': typeof AnalyticsFinanceRoute
  '/analytics/racing': typeof AnalyticsRacingRoute
  '/analytics/stable': typeof AnalyticsStableRoute
  '/auction/$saleId': typeof AuctionSaleIdRoute
  '/calendar/$regionId': typeof CalendarRegionIdRoute
  '/foal-development/$horseId': typeof FoalDevelopmentHorseIdRoute
  '/jockey/$jockeyId': typeof JockeyJockeyIdRoute
  '/npc-stables/$stableId': typeof NpcStablesStableIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/sire-watch/$stallionId': typeof SireWatchStallionIdRoute
  '/stable/$horseId': typeof StableHorseIdRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/syndicate/$syndicateId': typeof SyndicateSyndicateIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/auction/': typeof AuctionIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/npc-stables/': typeof NpcStablesIndexRoute
  '/sire-watch/': typeof SireWatchIndexRoute
  '/stable/': typeof StableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auction'
    | '/awards'
    | '/bookmarks'
    | '/breeding'
    | '/briefing'
    | '/broodmares'
    | '/calendar'
    | '/facilities'
    | '/financial-report'
    | '/gazette'
    | '/hall-of-fame'
    | '/honors'
    | '/horse-gallery'
    | '/inbox'
    | '/jockeys'
    | '/market'
    | '/new-game'
    | '/npc-stables'
    | '/race-browser'
    | '/races'
    | '/racing'
    | '/recap'
    | '/records'
    | '/scheduler'
    | '/settings'
    | '/sire-leaderboards'
    | '/sire-watch'
    | '/stable'
    | '/staff'
    | '/stallions'
    | '/start'
    | '/analytics/breeding'
    | '/analytics/finance'
    | '/analytics/racing'
    | '/analytics/stable'
    | '/auction/$saleId'
    | '/calendar/$regionId'
    | '/foal-development/$horseId'
    | '/jockey/$jockeyId'
    | '/npc-stables/$stableId'
    | '/race/$raceId'
    | '/sire-watch/$stallionId'
    | '/stable/$horseId'
    | '/staff/$staffId'
    | '/syndicate/$syndicateId'
    | '/analytics/'
    | '/auction/'
    | '/calendar/'
    | '/npc-stables/'
    | '/sire-watch/'
    | '/stable/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awards'
    | '/bookmarks'
    | '/breeding'
    | '/briefing'
    | '/broodmares'
    | '/facilities'
    | '/financial-report'
    | '/gazette'
    | '/hall-of-fame'
    | '/honors'
    | '/horse-gallery'
    | '/inbox'
    | '/jockeys'
    | '/market'
    | '/new-game'
    | '/race-browser'
    | '/races'
    | '/racing'
    | '/recap'
    | '/records'
    | '/scheduler'
    | '/settings'
    | '/sire-leaderboards'
    | '/staff'
    | '/stallions'
    | '/start'
    | '/analytics/breeding'
    | '/analytics/finance'
    | '/analytics/racing'
    | '/analytics/stable'
    | '/auction/$saleId'
    | '/calendar/$regionId'
    | '/foal-development/$horseId'
    | '/jockey/$jockeyId'
    | '/npc-stables/$stableId'
    | '/race/$raceId'
    | '/sire-watch/$stallionId'
    | '/stable/$horseId'
    | '/staff/$staffId'
    | '/syndicate/$syndicateId'
    | '/analytics'
    | '/auction'
    | '/calendar'
    | '/npc-stables'
    | '/sire-watch'
    | '/stable'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auction'
    | '/awards'
    | '/bookmarks'
    | '/breeding'
    | '/briefing'
    | '/broodmares'
    | '/calendar'
    | '/facilities'
    | '/financial-report'
    | '/gazette'
    | '/hall-of-fame'
    | '/honors'
    | '/horse-gallery'
    | '/inbox'
    | '/jockeys'
    | '/market'
    | '/new-game'
    | '/npc-stables'
    | '/race-browser'
    | '/races'
    | '/racing'
    | '/recap'
    | '/records'
    | '/scheduler'
    | '/settings'
    | '/sire-leaderboards'
    | '/sire-watch'
    | '/stable'
    | '/staff'
    | '/stallions'
    | '/start'
    | '/analytics/breeding'
    | '/analytics/finance'
    | '/analytics/racing'
    | '/analytics/stable'
    | '/auction/$saleId'
    | '/calendar/$regionId'
    | '/foal-development/$horseId'
    | '/jockey/$jockeyId'
    | '/npc-stables/$stableId'
    | '/race/$raceId'
    | '/sire-watch/$stallionId'
    | '/stable/$horseId'
    | '/staff/$staffId'
    | '/syndicate/$syndicateId'
    | '/analytics/'
    | '/auction/'
    | '/calendar/'
    | '/npc-stables/'
    | '/sire-watch/'
    | '/stable/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AuctionRoute: typeof AuctionRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  BookmarksRoute: typeof BookmarksRoute
  BreedingRoute: typeof BreedingRoute
  BriefingRoute: typeof BriefingRoute
  BroodmaresRoute: typeof BroodmaresRoute
  CalendarRoute: typeof CalendarRouteWithChildren
  FacilitiesRoute: typeof FacilitiesRoute
  FinancialReportRoute: typeof FinancialReportRoute
  GazetteRoute: typeof GazetteRoute
  HallOfFameRoute: typeof HallOfFameRoute
  HonorsRoute: typeof HonorsRoute
  HorseGalleryRoute: typeof HorseGalleryRoute
  InboxRoute: typeof InboxRoute
  JockeysRoute: typeof JockeysRoute
  MarketRoute: typeof MarketRoute
  NewGameRoute: typeof NewGameRoute
  NpcStablesRoute: typeof NpcStablesRouteWithChildren
  RaceBrowserRoute: typeof RaceBrowserRoute
  RacesRoute: typeof RacesRoute
  RacingRoute: typeof RacingRoute
  RecapRoute: typeof RecapRoute
  RecordsRoute: typeof RecordsRoute
  SchedulerRoute: typeof SchedulerRoute
  SettingsRoute: typeof SettingsRoute
  SireLeaderboardsRoute: typeof SireLeaderboardsRoute
  SireWatchRoute: typeof SireWatchRouteWithChildren
  StableRoute: typeof StableRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  StallionsRoute: typeof StallionsRoute
  StartRoute: typeof StartRoute
  FoalDevelopmentHorseIdRoute: typeof FoalDevelopmentHorseIdRoute
  JockeyJockeyIdRoute: typeof JockeyJockeyIdRoute
  RaceRaceIdRoute: typeof RaceRaceIdRoute
  SyndicateSyndicateIdRoute: typeof SyndicateSyndicateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stallions': {
      id: '/stallions'
      path: '/stallions'
      fullPath: '/stallions'
      preLoaderRoute: typeof StallionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable': {
      id: '/stable'
      path: '/stable'
      fullPath: '/stable'
      preLoaderRoute: typeof StableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sire-watch': {
      id: '/sire-watch'
      path: '/sire-watch'
      fullPath: '/sire-watch'
      preLoaderRoute: typeof SireWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sire-leaderboards': {
      id: '/sire-leaderboards'
      path: '/sire-leaderboards'
      fullPath: '/sire-leaderboards'
      preLoaderRoute: typeof SireLeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racing': {
      id: '/racing'
      path: '/racing'
      fullPath: '/racing'
      preLoaderRoute: typeof RacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races': {
      id: '/races'
      path: '/races'
      fullPath: '/races'
      preLoaderRoute: typeof RacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race-browser': {
      id: '/race-browser'
      path: '/race-browser'
      fullPath: '/race-browser'
      preLoaderRoute: typeof RaceBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npc-stables': {
      id: '/npc-stables'
      path: '/npc-stables'
      fullPath: '/npc-stables'
      preLoaderRoute: typeof NpcStablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jockeys': {
      id: '/jockeys'
      path: '/jockeys'
      fullPath: '/jockeys'
      preLoaderRoute: typeof JockeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horse-gallery': {
      id: '/horse-gallery'
      path: '/horse-gallery'
      fullPath: '/horse-gallery'
      preLoaderRoute: typeof HorseGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honors': {
      id: '/honors'
      path: '/honors'
      fullPath: '/honors'
      preLoaderRoute: typeof HonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazette': {
      id: '/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof GazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-report': {
      id: '/financial-report'
      path: '/financial-report'
      fullPath: '/financial-report'
      preLoaderRoute: typeof FinancialReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broodmares': {
      id: '/broodmares'
      path: '/broodmares'
      fullPath: '/broodmares'
      preLoaderRoute: typeof BroodmaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breeding': {
      id: '/breeding'
      path: '/breeding'
      fullPath: '/breeding'
      preLoaderRoute: typeof BreedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction': {
      id: '/auction'
      path: '/auction'
      fullPath: '/auction'
      preLoaderRoute: typeof AuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/': {
      id: '/stable/'
      path: '/'
      fullPath: '/stable/'
      preLoaderRoute: typeof StableIndexRouteImport
      parentRoute: typeof StableRoute
    }
    '/sire-watch/': {
      id: '/sire-watch/'
      path: '/'
      fullPath: '/sire-watch/'
      preLoaderRoute: typeof SireWatchIndexRouteImport
      parentRoute: typeof SireWatchRoute
    }
    '/npc-stables/': {
      id: '/npc-stables/'
      path: '/'
      fullPath: '/npc-stables/'
      preLoaderRoute: typeof NpcStablesIndexRouteImport
      parentRoute: typeof NpcStablesRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/auction/': {
      id: '/auction/'
      path: '/'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof AuctionRoute
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/syndicate/$syndicateId': {
      id: '/syndicate/$syndicateId'
      path: '/syndicate/$syndicateId'
      fullPath: '/syndicate/$syndicateId'
      preLoaderRoute: typeof SyndicateSyndicateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/stable/$horseId': {
      id: '/stable/$horseId'
      path: '/$horseId'
      fullPath: '/stable/$horseId'
      preLoaderRoute: typeof StableHorseIdRouteImport
      parentRoute: typeof StableRoute
    }
    '/sire-watch/$stallionId': {
      id: '/sire-watch/$stallionId'
      path: '/$stallionId'
      fullPath: '/sire-watch/$stallionId'
      preLoaderRoute: typeof SireWatchStallionIdRouteImport
      parentRoute: typeof SireWatchRoute
    }
    '/race/$raceId': {
      id: '/race/$raceId'
      path: '/race/$raceId'
      fullPath: '/race/$raceId'
      preLoaderRoute: typeof RaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npc-stables/$stableId': {
      id: '/npc-stables/$stableId'
      path: '/$stableId'
      fullPath: '/npc-stables/$stableId'
      preLoaderRoute: typeof NpcStablesStableIdRouteImport
      parentRoute: typeof NpcStablesRoute
    }
    '/jockey/$jockeyId': {
      id: '/jockey/$jockeyId'
      path: '/jockey/$jockeyId'
      fullPath: '/jockey/$jockeyId'
      preLoaderRoute: typeof JockeyJockeyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foal-development/$horseId': {
      id: '/foal-development/$horseId'
      path: '/foal-development/$horseId'
      fullPath: '/foal-development/$horseId'
      preLoaderRoute: typeof FoalDevelopmentHorseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$regionId': {
      id: '/calendar/$regionId'
      path: '/$regionId'
      fullPath: '/calendar/$regionId'
      preLoaderRoute: typeof CalendarRegionIdRouteImport
      parentRoute: typeof CalendarRoute
    }
    '/auction/$saleId': {
      id: '/auction/$saleId'
      path: '/$saleId'
      fullPath: '/auction/$saleId'
      preLoaderRoute: typeof AuctionSaleIdRouteImport
      parentRoute: typeof AuctionRoute
    }
    '/analytics/stable': {
      id: '/analytics/stable'
      path: '/stable'
      fullPath: '/analytics/stable'
      preLoaderRoute: typeof AnalyticsStableRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/racing': {
      id: '/analytics/racing'
      path: '/racing'
      fullPath: '/analytics/racing'
      preLoaderRoute: typeof AnalyticsRacingRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/finance': {
      id: '/analytics/finance'
      path: '/finance'
      fullPath: '/analytics/finance'
      preLoaderRoute: typeof AnalyticsFinanceRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/breeding': {
      id: '/analytics/breeding'
      path: '/breeding'
      fullPath: '/analytics/breeding'
      preLoaderRoute: typeof AnalyticsBreedingRouteImport
      parentRoute: typeof AnalyticsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsBreedingRoute: typeof AnalyticsBreedingRoute
  AnalyticsFinanceRoute: typeof AnalyticsFinanceRoute
  AnalyticsRacingRoute: typeof AnalyticsRacingRoute
  AnalyticsStableRoute: typeof AnalyticsStableRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsBreedingRoute: AnalyticsBreedingRoute,
  AnalyticsFinanceRoute: AnalyticsFinanceRoute,
  AnalyticsRacingRoute: AnalyticsRacingRoute,
  AnalyticsStableRoute: AnalyticsStableRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface AuctionRouteChildren {
  AuctionSaleIdRoute: typeof AuctionSaleIdRoute
  AuctionIndexRoute: typeof AuctionIndexRoute
}

const AuctionRouteChildren: AuctionRouteChildren = {
  AuctionSaleIdRoute: AuctionSaleIdRoute,
  AuctionIndexRoute: AuctionIndexRoute,
}

const AuctionRouteWithChildren =
  AuctionRoute._addFileChildren(AuctionRouteChildren)

interface CalendarRouteChildren {
  CalendarRegionIdRoute: typeof CalendarRegionIdRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarRegionIdRoute: CalendarRegionIdRoute,
  CalendarIndexRoute: CalendarIndexRoute,
}

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
)

interface NpcStablesRouteChildren {
  NpcStablesStableIdRoute: typeof NpcStablesStableIdRoute
  NpcStablesIndexRoute: typeof NpcStablesIndexRoute
}

const NpcStablesRouteChildren: NpcStablesRouteChildren = {
  NpcStablesStableIdRoute: NpcStablesStableIdRoute,
  NpcStablesIndexRoute: NpcStablesIndexRoute,
}

const NpcStablesRouteWithChildren = NpcStablesRoute._addFileChildren(
  NpcStablesRouteChildren,
)

interface SireWatchRouteChildren {
  SireWatchStallionIdRoute: typeof SireWatchStallionIdRoute
  SireWatchIndexRoute: typeof SireWatchIndexRoute
}

const SireWatchRouteChildren: SireWatchRouteChildren = {
  SireWatchStallionIdRoute: SireWatchStallionIdRoute,
  SireWatchIndexRoute: SireWatchIndexRoute,
}

const SireWatchRouteWithChildren = SireWatchRoute._addFileChildren(
  SireWatchRouteChildren,
)

interface StableRouteChildren {
  StableHorseIdRoute: typeof StableHorseIdRoute
  StableIndexRoute: typeof StableIndexRoute
}

const StableRouteChildren: StableRouteChildren = {
  StableHorseIdRoute: StableHorseIdRoute,
  StableIndexRoute: StableIndexRoute,
}

const StableRouteWithChildren =
  StableRoute._addFileChildren(StableRouteChildren)

interface StaffRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AuctionRoute: AuctionRouteWithChildren,
  AwardsRoute: AwardsRoute,
  BookmarksRoute: BookmarksRoute,
  BreedingRoute: BreedingRoute,
  BriefingRoute: BriefingRoute,
  BroodmaresRoute: BroodmaresRoute,
  CalendarRoute: CalendarRouteWithChildren,
  FacilitiesRoute: FacilitiesRoute,
  FinancialReportRoute: FinancialReportRoute,
  GazetteRoute: GazetteRoute,
  HallOfFameRoute: HallOfFameRoute,
  HonorsRoute: HonorsRoute,
  HorseGalleryRoute: HorseGalleryRoute,
  InboxRoute: InboxRoute,
  JockeysRoute: JockeysRoute,
  MarketRoute: MarketRoute,
  NewGameRoute: NewGameRoute,
  NpcStablesRoute: NpcStablesRouteWithChildren,
  RaceBrowserRoute: RaceBrowserRoute,
  RacesRoute: RacesRoute,
  RacingRoute: RacingRoute,
  RecapRoute: RecapRoute,
  RecordsRoute: RecordsRoute,
  SchedulerRoute: SchedulerRoute,
  SettingsRoute: SettingsRoute,
  SireLeaderboardsRoute: SireLeaderboardsRoute,
  SireWatchRoute: SireWatchRouteWithChildren,
  StableRoute: StableRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  StallionsRoute: StallionsRoute,
  StartRoute: StartRoute,
  FoalDevelopmentHorseIdRoute: FoalDevelopmentHorseIdRoute,
  JockeyJockeyIdRoute: JockeyJockeyIdRoute,
  RaceRaceIdRoute: RaceRaceIdRoute,
  SyndicateSyndicateIdRoute: SyndicateSyndicateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
